export const KEY_MANAGEMENT_SNAPS = [
  {
    id: '1',
    snapId: 'local:http://localhost:8080',
    iconUrl: '',
    snapTitle: 'Metamask Simple Keyring',
    snapSlug: 'Secure your account with MetaMask Mobile',
    snapDescription:
      'Threshold signature schemes (TSS) allow multiple collaborating participants to sign a message or transaction. The private key is shared between the participants using a technique called multi-party computation (MPC) which ensures that the entire private key is never exposed to any participant; the process for generating key shares is called distributed key generation (DKG). Before a signature can be generated all participants must generate key shares using DKG and store their key shares securely; the number of participants and threshold for signature generation must be decided in advance. Unlike other techniques such as Shamirs Secret Sharing (SSS) the entire private key is never revealed to any single participant and is therefore more secure as it does not have the trusted dealer problem.',
    tags: ['EOA'],
    developer: 'Metamask',
    website: 'https://www.consensys.net/',
    auditUrls: ['much secure', 'very safe'],
    version: '1.0.0',
    lastUpdated: 'April 20, 2023',
  },
  {
    id: '1',
    snapId: 'local:http://localhost:8080',
    iconUrl: '',
    snapTitle: 'Metamask Account Abstrction Snap',
    snapSlug: 'Secure your account with MetaMask Mobile',
    snapDescription:
      'Threshold signature schemes (TSS) allow multiple collaborating participants to sign a message or transaction. The private key is shared between the participants using a technique called multi-party computation (MPC) which ensures that the entire private key is never exposed to any participant; the process for generating key shares is called distributed key generation (DKG). Before a signature can be generated all participants must generate key shares using DKG and store their key shares securely; the number of participants and threshold for signature generation must be decided in advance. Unlike other techniques such as Shamirs Secret Sharing (SSS) the entire private key is never revealed to any single participant and is therefore more secure as it does not have the trusted dealer problem.',
    tags: ['4337', 'Smart Contract'],
    developer: 'Metamask',
    website: 'https://www.consensys.net/',
    auditUrls: ['much secure', 'very safe'],
    version: '1.0.0',
    lastUpdated: 'April 20, 2023',
  },
  {
    id: '1',
    snapId: 'local:http://localhost:8080',
    iconUrl: '',
    snapTitle: 'Metamask TSS',
    snapSlug: 'Secure your account with MetaMask Mobile',
    snapDescription:
      'Threshold signature schemes (TSS) allow multiple collaborating participants to sign a message or transaction. The private key is shared between the participants using a technique called multi-party computation (MPC) which ensures that the entire private key is never exposed to any participant; the process for generating key shares is called distributed key generation (DKG). Before a signature can be generated all participants must generate key shares using DKG and store their key shares securely; the number of participants and threshold for signature generation must be decided in advance. Unlike other techniques such as Shamirs Secret Sharing (SSS) the entire private key is never revealed to any single participant and is therefore more secure as it does not have the trusted dealer problem.',
    tags: ['MPC', 'Shared Custody'],
    developer: 'Metamask',
    website: 'https://www.consensys.net/',
    auditUrls: ['much secure', 'very safe'],
    version: '1.0.0',
    lastUpdated: 'April 20, 2023',
  },
  {
    id: '1',
    snapId: 'local:http://localhost:8080',
    iconUrl: '',
    snapTitle: 'Metamask TSS',
    snapSlug: 'Secure your account with MetaMask Mobile',
    snapDescription:
      'Threshold signature schemes (TSS) allow multiple collaborating participants to sign a message or transaction. The private key is shared between the participants using a technique called multi-party computation (MPC) which ensures that the entire private key is never exposed to any participant; the process for generating key shares is called distributed key generation (DKG). Before a signature can be generated all participants must generate key shares using DKG and store their key shares securely; the number of participants and threshold for signature generation must be decided in advance. Unlike other techniques such as Shamirs Secret Sharing (SSS) the entire private key is never revealed to any single participant and is therefore more secure as it does not have the trusted dealer problem.',
    tags: ['MPC', 'Shared Custody'],
    developer: 'Metamask',
    website: 'https://tss.ac/',
    auditUrls: ['auditUrl1', 'auditUrl2'],
    version: '1.0.0',
    lastUpdated: 'April 20, 2023',
  },
];
