#!/bin/sh

# stop any existing instance of trezord
killall trezord 

# start the bridge for the simulator
/Applications/Utilities/TREZOR\ Bridge/trezord -e 21324  >> /dev/null 2>&1 &

# launch simulator
/Users/bruno/repos/trezor-core/emu.sh