import { createProjectLogger } from '@metamask/utils';
import {
  BaseControllerMessenger,
  BaseRestrictedControllerMessenger,
  MessengerClientByName,
  MessengerClientInitFunction,
  MessengerClientInitRequest,
  MessengerClientName,
} from './types';
import { MessengerClient } from './controller-list';
import { CONTROLLER_MESSENGERS } from './messengers';

const log = createProjectLogger('messenger-client-init');

/** Result of initializing controllers. */
export type InitMessengerClientsResult = {
  /** All API methods exposed by the controllers. */
  controllerApi: Record<string, MessengerClient>;

  /** All controllers that provided a memory state key. */
  controllerMemState: Record<string, MessengerClient>;

  /** All controllers that provided a persisted state key. */
  controllerPersistedState: Record<string, MessengerClient>;

  /** All initialized controllers keyed by name. */
  controllersByName: MessengerClientByName;
};

type BaseControllerInitRequest = MessengerClientInitRequest<
  BaseRestrictedControllerMessenger,
  BaseRestrictedControllerMessenger | void
>;

type ControllerMessengerCallback = (
  BaseControllerMessenger: BaseControllerMessenger,
) => BaseRestrictedControllerMessenger;

export type MessengerClientsToInitialize =
  | 'AccountTrackerController'
  | 'AuthenticationController'
  | 'ClientController'
  | 'CronjobController'
  | 'DeFiPositionsController'
  | 'ExecutionService'
  | 'MultichainAssetsController'
  | 'MultichainAssetsRatesController'
  | 'MultichainBalancesController'
  | 'MultichainNetworkController'
  | 'MultichainTransactionsController'
  | 'NotificationServicesController'
  | 'NotificationServicesPushController'
  | 'RateLimitController'
  | 'SnapRegistryController'
  | 'SnapController'
  | 'SnapInsightsController'
  | 'SnapInterfaceController'
  | 'PerpsController'
  | 'PPOMController'
  | 'TransactionController'
  | 'TransactionPayController'
  | 'UserStorageController';

type InitFunction<Name extends MessengerClientsToInitialize> =
  MessengerClientInitFunction<
    MessengerClientByName[Name],
    ReturnType<(typeof CONTROLLER_MESSENGERS)[Name]['getMessenger']>,
    ReturnType<(typeof CONTROLLER_MESSENGERS)[Name]['getInitMessenger']>
  >;

export type InitFunctions = Partial<{
  [name in MessengerClientsToInitialize]: InitFunction<name>;
}>;

/**
 * Initialize the controllers according to the provided init objects.
 * Each init object can be a function that returns a controller, or a `ControllerInit` instance.
 *
 * @param options - Options bag.
 * @param options.baseControllerMessenger - Unrestricted base controller messenger.
 * @param options.existingControllers - All required controllers that have already been initialized.
 * @param options.initFunctions - Map of init functions keyed by controller name.
 * @param options.initRequest - Base request used to initialize the controllers.
 * Excluding the properties that are generated by this function.
 * @returns The initialized controllers and associated data.
 */
export function initControllers({
  baseControllerMessenger,
  existingControllers = [],
  initFunctions,
  initRequest,
}: {
  baseControllerMessenger: BaseControllerMessenger;
  existingControllers?: MessengerClient[];
  initFunctions: InitFunctions;
  initRequest: Omit<
    BaseControllerInitRequest,
    'controllerMessenger' | 'getController' | 'initMessenger'
  >;
}): InitMessengerClientsResult {
  log('Initializing controllers', Object.keys(initFunctions).length);

  const partialControllersByName = existingControllers.reduce<
    Partial<MessengerClientByName>
  >((acc, controller) => {
    // @ts-expect-error: Union too complex.
    acc[controller.name] = controller;
    return acc;
  }, {});

  const controllerPersistedState: Record<string, MessengerClient> = {};
  const controllerMemState: Record<string, MessengerClient> = {};
  let controllerApi = {};

  const getController = <Name extends MessengerClientName>(
    name: Name,
  ): MessengerClientByName[Name] =>
    getControllerOrThrow(
      partialControllersByName as MessengerClientByName,
      name,
    );

  for (const [key, value] of Object.entries(initFunctions)) {
    const controllerName = key as MessengerClientsToInitialize;
    const initFunction = value as InitFunction<typeof controllerName>;
    const messengerCallbacks = CONTROLLER_MESSENGERS[controllerName];

    const controllerMessengerCallback =
      messengerCallbacks?.getMessenger as ControllerMessengerCallback;

    const initMessengerCallback =
      messengerCallbacks?.getInitMessenger as ControllerMessengerCallback;

    const controllerMessenger = controllerMessengerCallback?.(
      baseControllerMessenger,
    );

    const initMessenger = initMessengerCallback?.(baseControllerMessenger);

    const finalInitRequest: BaseControllerInitRequest = {
      ...initRequest,
      controllerMessenger,
      getController,
      initMessenger,
    };

    const result = initFunction({
      ...finalInitRequest,
      controllerMessenger: finalInitRequest.controllerMessenger,
    });

    const {
      controller,
      persistedStateKey: persistedStateKeyRaw,
      memStateKey: memStateKeyRaw,
    } = result;

    const api = result.api ?? {};

    const persistedStateKey =
      persistedStateKeyRaw === null
        ? undefined
        : (persistedStateKeyRaw ?? controllerName);

    const memStateKey =
      memStateKeyRaw === null ? undefined : (memStateKeyRaw ?? controllerName);

    // @ts-expect-error: Union too complex.
    partialControllersByName[controllerName] = controller;

    controllerApi = {
      ...controllerApi,
      ...api,
    };

    if (persistedStateKey) {
      controllerPersistedState[persistedStateKey] = controller;
    }

    if (memStateKey) {
      controllerMemState[memStateKey] = controller;
    }

    log('Initialized controller', controllerName, {
      api: Object.keys(api),
      persistedStateKey,
      memStateKey,
    });
  }

  return {
    controllerApi,
    controllerMemState,
    controllerPersistedState,
    controllersByName: partialControllersByName as MessengerClientByName,
  };
}

function getControllerOrThrow<Name extends MessengerClientName>(
  controllersByName: MessengerClientByName,
  name: Name,
): MessengerClientByName[Name] {
  const controller = controllersByName[name];

  if (!controller) {
    throw new Error(
      `Controller requested before it was initialized: ${String(name)}`,
    );
  }

  return controller;
}
