import { createProjectLogger } from '@metamask/utils';
import {
  BaseControllerMessenger,
  BaseRestrictedControllerMessenger,
  MessengerClientByName,
  MessengerClientInitFunction,
  MessengerClientInitRequest,
  MessengerClientName,
} from './types';
import { MessengerClient } from './controller-list';
import { MESSENGER_FACTORIES } from './messengers';

const log = createProjectLogger('messenger-client-init');

/** Result of initializing messenger clients. */
export type InitMessengerClientsResult = {
  /** All API methods exposed by the messenger clients. */
  messengerClientApi: Record<string, MessengerClient>;

  /** All controllers that provided a memory state key. */
  controllerMemState: Record<string, MessengerClient>;

  /** All controllers that provided a persisted state key. */
  controllerPersistedState: Record<string, MessengerClient>;

  /** All initialized messenger clients keyed by name. */
  messengerClientsByName: MessengerClientByName;
};

type BaseMessengerClientInitRequest = MessengerClientInitRequest<
  BaseRestrictedControllerMessenger,
  BaseRestrictedControllerMessenger | void
>;

type ControllerMessengerCallback = (
  BaseControllerMessenger: BaseControllerMessenger,
) => BaseRestrictedControllerMessenger;

export type MessengerClientsToInitialize =
  | 'AccountTrackerController'
  | 'AuthenticationController'
  | 'ClientController'
  | 'CronjobController'
  | 'DeFiPositionsController'
  | 'ExecutionService'
  | 'MultichainAssetsController'
  | 'MultichainAssetsRatesController'
  | 'MultichainBalancesController'
  | 'MultichainNetworkController'
  | 'MultichainTransactionsController'
  | 'NotificationServicesController'
  | 'NotificationServicesPushController'
  | 'RateLimitController'
  | 'SnapRegistryController'
  | 'SnapController'
  | 'SnapInsightsController'
  | 'SnapInterfaceController'
  | 'GeolocationApiService'
  | 'GeolocationController'
  | 'PerpsController'
  | 'PPOMController'
  | 'TransactionController'
  | 'TransactionPayController'
  | 'UserStorageController';

type InitFunction<Name extends MessengerClientsToInitialize> =
  MessengerClientInitFunction<
    MessengerClientByName[Name],
    ReturnType<(typeof MESSENGER_FACTORIES)[Name]['getMessenger']>,
    ReturnType<(typeof MESSENGER_FACTORIES)[Name]['getInitMessenger']>
  >;

export type InitFunctions = Partial<{
  [name in MessengerClientsToInitialize]: InitFunction<name>;
}>;

/**
 * Initialize the messenger clients according to the provided init objects.
 * Each init object can be a function that returns a messenger client.
 *
 * @param options - Options bag.
 * @param options.baseControllerMessenger - Unrestricted base controller messenger.
 * @param options.initFunctions - Map of init functions keyed by messenger client name.
 * @param options.initRequest - Base request used to initialize the messenger clients.
 * Excluding the properties that are generated by this function.
 * @returns The initialized messenger clients and associated data.
 */
export function initMessengerClients({
  baseControllerMessenger,
  initFunctions,
  initRequest,
}: {
  baseControllerMessenger: BaseControllerMessenger;
  initFunctions: InitFunctions;
  initRequest: Omit<
    BaseMessengerClientInitRequest,
    'controllerMessenger' | 'getMessengerClient' | 'initMessenger'
  >;
}): InitMessengerClientsResult {
  log('Initializing messenger clients', Object.keys(initFunctions).length);

  const partialMessengerClientsByName: Partial<MessengerClientByName> = {};

  const controllerPersistedState: Record<string, MessengerClient> = {};
  const controllerMemState: Record<string, MessengerClient> = {};
  let messengerClientApi = {};

  const getMessengerClient = <Name extends MessengerClientName>(
    name: Name,
  ): MessengerClientByName[Name] =>
    getMessengerClientOrThrow(
      partialMessengerClientsByName as MessengerClientByName,
      name,
    );

  for (const [key, value] of Object.entries(initFunctions)) {
    const messengerClientName = key as MessengerClientsToInitialize;
    const initFunction = value as InitFunction<typeof messengerClientName>;
    const messengerCallbacks = MESSENGER_FACTORIES[messengerClientName];

    const controllerMessengerCallback =
      messengerCallbacks?.getMessenger as ControllerMessengerCallback;

    const initMessengerCallback =
      messengerCallbacks?.getInitMessenger as ControllerMessengerCallback;

    const controllerMessenger = controllerMessengerCallback?.(
      baseControllerMessenger,
    );

    const initMessenger = initMessengerCallback?.(baseControllerMessenger);

    const finalInitRequest: BaseMessengerClientInitRequest = {
      ...initRequest,
      controllerMessenger,
      getMessengerClient,
      initMessenger,
    };

    const result = initFunction({
      ...finalInitRequest,
      controllerMessenger: finalInitRequest.controllerMessenger,
    });

    const {
      messengerClient,
      persistedStateKey: persistedStateKeyRaw,
      memStateKey: memStateKeyRaw,
    } = result;

    const api = result.api ?? {};

    const persistedStateKey =
      persistedStateKeyRaw === null
        ? undefined
        : (persistedStateKeyRaw ?? messengerClientName);

    const memStateKey =
      memStateKeyRaw === null
        ? undefined
        : (memStateKeyRaw ?? messengerClientName);

    // @ts-expect-error: Union too complex.
    partialMessengerClientsByName[messengerClientName] = messengerClient;

    messengerClientApi = {
      ...messengerClientApi,
      ...api,
    };

    if (persistedStateKey) {
      controllerPersistedState[persistedStateKey] = messengerClient;
    }

    if (memStateKey) {
      controllerMemState[memStateKey] = messengerClient;
    }

    log('Initialized messenger client', messengerClientName, {
      api: Object.keys(api),
      persistedStateKey,
      memStateKey,
    });
  }

  return {
    messengerClientApi,
    controllerMemState,
    controllerPersistedState,
    messengerClientsByName:
      partialMessengerClientsByName as MessengerClientByName,
  };
}

function getMessengerClientOrThrow<Name extends MessengerClientName>(
  messengerClientsByName: MessengerClientByName,
  name: Name,
): MessengerClientByName[Name] {
  const messengerClient = messengerClientsByName[name];

  if (!messengerClient) {
    throw new Error(
      `Messenger client requested before it was initialized: ${String(name)}`,
    );
  }

  return messengerClient;
}
