import {
  Messenger,
  MessengerActions,
  MessengerEvents,
} from '@metamask/messenger';
import { LegacyBackgroundApiServiceMessenger } from '../../services/legacy-background-api-service';
import { RootMessenger } from '../../lib/messenger';

/**
 * Create a messenger restricted to the allowed actions and events of the
 * background API service.
 * @param messenger - The base messenger used to create the restricted messenger.
 * @returns The messenger restricted to the allowed actions and events of the background API service.
 */
export function getLegacyBackgroundApiServiceMessenger(
  messenger: RootMessenger<
    MessengerActions<LegacyBackgroundApiServiceMessenger>,
    MessengerEvents<LegacyBackgroundApiServiceMessenger>
  >,
) {
  const serviceMessenger: LegacyBackgroundApiServiceMessenger = new Messenger({
    namespace: 'LegacyBackgroundApiService',
    parent: messenger,
  });

  messenger.delegate({
    messenger: serviceMessenger,
    actions: [
      'NetworkController:getState',
      'NetworkController:findNetworkClientIdByChainId',
      'NetworkController:getNetworkClientById',
      'NetworkController:getNetworkConfigurationByNetworkClientId',
      'SelectedNetworkController:getNetworkClientIdForDomain',
      'NetworkController:getSelectedNetworkClient',
      'NetworkController:addNetwork',
      'NetworkController:setActiveNetwork',
      'NetworkController:lookupNetwork',
      'NetworkEnablementController:getState',
      'NetworkEnablementController:enableNetwork',
      'NetworkEnablementController:enableAllPopularNetworks',
      'NetworkEnablementController:isNetworkEnabled',
      'NetworkEnablementController:restoreEnabledNetworkMap',
      'RemoteFeatureFlagController:getState',
      'CurrencyRateController:setCurrentCurrency',
      'AssetsContractController:getTokenStandardAndDetails',
      'AssetsController:getAssets',
      'AssetsController:getState',
      'AssetsController:setSelectedCurrency',
      'TokenListController:getState',
      'TokensController:getState',
      'KeyringController:exportSeedPhrase',
      'KeyringController:getState',
      'AccountsController:getSelectedAccount',
      'AccountsController:getState',
      'ApprovalController:add',
      'ApprovalController:getState',
      'ApprovalController:hasRequest',
      'ApprovalController:acceptRequest',
      'AppStateController:getState',
      'SnapInterfaceController:deleteInterface',
      'SnapController:clearState',
      'TransactionController:getNonceLock',
      'TransactionController:getState',
      'TransactionController:clearUnapprovedTransactions',
      'ApprovalController:rejectRequest',
      'TransactionController:wipeTransactions',
      'SmartTransactionsController:wipeSmartTransactions',
      'BridgeStatusController:wipeBridgeStatus',
      'NetworkController:resetConnection',
      'KeyringController:importAccountWithStrategy',
      'OnboardingController:getIsSocialLoginFlow',
      'KeyringController:withController',
      'KeyringController:withKeyringV2',
      'KeyringController:withKeyringV2Unsafe',
      'KeyringController:removeAccount',
      'AccountsController:getAccount',
      'AccountsController:getAccountByAddress',
      'AccountsController:listAccounts',
      'AccountsController:setAccountName',
      'AccountsController:setSelectedAccount',
      'SeedlessOnboardingController:addNewSecretData',
      'SeedlessOnboardingController:changePassword',
      'SeedlessOnboardingController:createToprfKeyAndBackupSeedPhrase',
      'SeedlessOnboardingController:fetchAllSecretData',
      'SeedlessOnboardingController:getSecretDataBackupState',
      'SeedlessOnboardingController:updateBackupMetadataState',
      'PermissionController:clearState',
      'PermissionController:rejectPermissionsRequest',
      'PermissionController:revokePermissions',
      'PermissionController:updatePermissionsByCaveat',
      'KeyringController:getKeyringsByType',
      'KeyringController:addNewKeyring',
      'PreferencesController:getState',
      'PreferencesController:addReferralApprovedAccount',
      'PreferencesController:addReferralDeclinedAccount',
      'PreferencesController:addReferralPassedAccount',
      'PreferencesController:removeReferralDeclinedAccount',
      'PreferencesController:setAccountsReferralApproved',
      'PreferencesController:setPasswordForgotten',
      'PasskeyController:unlockWithPasskey',
      'PasskeyController:changePasswordWithPasskeyVerification',
      'PasskeyController:exportSeedPhraseWithPasskey',
      'OnboardingController:getState',
      'SeedlessOnboardingController:checkIsPasswordOutdated',
      'SeedlessOnboardingController:getState',
      'SeedlessOnboardingController:runMigrations',
      'MetaMetricsController:createEventFragment',
      'MetaMetricsController:getEventFragmentById',
      'MetaMetricsController:updateEventFragment',
      'KeyringController:verifyPassword',
      'KeyringController:exportAccount',
      'KeyringController:changePassword',
      'KeyringController:exportEncryptionKey',
      'KeyringController:setLocked',
      'KeyringController:submitEncryptionKey',
      'KeyringController:submitPassword',
      'SeedlessOnboardingController:loadKeyringEncryptionKey',
      'SeedlessOnboardingController:revokePendingRefreshTokens',
      'SeedlessOnboardingController:setLocked',
      'SeedlessOnboardingController:storeKeyringEncryptionKey',
      'SeedlessOnboardingController:submitGlobalPassword',
      'SeedlessOnboardingController:submitPassword',
      'SeedlessOnboardingController:syncLatestGlobalPassword',
      'AccountsController:updateAccounts',
      'AccountOrderController:updateHiddenAccountsList',
      'AccountTreeController:clearState',
      'AccountTreeController:init',
      'AccountTreeController:reinit',
      'AccountTreeController:getSelectedAccountGroup',
      'AccountTreeController:syncWithUserStorage',
      'AccountTreeController:syncWithUserStorageAtLeastOnce',
      'AppStateController:getIsWalletResetInProgress',
      'AppStateController:setIsWalletResetInProgress',
      'MultichainAccountService:createMultichainAccountWallet',
      'MultichainAccountService:getMultichainAccountWallet',
      'MultichainAccountService:init',
      'MultichainAccountService:removeMultichainAccountWallet',
      'MultichainAccountService:resyncAccounts',
      'MultichainAccountService:alignWallets',
      'SubscriptionController:stopAllPolling',
      'AuthenticationController:getState',
      'AuthenticationController:performSignOut',
      'AppStateController:setPasskeyAutoUnlockSuppressed',
      'AppStateController:setTrezorModel',
      'MetaMetricsController:bufferedTrace',
      'MetaMetricsController:bufferedEndTrace',
      'TransactionController:updateEditableParams',
      'TransactionController:estimateGas',
      'TransactionController:isAtomicBatchSupported',
      'DelegationController:signDelegation',
      'KeyringController:signEip7702Authorization',
      'PermissionController:acceptPermissionsRequest',
      'PhishingController:maybeUpdateState',
      'PhishingController:testOrigin',
      'PreferencesController:toggleExternalServices',
      'SubscriptionController:getState',
      'TokenDetectionController:enable',
      'TokenDetectionController:disable',
      'GasFeeController:enableNonRPCGasFeeApis',
      'GasFeeController:disableNonRPCGasFeeApis',
      'ShieldController:start',
      'ShieldController:stop',
      'TransactionController:addTransaction',
      'TransactionController:addTransactionBatch',
      'TransactionController:updateSecurityAlertResponse',
      'UserOperationController:addUserOperationFromTransaction',
      'UserOperationController:startPollingByNetworkClientId',
      'PPOMController:usePPOM',
      'KeyringController:getKeyringForAccount',
      'SignatureController:getState',
      'AppStateController:getAddressSecurityAlertResponse',
      'AppStateController:addAddressSecurityAlertResponse',
      'AppStateController:addSignatureSecurityAlertResponse',
      'PhishingController:scanAddress',
      'SubscriptionController:getSubscriptionByProduct',
      'AuthenticationController:getBearerToken',
      'ShieldController:clearState',
      'SeedlessOnboardingController:clearState',
      'PasskeyController:clearState',
      'SubscriptionController:clearState',
      'ClaimsController:clearState',
      'AddressBookController:clear',
      'PreferencesController:resetState',
      'OnboardingController:resetOnboarding',
    ],
    events: [
      'NetworkEnablementController:stateChange',
      'TransactionController:unapprovedTransactionAdded',
      'SignatureController:stateChange',
    ],
  });

  return serviceMessenger;
}
