export const AUTO_LOCK_TIMEOUT_ALARM = 'AUTO_LOCK_TIMEOUT_ALARM';
export const METAMETRICS_FINALIZE_EVENT_FRAGMENT_ALARM =
  'METAMETRICS_FINALIZE_EVENT_FRAGMENT_ALARM';
export const TOKEN_LIST_FETCH_ALARM = 'TOKEN_LIST_FETCH_ALARM';
