export const AUTO_LOCK_TIMEOUT_ALARM = 'AUTO_LOCK_TIMEOUT_ALARM';
export const DETECT_TOKEN_ALARM = 'DETECT_TOKEN_ALARM';
export const METAMETRICS_FINALIZE_EVENT_FRAGMENT_ALARM =
  'METAMETRICS_FINALIZE_EVENT_FRAGMENT_ALARM';
