export const KNOWN_CHAINS = [
  { name: 'Ethereum Mainnet', chainId: 1, symbol: 'ETH' },
  { name: 'Expanse Network', chainId: 2, symbol: 'EXP' },
  { name: 'Ropsten', chainId: 3, symbol: 'ETH' },
  { name: 'Rinkeby', chainId: 4, symbol: 'ETH' },
  { name: 'Goerli', chainId: 5, symbol: 'ETH' },
  { name: 'Ethereum Classic Testnet Kotti', chainId: 6, symbol: 'KOT' },
  { name: 'ThaiChain', chainId: 7, symbol: 'TCH' },
  { name: 'Ubiq', chainId: 8, symbol: 'UBQ' },
  { name: 'Ubiq Network Testnet', chainId: 9, symbol: 'TUBQ' },
  { name: 'OP Mainnet', chainId: 10, symbol: 'ETH' },
  { name: 'Metadium Mainnet', chainId: 11, symbol: 'META' },
  { name: 'Metadium Testnet', chainId: 12, symbol: 'KAL' },
  { name: 'Diode Testnet Staging', chainId: 13, symbol: 'sDIODE' },
  { name: 'Flare Mainnet', chainId: 14, symbol: 'FLR' },
  { name: 'Diode Prenet', chainId: 15, symbol: 'DIODE' },
  { name: 'Flare Testnet Coston', chainId: 16, symbol: 'CFLR' },
  { name: 'ThaiChain 2.0 ThaiFi', chainId: 17, symbol: 'TFI' },
  { name: 'ThunderCore Testnet', chainId: 18, symbol: 'TST' },
  { name: 'Songbird Canary-Network', chainId: 19, symbol: 'SGB' },
  { name: 'Elastos Smart Chain', chainId: 20, symbol: 'ELA' },
  { name: 'Elastos Smart Chain Testnet', chainId: 21, symbol: 'tELA' },
  { name: 'ELA-DID-Sidechain Mainnet', chainId: 22, symbol: 'ELA' },
  { name: 'ELA-DID-Sidechain Testnet', chainId: 23, symbol: 'tELA' },
  { name: 'KardiaChain Mainnet', chainId: 24, symbol: 'KAI' },
  { name: 'Cronos Mainnet', chainId: 25, symbol: 'CRO' },
  { name: 'Genesis L1 testnet', chainId: 26, symbol: 'L1test' },
  { name: 'ShibaChain', chainId: 27, symbol: 'SHIB' },
  { name: 'Boba Network Rinkeby Testnet', chainId: 28, symbol: 'ETH' },
  { name: 'Genesis L1', chainId: 29, symbol: 'L1' },
  { name: 'Rootstock Mainnet', chainId: 30, symbol: 'RBTC' },
  { name: 'Rootstock Testnet', chainId: 31, symbol: 'tRBTC' },
  { name: 'GoodData Testnet', chainId: 32, symbol: 'GooD' },
  { name: 'GoodData Mainnet', chainId: 33, symbol: 'GooD' },
  { name: 'SecureChain Mainnet', chainId: 34, symbol: 'SCAI' },
  { name: 'TBWG Chain', chainId: 35, symbol: 'TBG' },
  { name: 'Dxchain Mainnet', chainId: 36, symbol: 'DX' },
  { name: 'Xpla Mainnet', chainId: 37, symbol: 'XPLA' },
  { name: 'Valorbit', chainId: 38, symbol: 'VAL' },
  { name: 'U2U Solaris Mainnet', chainId: 39, symbol: 'U2U' },
  { name: 'Telos EVM Mainnet', chainId: 40, symbol: 'TLOS' },
  { name: 'Telos EVM Testnet', chainId: 41, symbol: 'TLOS' },
  { name: 'LUKSO Mainnet', chainId: 42, symbol: 'LYX' },
  { name: 'Darwinia Pangolin Testnet', chainId: 43, symbol: 'PRING' },
  { name: 'Crab Network', chainId: 44, symbol: 'CRAB' },
  { name: 'Darwinia Pangoro Testnet', chainId: 45, symbol: 'ORING' },
  { name: 'Darwinia Network', chainId: 46, symbol: 'RING' },
  { name: 'Acria IntelliChain', chainId: 47, symbol: 'ACRIA' },
  { name: 'Ennothem Mainnet Proterozoic', chainId: 48, symbol: 'ETMP' },
  { name: 'Ennothem Testnet Pioneer', chainId: 49, symbol: 'ETMP' },
  { name: 'XDC Network', chainId: 50, symbol: 'XDC' },
  { name: 'XDC Apothem Network', chainId: 51, symbol: 'TXDC' },
  { name: 'CoinEx Smart Chain Mainnet', chainId: 52, symbol: 'cet' },
  { name: 'CoinEx Smart Chain Testnet', chainId: 53, symbol: 'cett' },
  { name: 'Openpiece Mainnet', chainId: 54, symbol: 'BELLY' },
  { name: 'Zyx Mainnet', chainId: 55, symbol: 'ZYX' },
  { name: 'BNB Smart Chain Mainnet', chainId: 56, symbol: 'BNB' },
  { name: 'Syscoin Mainnet', chainId: 57, symbol: 'SYS' },
  { name: 'Ontology Mainnet', chainId: 58, symbol: 'ONG' },
  { name: 'EOS EVM Legacy', chainId: 59, symbol: 'EOS' },
  { name: 'GoChain', chainId: 60, symbol: 'GO' },
  { name: 'Ethereum Classic Mainnet', chainId: 61, symbol: 'ETC' },
  { name: 'Ethereum Classic Testnet Morden', chainId: 62, symbol: 'TETC' },
  { name: 'Ethereum Classic Testnet Mordor', chainId: 63, symbol: 'METC' },
  { name: 'Ellaism', chainId: 64, symbol: 'ELLA' },
  { name: 'OKExChain Testnet', chainId: 65, symbol: 'OKT' },
  { name: 'OKXChain Mainnet', chainId: 66, symbol: 'OKT' },
  { name: 'DBChain Testnet', chainId: 67, symbol: 'DBM' },
  { name: 'SoterOne Mainnet', chainId: 68, symbol: 'SOTER' },
  { name: 'Optimism Kovan', chainId: 69, symbol: 'ETH' },
  { name: 'Hoo Smart Chain', chainId: 70, symbol: 'HOO' },
  { name: 'Conflux eSpace (Testnet)', chainId: 71, symbol: 'CFX' },
  { name: 'DxChain Testnet', chainId: 72, symbol: 'DX' },
  { name: 'FNCY', chainId: 73, symbol: 'FNCY' },
  { name: 'IDChain Mainnet', chainId: 74, symbol: 'EIDI' },
  { name: 'Decimal Smart Chain Mainnet', chainId: 75, symbol: 'DEL' },
  { name: 'Mix', chainId: 76, symbol: 'MIX' },
  { name: 'POA Network Sokol', chainId: 77, symbol: 'SPOA' },
  { name: 'PrimusChain mainnet', chainId: 78, symbol: 'PETH' },
  { name: 'Zenith Mainnet', chainId: 79, symbol: 'ZENITH' },
  { name: 'GeneChain', chainId: 80, symbol: 'RNA' },
  { name: 'Japan Open Chain Mainnet', chainId: 81, symbol: 'JOC' },
  { name: 'Meter Mainnet', chainId: 82, symbol: 'MTR' },
  { name: 'Meter Testnet', chainId: 83, symbol: 'MTR' },
  { name: 'Linqto Devnet', chainId: 84, symbol: 'XRP' },
  { name: 'GateChain Testnet', chainId: 85, symbol: 'GT' },
  { name: 'GateChain Mainnet', chainId: 86, symbol: 'GT' },
  { name: 'Nova Network', chainId: 87, symbol: 'SNT' },
  { name: 'TomoChain', chainId: 88, symbol: 'TOMO' },
  { name: 'TomoChain Testnet', chainId: 89, symbol: 'TOMO' },
  { name: 'Garizon Stage0', chainId: 90, symbol: 'GAR' },
  { name: 'Garizon Stage1', chainId: 91, symbol: 'GAR' },
  { name: 'Garizon Stage2', chainId: 92, symbol: 'GAR' },
  { name: 'Garizon Stage3', chainId: 93, symbol: 'GAR' },
  { name: 'SwissDLT', chainId: 94, symbol: 'BCTS' },
  { name: 'CamDL Mainnet', chainId: 95, symbol: 'CADL' },
  { name: 'Bitkub Chain', chainId: 96, symbol: 'KUB' },
  { name: 'BNB Smart Chain Testnet', chainId: 97, symbol: 'tBNB' },
  { name: 'Six Protocol', chainId: 98, symbol: 'SIX' },
  { name: 'POA Network Core', chainId: 99, symbol: 'POA' },
  { name: 'Gnosis', chainId: 100, symbol: 'XDAI' },
  { name: 'EtherInc', chainId: 101, symbol: 'ETI' },
  { name: 'Web3Games Testnet', chainId: 102, symbol: 'W3G' },
  { name: 'Worldland Mainnet', chainId: 103, symbol: 'WL' },
  { name: 'Kaiba Lightning Chain Testnet', chainId: 104, symbol: 'tKAIBA' },
  { name: 'Web3Games Devnet', chainId: 105, symbol: 'W3G' },
  { name: 'Velas EVM Mainnet', chainId: 106, symbol: 'VLX' },
  { name: 'Nebula Testnet', chainId: 107, symbol: 'NBX' },
  { name: 'ThunderCore Mainnet', chainId: 108, symbol: 'TT' },
  { name: 'Shibarium', chainId: 109, symbol: 'BONE' },
  { name: 'Proton Testnet', chainId: 110, symbol: 'XPR' },
  { name: 'EtherLite Chain', chainId: 111, symbol: 'ETL' },
  { name: 'Coinbit Mainnet', chainId: 112, symbol: 'GIDR' },
  { name: 'Dehvo', chainId: 113, symbol: 'Deh' },
  { name: 'Flare Testnet Coston2', chainId: 114, symbol: 'C2FLR' },
  { name: 'DeBank Testnet(Deprecated)', chainId: 115, symbol: 'ETH' },
  { name: 'DeBank Mainnet', chainId: 116, symbol: 'ETH' },
  { name: 'Uptick Mainnet', chainId: 117, symbol: 'UPTICK' },
  { name: 'Arcology Testnet', chainId: 118, symbol: 'Acol' },
  { name: 'ENULS Mainnet', chainId: 119, symbol: 'NULS' },
  { name: 'ENULS Testnet', chainId: 120, symbol: 'NULS' },
  { name: 'Realchain Mainnet', chainId: 121, symbol: 'REAL' },
  { name: 'Fuse Mainnet', chainId: 122, symbol: 'FUSE' },
  { name: 'Fuse Sparknet', chainId: 123, symbol: 'SPARK' },
  { name: 'Decentralized Web Mainnet', chainId: 124, symbol: 'DWU' },
  { name: 'OYchain Testnet', chainId: 125, symbol: 'OY' },
  { name: 'OYchain Mainnet', chainId: 126, symbol: 'OY' },
  { name: 'Factory 127 Mainnet', chainId: 127, symbol: 'FETH' },
  { name: 'Huobi ECO Chain Mainnet', chainId: 128, symbol: 'HT' },
  { name: 'iExec Sidechain', chainId: 134, symbol: 'xRLC' },
  { name: 'Alyx Chain Testnet', chainId: 135, symbol: 'ALYX' },
  { name: 'Deamchain Mainnet', chainId: 136, symbol: 'DEAM' },
  { name: 'Polygon Mainnet', chainId: 137, symbol: 'MATIC' },
  { name: 'Defi Oracle Meta Mainnet', chainId: 138, symbol: 'ETH' },
  { name: 'WoopChain Mainnet', chainId: 139, symbol: 'WOOC' },
  { name: 'Openpiece Testnet', chainId: 141, symbol: 'BELLY' },
  { name: 'DAX CHAIN', chainId: 142, symbol: 'DAX' },
  { name: 'PHI Network v2', chainId: 144, symbol: 'Φ' },
  { name: 'ShimmerEVM Mainnet', chainId: 148, symbol: 'SMR' },
  { name: 'Six Protocol Testnet', chainId: 150, symbol: 'tSIX' },
  { name: 'Redbelly Network Mainnet', chainId: 151, symbol: 'RBNT' },
  { name: 'Redbelly Network Devnet', chainId: 152, symbol: 'RBNT' },
  { name: 'Redbelly Network Testnet', chainId: 153, symbol: 'RBNT' },
  { name: 'Redbelly Network TGE', chainId: 154, symbol: 'RBNT' },
  { name: 'Tenet Testnet', chainId: 155, symbol: 'TENET' },
  { name: 'OEBlock Testnet', chainId: 156, symbol: 'OEB' },
  { name: 'Armonia Eva Chain Mainnet', chainId: 160, symbol: 'AMAX' },
  { name: 'Armonia Eva Chain Testnet', chainId: 161, symbol: 'AMAX' },
  { name: 'Lightstreams Testnet', chainId: 162, symbol: 'PHT' },
  { name: 'Lightstreams Mainnet', chainId: 163, symbol: 'PHT' },
  { name: 'Omni Testnet', chainId: 165, symbol: 'OMNI' },
  { name: 'Atoshi Testnet', chainId: 167, symbol: 'ATOS' },
  { name: 'AIOZ Network', chainId: 168, symbol: 'AIOZ' },
  { name: 'Manta Pacific Mainnet', chainId: 169, symbol: 'ETH' },
  { name: 'HOO Smart Chain Testnet', chainId: 170, symbol: 'HOO' },
  { name: 'Latam-Blockchain Resil Testnet', chainId: 172, symbol: 'usd' },
  { name: 'AME Chain Mainnet', chainId: 180, symbol: 'AME' },
  { name: 'Seele Mainnet', chainId: 186, symbol: 'Seele' },
  { name: 'BMC Mainnet', chainId: 188, symbol: 'BTM' },
  { name: 'BMC Testnet', chainId: 189, symbol: 'BTM' },
  { name: 'Crypto Emergency', chainId: 193, symbol: 'CEM' },
  { name: 'X1 Testnet', chainId: 195, symbol: 'OKB' },
  { name: 'X1 Mainnet', chainId: 196, symbol: 'OKB' },
  { name: 'Neutrinos TestNet', chainId: 197, symbol: 'NEUTR' },
  { name: 'Bitchain Mainnet', chainId: 198, symbol: 'BTC' },
  { name: 'BitTorrent Chain Mainnet', chainId: 199, symbol: 'BTT' },
  { name: 'Arbitrum on xDai', chainId: 200, symbol: 'xDAI' },
  { name: 'MOAC testnet', chainId: 201, symbol: 'mc' },
  { name: 'opBNB Mainnet', chainId: 204, symbol: 'BNB' },
  { name: 'VinuChain Testnet', chainId: 206, symbol: 'VС' },
  { name: 'VinuChain Network', chainId: 207, symbol: 'VС' },
  { name: 'Structx Mainnet', chainId: 208, symbol: 'utx' },
  { name: 'Bitnet', chainId: 210, symbol: 'BTN' },
  { name: 'Freight Trust Network', chainId: 211, symbol: '0xF' },
  { name: 'MAP Makalu', chainId: 212, symbol: 'MAP' },
  { name: 'Shinarium Mainnet', chainId: 214, symbol: 'SHI' },
  { name: 'SiriusNet V2', chainId: 217, symbol: 'MCD' },
  { name: 'SoterOne Mainnet old', chainId: 218, symbol: 'SOTER' },
  { name: 'Permission', chainId: 222, symbol: 'ASK' },
  { name: 'LACHAIN Mainnet', chainId: 225, symbol: 'LA' },
  { name: 'LACHAIN Testnet', chainId: 226, symbol: 'TLA' },
  { name: 'SwapDEX', chainId: 230, symbol: 'SDX' },
  { name: 'Deamchain Testnet', chainId: 236, symbol: 'DEAM' },
  { name: 'Plinga Mainnet', chainId: 242, symbol: 'PLINGA' },
  { name: 'Energy Web Chain', chainId: 246, symbol: 'EWT' },
  { name: 'Oasys Mainnet', chainId: 248, symbol: 'OAS' },
  { name: 'Fantom Opera', chainId: 250, symbol: 'FTM' },
  { name: 'Kroma', chainId: 255, symbol: 'ETH' },
  { name: 'Huobi ECO Chain Testnet', chainId: 256, symbol: 'htt' },
  { name: 'Setheum', chainId: 258, symbol: 'SETM' },
  { name: 'Neonlink Mainnet', chainId: 259, symbol: 'NEON' },
  { name: 'SUR Blockchain Network', chainId: 262, symbol: 'SRN' },
  { name: 'High Performance Blockchain', chainId: 269, symbol: 'HPB' },
  { name: 'EgonCoin Mainnet', chainId: 271, symbol: 'EGON' },
  { name: 'LaChain', chainId: 274, symbol: 'LAC' },
  { name: 'zkSync Era Testnet', chainId: 280, symbol: 'ETH' },
  { name: 'Boba Network', chainId: 288, symbol: 'ETH' },
  { name: 'Orderly Mainnet', chainId: 291, symbol: 'ETH' },
  { name: 'Hedera Mainnet', chainId: 295, symbol: 'HBAR' },
  { name: 'Hedera Testnet', chainId: 296, symbol: 'HBAR' },
  { name: 'Hedera Previewnet', chainId: 297, symbol: 'HBAR' },
  { name: 'Hedera Localnet', chainId: 298, symbol: 'HBAR' },
  { name: '(deprecated) Optimism on GC', chainId: 300, symbol: 'xDAI' },
  { name: 'Bobaopera', chainId: 301, symbol: 'BOBA' },
  { name: 'Neurochain Testnet', chainId: 303, symbol: 'tNCN' },
  { name: 'Wyzth Testnet', chainId: 309, symbol: 'WYZ' },
  { name: 'Omax Mainnet', chainId: 311, symbol: 'OMAX' },
  { name: 'Neurochain Mainnet', chainId: 313, symbol: 'NCN' },
  { name: 'Filecoin - Mainnet', chainId: 314, symbol: 'FIL' },
  { name: 'KCC Mainnet', chainId: 321, symbol: 'KCS' },
  { name: 'KCC Testnet', chainId: 322, symbol: 'tKCS' },
  { name: 'zkSync Era Mainnet', chainId: 324, symbol: 'ETH' },
  { name: 'Web3Q Mainnet', chainId: 333, symbol: 'W3Q' },
  { name: 'DFK Chain Test', chainId: 335, symbol: 'JEWEL' },
  { name: 'Shiden', chainId: 336, symbol: 'SDN' },
  { name: 'Cronos Testnet', chainId: 338, symbol: 'TCRO' },
  { name: 'Yooldo Verse Mainnet', chainId: 345, symbol: 'OAS' },
  { name: 'Theta Mainnet', chainId: 361, symbol: 'TFUEL' },
  { name: 'Theta Sapphire Testnet', chainId: 363, symbol: 'TFUEL' },
  { name: 'Theta Amber Testnet', chainId: 364, symbol: 'TFUEL' },
  { name: 'Theta Testnet', chainId: 365, symbol: 'TFUEL' },
  { name: 'PulseChain', chainId: 369, symbol: 'PLS' },
  { name: 'Consta Testnet', chainId: 371, symbol: 'tCNT' },
  { name: 'Lisinski', chainId: 385, symbol: 'LISINS' },
  { name: 'Nativ3 Mainnet', chainId: 399, symbol: 'USNT' },
  { name: 'HyperonChain TestNet', chainId: 400, symbol: 'HPN' },
  { name: 'Ozone Chain Testnet', chainId: 401, symbol: 'OZO' },
  { name: 'Pepe Chain Mainnet', chainId: 411, symbol: 'PEPE' },
  { name: 'SX Network Mainnet', chainId: 416, symbol: 'SX' },
  { name: 'LaTestnet', chainId: 418, symbol: 'TLA' },
  { name: 'Optimism Goerli Testnet', chainId: 420, symbol: 'ETH' },
  { name: 'PGN (Public Goods Network)', chainId: 424, symbol: 'ETH' },
  { name: 'Zeeth Chain', chainId: 427, symbol: 'ZTH' },
  { name: 'Obscuro Testnet', chainId: 443, symbol: 'ETH' },
  { name: 'Synapse Chain Testnet', chainId: 444, symbol: 'ETH' },
  { name: 'ARZIO Chain', chainId: 456, symbol: 'AZO' },
  { name: 'Areon Network Testnet', chainId: 462, symbol: 'TAREA' },
  { name: 'Rupaya', chainId: 499, symbol: 'RUPX' },
  { name: 'Camino C-Chain', chainId: 500, symbol: 'CAM' },
  { name: 'Columbus Test Network', chainId: 501, symbol: 'CAM' },
  { name: 'Double-A Chain Mainnet', chainId: 512, symbol: 'AAC' },
  { name: 'Double-A Chain Testnet', chainId: 513, symbol: 'AAC' },
  { name: 'Gear Zero Network Mainnet', chainId: 516, symbol: 'GZN' },
  { name: 'XT Smart Chain Mainnet', chainId: 520, symbol: 'XT' },
  { name: 'Firechain Mainnet', chainId: 529, symbol: 'FIRE' },
  { name: 'F(x)Core Mainnet Network', chainId: 530, symbol: 'FX' },
  { name: 'Candle', chainId: 534, symbol: 'CNDL' },
  { name: 'PAWCHAIN Testnet', chainId: 542, symbol: 'PAW' },
  { name: 'Vela1 Chain Mainnet', chainId: 555, symbol: 'CLASS' },
  { name: 'Tao Network', chainId: 558, symbol: 'TAO' },
  { name: 'Dogechain Testnet', chainId: 568, symbol: 'DOGE' },
  { name: 'Rollux Mainnet', chainId: 570, symbol: 'SYS' },
  { name: 'Metis Stardust Testnet', chainId: 588, symbol: 'METIS' },
  { name: 'Astar', chainId: 592, symbol: 'ASTR' },
  { name: 'Acala Mandala Testnet TC9', chainId: 595, symbol: 'mACA' },
  { name: 'Karura Network Testnet', chainId: 596, symbol: 'KAR' },
  { name: 'Acala Network Testnet', chainId: 597, symbol: 'ACA' },
  { name: 'Metis Goerli Testnet', chainId: 599, symbol: 'METIS' },
  { name: 'Meshnyan testnet', chainId: 600, symbol: 'MESHT' },
  { name: 'PEER Testnet', chainId: 601, symbol: 'PEER' },
  { name: 'Graphlinq Blockchain Mainnet', chainId: 614, symbol: 'GLQ' },
  { name: 'Avocado', chainId: 634, symbol: 'USDC' },
  { name: 'SX Network Testnet', chainId: 647, symbol: 'SX' },
  { name: 'Endurance Smart Chain Mainnet', chainId: 648, symbol: 'ACE' },
  { name: 'Pixie Chain Testnet', chainId: 666, symbol: 'PCTT' },
  { name: 'LAOS Arrakis', chainId: 667, symbol: 'LAOS' },
  { name: 'JuncaChain', chainId: 668, symbol: 'JGC' },
  { name: 'JuncaChain testnet', chainId: 669, symbol: 'JGCT' },
  { name: 'Karura Network', chainId: 686, symbol: 'KAR' },
  { name: 'Star Social Testnet', chainId: 700, symbol: 'SNS' },
  { name: 'BlockChain Station Mainnet', chainId: 707, symbol: 'BCS' },
  { name: 'BlockChain Station Testnet', chainId: 708, symbol: 'tBCS' },
  { name: 'Highbury', chainId: 710, symbol: 'FURY' },
  { name: 'Shibarium Beta', chainId: 719, symbol: 'BONE' },
  { name: 'Lycan Chain', chainId: 721, symbol: 'LYC' },
  { name: 'Canto Testnet', chainId: 740, symbol: 'CANTO' },
  { name: 'Vention Smart Chain Testnet', chainId: 741, symbol: 'VNT' },
  { name: 'Script Testnet', chainId: 742, symbol: 'SPAY' },
  { name: 'QL1', chainId: 766, symbol: 'QOM' },
  { name: 'OpenChain Testnet', chainId: 776, symbol: 'TOPC' },
  { name: 'cheapETH', chainId: 777, symbol: 'cTH' },
  { name: 'MAAL Chain', chainId: 786, symbol: 'MAAL' },
  { name: 'Acala Network', chainId: 787, symbol: 'ACA' },
  { name: 'Aerochain Testnet', chainId: 788, symbol: 'TAero' },
  { name: 'Patex', chainId: 789, symbol: 'ETH' },
  { name: 'Lucid Blockchain', chainId: 800, symbol: 'LUCID' },
  { name: 'Haic', chainId: 803, symbol: 'HAIC' },
  { name: 'Portal Fantasy Chain Test', chainId: 808, symbol: 'PFT' },
  { name: 'Qitmeer', chainId: 813, symbol: 'MEER' },
  { name: 'BeOne Chain Mainnet', chainId: 818, symbol: 'BOC' },
  { name: 'Callisto Mainnet', chainId: 820, symbol: 'CLO' },
  { name: 'Callisto Testnet Deprecated', chainId: 821, symbol: 'TCLO' },
  { name: 'Taraxa Mainnet', chainId: 841, symbol: 'TARA' },
  { name: 'Taraxa Testnet', chainId: 842, symbol: 'TARA' },
  { name: 'Zeeth Chain Dev', chainId: 859, symbol: 'ZTH' },
  { name: 'Fantasia Chain Mainnet', chainId: 868, symbol: 'FST' },
  { name: 'Bandai Namco Research Verse Mainnet', chainId: 876, symbol: 'OAS' },
  { name: 'Dexit Network', chainId: 877, symbol: 'DXT' },
  { name: 'Ambros Chain Mainnet', chainId: 880, symbol: 'AMBROS' },
  { name: 'Wanchain', chainId: 888, symbol: 'WAN' },
  { name: 'Garizon Testnet Stage0', chainId: 900, symbol: 'GAR' },
  { name: 'Garizon Testnet Stage1', chainId: 901, symbol: 'GAR' },
  { name: 'Garizon Testnet Stage2', chainId: 902, symbol: 'GAR' },
  { name: 'Garizon Testnet Stage3', chainId: 903, symbol: 'GAR' },
  { name: 'Portal Fantasy Chain', chainId: 909, symbol: 'PFT' },
  { name: 'DecentraBone Layer1 Testnet', chainId: 910, symbol: 'DBONE' },
  { name: 'Rinia Testnet', chainId: 917, symbol: 'FIRE' },
  { name: 'Mode Testnet', chainId: 919, symbol: 'ETH' },
  { name: 'Yidark Chain Mainnet', chainId: 927, symbol: 'YDK' },
  { name: 'PulseChain Testnet', chainId: 940, symbol: 'tPLS' },
  { name: 'PulseChain Testnet v2b', chainId: 941, symbol: 'tPLS' },
  { name: 'PulseChain Testnet v3', chainId: 942, symbol: 'tPLS' },
  { name: 'PulseChain Testnet v4', chainId: 943, symbol: 'tPLS' },
  { name: 'muNode Testnet', chainId: 956, symbol: 'ETH' },
  { name: 'BTC20 Smart Chain', chainId: 963, symbol: 'BTCC' },
  { name: 'Oort Mainnet', chainId: 970, symbol: 'CCN' },
  { name: 'Oort Huygens', chainId: 971, symbol: 'CCN' },
  { name: 'Oort Ascraeus', chainId: 972, symbol: 'CCNA' },
  { name: 'Nepal Blockchain Network', chainId: 977, symbol: 'YETI' },
  { name: 'TOP Mainnet EVM', chainId: 980, symbol: 'ETH' },
  { name: 'Memo Smart Chain Mainnet', chainId: 985, symbol: 'CMEMO' },
  { name: 'TOP Mainnet', chainId: 989, symbol: 'TOP' },
  { name: 'eLiberty Mainnet', chainId: 990, symbol: '$EL' },
  { name: '5ireChain Thunder', chainId: 997, symbol: '5ire' },
  { name: 'Lucky Network', chainId: 998, symbol: 'L99' },
  { name: 'Wanchain Testnet', chainId: 999, symbol: 'WAN' },
  { name: 'GTON Mainnet', chainId: 1000, symbol: 'GCD' },
  { name: 'Klaytn Testnet Baobab', chainId: 1001, symbol: 'KLAY' },
  { name: 'Tectum Emission Token', chainId: 1003, symbol: 'TET' },
  { name: 'T-EKTA', chainId: 1004, symbol: 'T-EKTA' },
  { name: 'Newton Testnet', chainId: 1007, symbol: 'NEW' },
  { name: 'Eurus Mainnet', chainId: 1008, symbol: 'EUN' },
  { name: 'Evrice Network', chainId: 1010, symbol: 'EVC' },
  { name: 'Newton', chainId: 1012, symbol: 'NEW' },
  { name: 'Sakura', chainId: 1022, symbol: 'SKU' },
  { name: 'Clover Testnet', chainId: 1023, symbol: 'CLV' },
  { name: 'CLV Parachain', chainId: 1024, symbol: 'CLV' },
  { name: 'BitTorrent Chain Testnet', chainId: 1028, symbol: 'BTT' },
  { name: 'Conflux eSpace', chainId: 1030, symbol: 'CFX' },
  { name: 'Proxy Network Testnet', chainId: 1031, symbol: 'PRX' },
  { name: 'Bronos Testnet', chainId: 1038, symbol: 'tBRO' },
  { name: 'Bronos Mainnet', chainId: 1039, symbol: 'BRO' },
  { name: 'ShimmerEVM Testnet Deprecated', chainId: 1071, symbol: 'SMR' },
  { name: 'ShimmerEVM Testnet', chainId: 1072, symbol: 'SMR' },
  { name: 'Mintara Testnet', chainId: 1079, symbol: 'MNTR' },
  { name: 'Mintara Mainnet', chainId: 1080, symbol: 'MNTR' },
  { name: 'Metis Andromeda Mainnet', chainId: 1088, symbol: 'METIS' },
  { name: 'Humans.ai Mainnet', chainId: 1089, symbol: 'HEART' },
  { name: 'MOAC mainnet', chainId: 1099, symbol: 'mc' },
  { name: 'Polygon zkEVM', chainId: 1101, symbol: 'ETH' },
  { name: 'BLXq Testnet', chainId: 1107, symbol: 'BLXQ' },
  { name: 'BLXq Mainnet', chainId: 1108, symbol: 'BLXQ' },
  { name: 'WEMIX3.0 Mainnet', chainId: 1111, symbol: 'WEMIX' },
  { name: 'WEMIX3.0 Testnet', chainId: 1112, symbol: 'tWEMIX' },
  { name: 'Core Blockchain Testnet', chainId: 1115, symbol: 'tCORE' },
  { name: 'Core Blockchain Mainnet', chainId: 1116, symbol: 'CORE' },
  { name: 'Dogcoin Mainnet', chainId: 1117, symbol: 'DOGS' },
  { name: 'DeFiChain EVM Network Mainnet', chainId: 1130, symbol: 'DFI' },
  { name: 'DeFiChain EVM Network Testnet', chainId: 1131, symbol: 'DFI' },
  { name: 'DeFiMetaChain', chainId: 1133, symbol: 'DFI' },
  { name: 'AmStar Testnet', chainId: 1138, symbol: 'SINSO' },
  { name: 'MathChain', chainId: 1139, symbol: 'MATH' },
  { name: 'MathChain Testnet', chainId: 1140, symbol: 'MATH' },
  { name: 'Symplexia Smart Chain', chainId: 1149, symbol: 'PLEX' },
  { name: 'Origin Testnet', chainId: 1170, symbol: 'UOC' },
  { name: 'Smart Host Teknoloji TESTNET', chainId: 1177, symbol: 'tSHT' },
  { name: 'Iora Chain', chainId: 1197, symbol: 'IORA' },
  { name: 'Evanesco Testnet', chainId: 1201, symbol: 'AVIS' },
  { name: 'World Trade Technical Chain Mainnet', chainId: 1202, symbol: 'WTT' },
  { name: 'Popcateum Mainnet', chainId: 1213, symbol: 'POP' },
  { name: 'EnterChain Mainnet', chainId: 1214, symbol: 'ENTER' },
  { name: 'Exzo Network Mainnet', chainId: 1229, symbol: 'XZO' },
  { name: 'Ultron Testnet', chainId: 1230, symbol: 'ULX' },
  { name: 'Ultron Mainnet', chainId: 1231, symbol: 'ULX' },
  { name: 'Step Network', chainId: 1234, symbol: 'FITFI' },
  { name: 'ARC Mainnet', chainId: 1243, symbol: 'ARC' },
  { name: 'ARC Testnet', chainId: 1244, symbol: 'ARC' },
  { name: 'OM Platform Mainnet', chainId: 1246, symbol: 'OM' },
  { name: 'CIC Chain Testnet', chainId: 1252, symbol: 'CICT' },
  { name: 'HALO Mainnet', chainId: 1280, symbol: 'HO' },
  { name: 'Moonbeam', chainId: 1284, symbol: 'GLMR' },
  { name: 'Moonriver', chainId: 1285, symbol: 'MOVR' },
  { name: 'Moonrock old', chainId: 1286, symbol: 'ROC' },
  { name: 'Moonbase Alpha', chainId: 1287, symbol: 'DEV' },
  { name: 'Moonrock', chainId: 1288, symbol: 'ROC' },
  { name: 'Swisstronik Testnet', chainId: 1291, symbol: 'SWTR' },
  { name: 'Bobabeam', chainId: 1294, symbol: 'BOBA' },
  { name: 'Bobabase Testnet', chainId: 1297, symbol: 'BOBA' },
  { name: 'Dos Fuji Subnet', chainId: 1311, symbol: 'DOS' },
  { name: 'Alyx Mainnet', chainId: 1314, symbol: 'ALYX' },
  { name: 'AIA Mainnet', chainId: 1319, symbol: 'AIA' },
  { name: 'AIA Testnet', chainId: 1320, symbol: 'AIA' },
  { name: 'Geth Testnet', chainId: 1337, symbol: 'ETH' },
  { name: 'Elysium Testnet', chainId: 1338, symbol: 'LAVA' },
  { name: 'Elysium Mainnet', chainId: 1339, symbol: 'LAVA' },
  { name: 'Blitz Subnet', chainId: 1343, symbol: 'BGAS' },
  { name: 'CIC Chain Mainnet', chainId: 1353, symbol: 'CIC' },
  { name: 'Zafirium Mainnet', chainId: 1369, symbol: 'ZAFIC' },
  { name: 'Kalar Chain', chainId: 1379, symbol: 'KLC' },
  { name: 'AmStar Mainnet', chainId: 1388, symbol: 'SINSO' },
  { name: 'Joseon Mainnet', chainId: 1392, symbol: 'JSM' },
  { name: 'Polygon zkEVM Testnet old', chainId: 1402, symbol: 'ETH' },
  {
    name: 'Polygon zkEVM Testnet Pre Audit-Upgraded',
    chainId: 1422,
    symbol: 'ETH',
  },
  { name: 'Rikeza Network Mainnet', chainId: 1433, symbol: 'RIK' },
  { name: 'Living Assets Mainnet', chainId: 1440, symbol: 'LAS' },
  { name: 'Polygon zkEVM Testnet', chainId: 1442, symbol: 'ETH' },
  { name: 'GIL Testnet', chainId: 1452, symbol: 'GANG' },
  { name: 'Ctex Scan Blockchain', chainId: 1455, symbol: 'CTEX' },
  { name: 'BEVM', chainId: 1501, symbol: 'BTC' },
  { name: 'Sherpax Mainnet', chainId: 1506, symbol: 'KSX' },
  { name: 'Sherpax Testnet', chainId: 1507, symbol: 'KSX' },
  { name: 'Beagle Messaging Chain', chainId: 1515, symbol: 'BG' },
  { name: 'Tenet', chainId: 1559, symbol: 'TENET' },
  { name: 'Catecoin Chain Mainnet', chainId: 1618, symbol: 'CATE' },
  { name: 'Atheios', chainId: 1620, symbol: 'ATH' },
  { name: 'Btachain', chainId: 1657, symbol: 'BTA' },
  { name: 'Horizen Yuma Testnet Deprecated', chainId: 1662, symbol: 'tZEN' },
  { name: 'Horizen Gobi Testnet', chainId: 1663, symbol: 'tZEN' },
  { name: 'LUDAN Mainnet', chainId: 1688, symbol: 'LUDAN' },
  { name: 'Anytype EVM Chain', chainId: 1701, symbol: 'ANY' },
  { name: 'TBSI Mainnet', chainId: 1707, symbol: 'JINDA' },
  { name: 'TBSI Testnet', chainId: 1708, symbol: 'JINDA' },
  { name: 'Palette Chain Mainnet', chainId: 1718, symbol: 'PLT' },
  { name: 'PartyChain', chainId: 1773, symbol: 'GRAMS' },
  { name: 'Gauss Mainnet', chainId: 1777, symbol: 'GANG' },
  { name: 'Kerleano', chainId: 1804, symbol: 'CRC' },
  { name: 'Rabbit Analog Testnet Chain', chainId: 1807, symbol: 'rAna' },
  { name: 'Cube Chain Mainnet', chainId: 1818, symbol: 'CUBE' },
  { name: 'Cube Chain Testnet', chainId: 1819, symbol: 'CUBET' },
  { name: 'Teslafunds', chainId: 1856, symbol: 'TSF' },
  { name: 'WhiteBIT Network', chainId: 1875, symbol: 'WBT' },
  { name: 'Gitshock Cartenz Testnet', chainId: 1881, symbol: 'tGTFX' },
  { name: 'Lightlink Phoenix Mainnet', chainId: 1890, symbol: 'ETH' },
  { name: 'Lightlink Pegasus Testnet', chainId: 1891, symbol: 'ETH' },
  { name: 'BON Network', chainId: 1898, symbol: 'BOY' },
  { name: 'Sports Chain Network', chainId: 1904, symbol: 'SCN' },
  { name: 'Bitcichain Mainnet', chainId: 1907, symbol: 'BITCI' },
  { name: 'Bitcichain Testnet', chainId: 1908, symbol: 'TBITCI' },
  { name: 'ONUS Chain Testnet', chainId: 1945, symbol: 'ONUS' },
  { name: 'D-Chain Mainnet', chainId: 1951, symbol: 'DOINX' },
  { name: 'Dexilla Testnet', chainId: 1954, symbol: 'DXZ' },
  { name: 'Eleanor', chainId: 1967, symbol: 'MTC' },
  { name: 'Super Smart Chain Testnet', chainId: 1969, symbol: 'TSCS' },
  { name: 'Super Smart Chain Mainnet', chainId: 1970, symbol: 'SCS' },
  { name: 'Atelier', chainId: 1971, symbol: 'ATLR' },
  { name: 'ONUS Chain Mainnet', chainId: 1975, symbol: 'ONUS' },
  { name: 'Eurus Testnet', chainId: 1984, symbol: 'EUN' },
  { name: 'SatoshIE', chainId: 1985, symbol: 'TUSHY' },
  { name: 'SatoshIE Testnet', chainId: 1986, symbol: 'TUSHY' },
  { name: 'EtherGem', chainId: 1987, symbol: 'EGEM' },
  { name: 'Ekta', chainId: 1994, symbol: 'EKTA' },
  { name: 'edeXa Testnet', chainId: 1995, symbol: 'EDX' },
  { name: 'Dogechain Mainnet', chainId: 2000, symbol: 'DOGE' },
  { name: 'Milkomeda C1 Mainnet', chainId: 2001, symbol: 'mADA' },
  { name: 'Milkomeda A1 Mainnet', chainId: 2002, symbol: 'mALGO' },
  { name: 'CloudWalk Testnet', chainId: 2008, symbol: 'CWN' },
  { name: 'CloudWalk Mainnet', chainId: 2009, symbol: 'CWN' },
  { name: 'MainnetZ Mainnet', chainId: 2016, symbol: 'NetZ' },
  { name: 'PublicMint Devnet', chainId: 2018, symbol: 'USD' },
  { name: 'PublicMint Testnet', chainId: 2019, symbol: 'USD' },
  { name: 'PublicMint Mainnet', chainId: 2020, symbol: 'USD' },
  { name: 'Edgeware EdgeEVM Mainnet', chainId: 2021, symbol: 'EDG' },
  { name: 'Beresheet BereEVM Testnet', chainId: 2022, symbol: 'tEDG' },
  { name: 'Taycan Testnet', chainId: 2023, symbol: 'tSFL' },
  { name: 'Rangers Protocol Mainnet', chainId: 2025, symbol: 'RPG' },
  { name: 'Centrifuge', chainId: 2031, symbol: 'CFG' },
  { name: 'Catalyst', chainId: 2032, symbol: 'NCFG' },
  { name: 'Kiwi Subnet', chainId: 2037, symbol: 'SHRAP' },
  { name: 'Shrapnel Testnet', chainId: 2038, symbol: 'SHRAPG' },
  { name: 'OriginTrail Parachain', chainId: 2043, symbol: 'OTP' },
  { name: 'Shrapnel Subnet', chainId: 2044, symbol: 'SHRAPG' },
  { name: 'Stratos Testnet', chainId: 2047, symbol: 'STOS' },
  { name: 'Stratos', chainId: 2048, symbol: 'STOS' },
  { name: 'Movo Smart Chain Mainnet', chainId: 2049, symbol: 'MOVO' },
  { name: 'Quokkacoin Mainnet', chainId: 2077, symbol: 'QKA' },
  { name: 'Altair', chainId: 2088, symbol: 'AIR' },
  { name: 'Algol', chainId: 2089, symbol: 'ALGL' },
  { name: 'Ecoball Mainnet', chainId: 2100, symbol: 'ECO' },
  { name: 'Ecoball Testnet Espuma', chainId: 2101, symbol: 'ECO' },
  { name: 'Exosama Network', chainId: 2109, symbol: 'SAMA' },
  { name: 'Metaplayerone Mainnet', chainId: 2122, symbol: 'METAD' },
  { name: 'Metaplayerone Dubai Testnet', chainId: 2124, symbol: 'MEU' },
  { name: 'BigShortBets', chainId: 2137, symbol: 'USDC' },
  { name: 'Defi Oracle Meta Testnet', chainId: 2138, symbol: 'tETH' },
  { name: 'BOSagora Mainnet', chainId: 2151, symbol: 'BOA' },
  { name: 'Findora Mainnet', chainId: 2152, symbol: 'FRA' },
  { name: 'Findora Testnet', chainId: 2153, symbol: 'FRA' },
  { name: 'Findora Forge', chainId: 2154, symbol: 'FRA' },
  { name: 'Moonsama Network', chainId: 2199, symbol: 'SAMA' },
  { name: 'Antofy Mainnet', chainId: 2202, symbol: 'ABN' },
  { name: 'Bitcoin EVM', chainId: 2203, symbol: 'BTC' },
  { name: 'Evanesco Mainnet', chainId: 2213, symbol: 'EVA' },
  { name: 'Kava Testnet', chainId: 2221, symbol: 'TKAVA' },
  { name: 'Kava', chainId: 2222, symbol: 'KAVA' },
  { name: 'VChain Mainnet', chainId: 2223, symbol: 'VNDT' },
  { name: 'Krest Network', chainId: 2241, symbol: 'KRST' },
  { name: 'BOMB Chain', chainId: 2300, symbol: 'BOMB' },
  { name: 'Arevia', chainId: 2309, symbol: 'ARÉV' },
  { name: 'SOMA Network Testnet', chainId: 2323, symbol: 'tSMA' },
  { name: 'Altcoinchain', chainId: 2330, symbol: 'ALT' },
  { name: 'SOMA Network Mainnet', chainId: 2332, symbol: 'SMA' },
  { name: '(deprecated) Kroma Sepolia', chainId: 2357, symbol: 'ETH' },
  { name: 'Kroma Sepolia', chainId: 2358, symbol: 'ETH' },
  { name: 'BOMB Chain Testnet', chainId: 2399, symbol: 'tBOMB' },
  { name: 'TCG Verse Mainnet', chainId: 2400, symbol: 'OAS' },
  { name: 'XODEX', chainId: 2415, symbol: 'XODEX' },
  { name: 'Unicorn Ultra Nebulas Testnet', chainId: 2484, symbol: 'U2U' },
  { name: 'Kortho Mainnet', chainId: 2559, symbol: 'KTO' },
  { name: 'TechPay Mainnet', chainId: 2569, symbol: 'TPC' },
  { name: 'PoCRNet', chainId: 2606, symbol: 'CRC' },
  { name: 'Redlight Chain Mainnet', chainId: 2611, symbol: 'REDLC' },
  { name: 'EZChain C-Chain Mainnet', chainId: 2612, symbol: 'EZC' },
  { name: 'EZChain C-Chain Testnet', chainId: 2613, symbol: 'EZC' },
  { name: 'WhiteBIT Network Testnet', chainId: 2625, symbol: 'WBT' },
  { name: 'Morphism Testnet', chainId: 2710, symbol: 'ETH' },
  { name: 'Boba Network Goerli Testnet', chainId: 2888, symbol: 'ETH' },
  { name: 'BitYuan Mainnet', chainId: 2999, symbol: 'BTY' },
  { name: 'CENNZnet Rata', chainId: 3000, symbol: 'CPAY' },
  { name: 'CENNZnet Nikau', chainId: 3001, symbol: 'CPAY' },
  { name: 'Canxium Mainnet', chainId: 3003, symbol: 'CAU' },
  { name: 'PLAYA3ULL GAMES', chainId: 3011, symbol: '3ULL' },
  { name: 'Orlando Chain', chainId: 3031, symbol: 'ORL' },
  { name: 'Bifrost Mainnet', chainId: 3068, symbol: 'BFC' },
  { name: 'Immu3 EVM', chainId: 3100, symbol: 'IMMU' },
  { name: 'Vulture EVM Beta', chainId: 3102, symbol: 'VFI' },
  { name: 'Filecoin - Hyperspace testnet', chainId: 3141, symbol: 'tFIL' },
  { name: 'Dubxcoin network', chainId: 3269, symbol: 'DUBX' },
  { name: 'Dubxcoin testnet', chainId: 3270, symbol: 'TDUBX' },
  { name: 'Debounce Subnet Testnet', chainId: 3306, symbol: 'DB' },
  { name: 'ZCore Testnet', chainId: 3331, symbol: 'ZCR' },
  { name: 'Web3Q Testnet', chainId: 3333, symbol: 'W3Q' },
  { name: 'Web3Q Galileo', chainId: 3334, symbol: 'W3Q' },
  { name: 'Paribu Net Mainnet', chainId: 3400, symbol: 'PRB' },
  { name: 'SecureChain Testnet', chainId: 3434, symbol: 'SCAI' },
  { name: 'Paribu Net Testnet', chainId: 3500, symbol: 'PRB' },
  { name: 'JFIN Chain', chainId: 3501, symbol: 'jfin' },
  { name: 'PandoProject Mainnet', chainId: 3601, symbol: 'PTX' },
  { name: 'PandoProject Testnet', chainId: 3602, symbol: 'PTX' },
  { name: 'Botanix Testnet', chainId: 3636, symbol: 'BTC' },
  { name: 'Botanix Mainnet', chainId: 3637, symbol: 'BTC' },
  { name: 'iChain Network', chainId: 3639, symbol: 'ISLAMI' },
  { name: 'Jouleverse Mainnet', chainId: 3666, symbol: 'J' },
  { name: 'Bittex Mainnet', chainId: 3690, symbol: 'BTX' },
  { name: 'Empire Network', chainId: 3693, symbol: 'EMPIRE' },
  { name: 'SenjePowers Testnet', chainId: 3698, symbol: 'SPC' },
  { name: 'SenjePowers Mainnet', chainId: 3699, symbol: 'SPC' },
  { name: 'Xpla Testnet', chainId: 3701, symbol: 'XPLA' },
  { name: 'Crossbell', chainId: 3737, symbol: 'CSB' },
  { name: 'AlveyChain Mainnet', chainId: 3797, symbol: 'ALV' },
  { name: 'KalyChain Mainnet', chainId: 3888, symbol: 'KLC' },
  { name: 'KalyChain Testnet', chainId: 3889, symbol: 'KLC' },
  { name: 'DRAC Network', chainId: 3912, symbol: 'DRAC' },
  { name: 'DOS Tesnet', chainId: 3939, symbol: 'DOS' },
  { name: 'DYNO Mainnet', chainId: 3966, symbol: 'DYNO' },
  { name: 'DYNO Testnet', chainId: 3967, symbol: 'tDYNO' },
  { name: 'YuanChain Mainnet', chainId: 3999, symbol: 'YCC' },
  { name: 'Ozone Chain Mainnet', chainId: 4000, symbol: 'OZO' },
  { name: 'Peperium Chain Testnet', chainId: 4001, symbol: 'PERIUM' },
  { name: 'Fantom Testnet', chainId: 4002, symbol: 'FTM' },
  { name: 'Bobaopera Testnet', chainId: 4051, symbol: 'BOBA' },
  { name: 'Nahmii 3 Mainnet', chainId: 4061, symbol: 'ETH' },
  { name: 'Nahmii 3 Testnet', chainId: 4062, symbol: 'ETH' },
  {
    name: 'Fastex Chain (Bahamut) Oasis Testnet',
    chainId: 4090,
    symbol: 'FTN',
  },
  { name: 'Bitindi Testnet', chainId: 4096, symbol: '$BNI' },
  { name: 'Bitindi Mainnet', chainId: 4099, symbol: '$BNI' },
  { name: 'AIOZ Network Testnet', chainId: 4102, symbol: 'AIOZ' },
  { name: 'Humans.ai Testnet', chainId: 4139, symbol: 'HEART' },
  { name: 'Tipboxcoin Testnet', chainId: 4141, symbol: 'TPBX' },
  { name: 'PHI Network V1', chainId: 4181, symbol: 'Φ' },
  { name: 'LUKSO Testnet', chainId: 4201, symbol: 'LYXt' },
  { name: 'Nexi Mainnet', chainId: 4242, symbol: 'NEXI' },
  { name: 'Bobafuji Testnet', chainId: 4328, symbol: 'BOBA' },
  { name: 'Beam', chainId: 4337, symbol: 'BEAM' },
  { name: 'Credit Smart Chain Mainnet', chainId: 4400, symbol: 'CREDIT' },
  { name: 'Htmlcoin Mainnet', chainId: 4444, symbol: 'HTML' },
  { name: 'Orderly Sepolia Testnet', chainId: 4460, symbol: 'ETH' },
  { name: 'IoTeX Network Mainnet', chainId: 4689, symbol: 'IOTX' },
  { name: 'IoTeX Network Testnet', chainId: 4690, symbol: 'IOTX' },
  { name: 'MEVerse Chain Testnet', chainId: 4759, symbol: 'MEV' },
  { name: 'BlackFort Exchange Network Testnet', chainId: 4777, symbol: 'TBXN' },
  { name: 'Venidium Testnet', chainId: 4918, symbol: 'XVM' },
  { name: 'Venidium Mainnet', chainId: 4919, symbol: 'XVM' },
  { name: 'BlackFort Exchange Network', chainId: 4999, symbol: 'BXN' },
  { name: 'Mantle', chainId: 5000, symbol: 'MNT' },
  { name: 'Mantle Testnet', chainId: 5001, symbol: 'MNT' },
  { name: 'Treasurenet Mainnet Alpha', chainId: 5002, symbol: 'UNIT' },
  { name: 'Mantle Sepolia Testnet', chainId: 5003, symbol: 'MNT' },
  { name: 'Treasurenet Testnet', chainId: 5005, symbol: 'UNIT' },
  { name: 'Bahamut', chainId: 5165, symbol: 'FTN' },
  { name: 'TLChain Network Mainnet', chainId: 5177, symbol: 'TLC' },
  { name: 'EraSwap Mainnet', chainId: 5197, symbol: 'ES' },
  { name: 'Humanode Mainnet', chainId: 5234, symbol: 'eHMND' },
  { name: 'Firechain Mainnet Old', chainId: 5290, symbol: 'FIRE' },
  { name: 'Uzmi Network Mainnet', chainId: 5315, symbol: 'UZMI' },
  { name: 'Tritanium Testnet', chainId: 5353, symbol: 'tTRN' },
  { name: 'VEX EVM TESTNET', chainId: 5522, symbol: 'VEX' },
  { name: 'Nahmii Mainnet', chainId: 5551, symbol: 'ETH' },
  { name: 'Nahmii Testnet', chainId: 5553, symbol: 'ETH' },
  { name: 'Chain Verse Mainnet', chainId: 5555, symbol: 'OAS' },
  { name: 'opBNB Testnet', chainId: 5611, symbol: 'tBNB' },
  { name: 'Arcturus Chain Testnet', chainId: 5616, symbol: 'tARCT' },
  { name: 'Tanssi EVM ContainerChain', chainId: 5678, symbol: 'Unit' },
  { name: 'Syscoin Tanenbaum Testnet', chainId: 5700, symbol: 'tSYS' },
  { name: 'Hika Network Testnet', chainId: 5729, symbol: 'HIK' },
  { name: 'SatoshiChain Testnet', chainId: 5758, symbol: 'SATS' },
  { name: 'Ganache', chainId: 5777, symbol: 'ETH' },
  { name: 'Ontology Testnet', chainId: 5851, symbol: 'ONG' },
  { name: 'Wegochain Rubidium Mainnet', chainId: 5869, symbol: 'RBD' },
  { name: 'Tres Testnet', chainId: 6065, symbol: 'TRES' },
  { name: 'Tres Mainnet', chainId: 6066, symbol: 'TRES' },
  { name: 'Cascadia Testnet', chainId: 6102, symbol: 'tCC' },
  { name: 'UPTN Testnet', chainId: 6118, symbol: 'UPTN' },
  { name: 'UPTN', chainId: 6119, symbol: 'UPTN' },
  { name: 'Peerpay', chainId: 6502, symbol: 'P2P' },
  { name: 'Scolcoin WeiChain Testnet', chainId: 6552, symbol: 'SCOL' },
  { name: 'Fox Testnet Network', chainId: 6565, symbol: 'tFOX' },
  { name: 'Pixie Chain Mainnet', chainId: 6626, symbol: 'PIX' },
  { name: 'IRIShub', chainId: 6688, symbol: 'ERIS' },
  { name: 'Gold Smart Chain Mainnet', chainId: 6789, symbol: 'STAND' },
  { name: 'Tomb Chain Mainnet', chainId: 6969, symbol: 'TOMB' },
  { name: 'PolySmartChain', chainId: 6999, symbol: 'PSC' },
  { name: 'ZetaChain Mainnet', chainId: 7000, symbol: 'ZETA' },
  { name: 'ZetaChain Athens 3 Testnet', chainId: 7001, symbol: 'ZETA' },
  { name: 'Ella the heart', chainId: 7027, symbol: 'ELLA' },
  { name: 'Planq Mainnet', chainId: 7070, symbol: 'PLQ' },
  { name: 'Bitrock Mainnet', chainId: 7171, symbol: 'BROCK' },
  { name: 'KLYNTAR', chainId: 7331, symbol: 'KLY' },
  { name: 'Horizen EON Mainnet', chainId: 7332, symbol: 'ZEN' },
  { name: 'Shyft Mainnet', chainId: 7341, symbol: 'SHYFT' },
  { name: 'Raba Network Mainnet', chainId: 7484, symbol: 'RABA' },
  { name: 'MEVerse Chain Mainnet', chainId: 7518, symbol: 'MEV' },
  { name: 'ADIL Testnet', chainId: 7575, symbol: 'ADIL' },
  { name: 'Adil Chain V2 Mainnet', chainId: 7576, symbol: 'ADIL' },
  { name: 'The Root Network - Mainnet', chainId: 7668, symbol: 'XRP' },
  { name: 'The Root Network - Porcini Testnet', chainId: 7672, symbol: 'XRP' },
  { name: 'Canto', chainId: 7700, symbol: 'CANTO' },
  { name: 'Canto Tesnet', chainId: 7701, symbol: 'CANTO' },
  { name: 'Bitrock Testnet', chainId: 7771, symbol: 'BROCK' },
  { name: 'Rise of the Warbots Testnet', chainId: 7777, symbol: 'NMAC' },
  { name: 'Hazlor Testnet', chainId: 7878, symbol: 'TSCAS' },
  { name: 'ARDENIUM Athena', chainId: 7895, symbol: 'tARD' },
  { name: 'DOS Chain', chainId: 7979, symbol: 'DOS' },
  { name: 'Teleport', chainId: 8000, symbol: 'TELE' },
  { name: 'Teleport Testnet', chainId: 8001, symbol: 'TELE' },
  { name: 'MDGL Testnet', chainId: 8029, symbol: 'MDGLT' },
  { name: 'Shardeum Liberty 1.X', chainId: 8080, symbol: 'SHM' },
  { name: 'Shardeum Liberty 2.X', chainId: 8081, symbol: 'SHM' },
  { name: 'Shardeum Sphinx 1.X', chainId: 8082, symbol: 'SHM' },
  { name: 'BitEth', chainId: 8086, symbol: 'BTE' },
  { name: 'StreamuX Blockchain', chainId: 8098, symbol: 'SmuX' },
  { name: 'Qitmeer Network Testnet', chainId: 8131, symbol: 'MEER-T' },
  { name: 'Qitmeer Network Mixnet', chainId: 8132, symbol: 'MEER-M' },
  { name: 'Qitmeer Network Privnet', chainId: 8133, symbol: 'MEER-P' },
  { name: 'Amana', chainId: 8134, symbol: 'MEER' },
  { name: 'Flana', chainId: 8135, symbol: 'MEER' },
  { name: 'Mizana', chainId: 8136, symbol: 'MEER' },
  { name: 'Testnet BeOne Chain', chainId: 8181, symbol: 'tBOC' },
  { name: 'Torus Testnet', chainId: 8194, symbol: 'TTQF' },
  { name: 'Klaytn Mainnet Cypress', chainId: 8217, symbol: 'KLAY' },
  { name: 'Blockton Blockchain', chainId: 8272, symbol: 'BTON' },
  { name: 'KorthoTest', chainId: 8285, symbol: 'KTO' },
  { name: 'Dracones Financial Services', chainId: 8387, symbol: 'FUCK' },
  { name: 'Base', chainId: 8453, symbol: 'ETH' },
  { name: 'Toki Network', chainId: 8654, symbol: 'TOKI' },
  { name: 'Toki Testnet', chainId: 8655, symbol: 'TOKI' },
  { name: 'Hela Official Runtime Mainnet', chainId: 8668, symbol: 'HLUSD' },
  { name: 'TOOL Global Mainnet', chainId: 8723, symbol: 'OLO' },
  { name: 'TOOL Global Testnet', chainId: 8724, symbol: 'OLO' },
  { name: 'Alph Network', chainId: 8738, symbol: 'ALPH' },
  { name: 'TMY Chain', chainId: 8768, symbol: 'TMY' },
  { name: 'MARO Blockchain Mainnet', chainId: 8848, symbol: 'MARO' },
  { name: 'Unique', chainId: 8880, symbol: 'UNQ' },
  { name: 'Quartz by Unique', chainId: 8881, symbol: 'QTZ' },
  { name: 'Opal testnet by Unique', chainId: 8882, symbol: 'UNQ' },
  { name: 'Sapphire by Unique', chainId: 8883, symbol: 'QTZ' },
  { name: 'XANAChain', chainId: 8888, symbol: 'XETA' },
  { name: 'Vyvo Smart Chain', chainId: 8889, symbol: 'VSC' },
  { name: 'Mammoth Mainnet', chainId: 8898, symbol: 'MMT' },
  { name: 'JIBCHAIN L1', chainId: 8899, symbol: 'JBC' },
  { name: 'Giant Mammoth Mainnet', chainId: 8989, symbol: 'GMMT' },
  { name: 'bloxberg', chainId: 8995, symbol: 'U+25B3' },
  { name: 'Evmos Testnet', chainId: 9000, symbol: 'tEVMOS' },
  { name: 'Evmos', chainId: 9001, symbol: 'EVMOS' },
  { name: 'BerylBit Mainnet', chainId: 9012, symbol: 'BRB' },
  { name: 'Genesis Coin', chainId: 9100, symbol: 'GNC' },
  { name: 'Rinia Testnet Old', chainId: 9170, symbol: 'FIRE' },
  { name: 'Codefin Mainnet', chainId: 9223, symbol: 'COF' },
  { name: 'Dogcoin Testnet', chainId: 9339, symbol: 'DOGS' },
  { name: 'Rangers Protocol Testnet Robin', chainId: 9527, symbol: 'tRPG' },
  { name: 'QEasyWeb3 Testnet', chainId: 9528, symbol: 'QET' },
  { name: 'Neonlink Testnet', chainId: 9559, symbol: 'tNEON' },
  { name: 'Oort MainnetDev', chainId: 9700, symbol: 'CCN' },
  { name: 'Boba BNB Testnet', chainId: 9728, symbol: 'BOBA' },
  { name: 'MainnetZ Testnet', chainId: 9768, symbol: 'NetZ' },
  { name: 'PepeNetwork Mainnet', chainId: 9779, symbol: 'WPEPE' },
  { name: 'Carbon EVM', chainId: 9790, symbol: 'SWTH' },
  { name: 'Carbon EVM Testnet', chainId: 9792, symbol: 'SWTH' },
  { name: 'IMPERIUM TESTNET', chainId: 9818, symbol: 'tIMP' },
  { name: 'IMPERIUM MAINNET', chainId: 9819, symbol: 'IMP' },
  { name: 'Mind Smart Chain Testnet', chainId: 9977, symbol: 'tMIND' },
  { name: 'Agung Network', chainId: 9990, symbol: 'AGNG' },
  { name: 'Mind Smart Chain Mainnet', chainId: 9996, symbol: 'MIND' },
  { name: 'AltLayer Testnet', chainId: 9997, symbol: 'ETH' },
  { name: 'myOwn Testnet', chainId: 9999, symbol: 'MYN' },
  { name: 'Smart Bitcoin Cash', chainId: 10000, symbol: 'BCH' },
  { name: 'Smart Bitcoin Cash Testnet', chainId: 10001, symbol: 'BCHT' },
  { name: 'Gon Chain', chainId: 10024, symbol: 'GT' },
  { name: 'Japan Open Chain Testnet', chainId: 10081, symbol: 'JOCT' },
  { name: 'SJATSH', chainId: 10086, symbol: 'ETH' },
  { name: 'Blockchain Genesis Mainnet', chainId: 10101, symbol: 'GEN' },
  { name: 'Gnosis Chiado Testnet', chainId: 10200, symbol: 'XDAI' },
  { name: 'MaxxChain Mainnet', chainId: 10201, symbol: 'PWR' },
  { name: 'Arthera Testnet', chainId: 10243, symbol: 'AA' },
  { name: '0XTade', chainId: 10248, symbol: '0XT' },
  { name: 'Worldland Testnet', chainId: 10395, symbol: 'WL' },
  { name: 'Numbers Mainnet', chainId: 10507, symbol: 'NUM' },
  { name: 'Numbers Testnet', chainId: 10508, symbol: 'NUM' },
  { name: 'CryptoCoinPay', chainId: 10823, symbol: 'CCP' },
  { name: 'Quadrans Blockchain', chainId: 10946, symbol: 'QDC' },
  { name: 'Quadrans Blockchain Testnet', chainId: 10947, symbol: 'tQDC' },
  { name: 'Astra', chainId: 11110, symbol: 'ASA' },
  { name: 'WAGMI', chainId: 11111, symbol: 'WGM' },
  { name: 'Astra Testnet', chainId: 11115, symbol: 'tASA' },
  { name: 'HashBit Mainnet', chainId: 11119, symbol: 'HBIT' },
  { name: 'Haqq Network', chainId: 11235, symbol: 'ISLM' },
  { name: 'Shyft Testnet', chainId: 11437, symbol: 'SHYFTT' },
  { name: 'Sardis Testnet', chainId: 11612, symbol: 'SRDX' },
  { name: 'SanR Chain', chainId: 11888, symbol: 'nSAN' },
  { name: 'Polygon Supernet Arianee', chainId: 11891, symbol: 'ARIA20' },
  { name: 'SatoshiChain Mainnet', chainId: 12009, symbol: 'SATS' },
  { name: 'Singularity ZERO Testnet', chainId: 12051, symbol: 'tZERO' },
  { name: 'Singularity ZERO Mainnet', chainId: 12052, symbol: 'ZERO' },
  { name: 'BRC Chain Mainnet', chainId: 12123, symbol: 'BRC' },
  { name: 'Fibonacci Mainnet', chainId: 12306, symbol: 'FIBO' },
  { name: 'BLG Testnet', chainId: 12321, symbol: 'BLG' },
  { name: 'Step Testnet', chainId: 12345, symbol: 'FITFI' },
  { name: 'Astar zkEVM', chainId: 12611, symbol: 'ETH' },
  { name: 'Rikeza Network Testnet', chainId: 12715, symbol: 'RIK' },
  { name: 'Quantum Chain Testnet', chainId: 12890, symbol: 'tQNET' },
  { name: 'SPS', chainId: 13000, symbol: 'ECG' },
  { name: 'Credit Smart Chain', chainId: 13308, symbol: 'CREDIT' },
  { name: 'Beam Testnet', chainId: 13337, symbol: 'BEAM' },
  { name: 'Phoenix Mainnet', chainId: 13381, symbol: 'PHX' },
  { name: 'Susono', chainId: 13812, symbol: 'OPN' },
  { name: 'SPS Testnet', chainId: 14000, symbol: 'ECG' },
  { name: 'Humanode Testnet 5 Israfel', chainId: 14853, symbol: 'eHMND' },
  { name: 'LoopNetwork Mainnet', chainId: 15551, symbol: 'LOOP' },
  { name: 'Trust EVM Testnet', chainId: 15555, symbol: 'EVM' },
  { name: 'EOS EVM Network Testnet', chainId: 15557, symbol: 'EOS' },
  { name: 'MetaDot Mainnet', chainId: 16000, symbol: 'MTT' },
  { name: 'MetaDot Testnet', chainId: 16001, symbol: 'MTTest' },
  { name: 'Genesys Mainnet', chainId: 16507, symbol: 'GSYS' },
  { name: 'IRIShub Testnet', chainId: 16688, symbol: 'ERIS' },
  { name: 'AirDAO Mainnet', chainId: 16718, symbol: 'AMB' },
  { name: 'IVAR Chain Testnet', chainId: 16888, symbol: 'tIVAR' },
  { name: 'Holesky', chainId: 17000, symbol: 'ETH' },
  { name: 'G8Chain Mainnet', chainId: 17171, symbol: 'G8C' },
  { name: 'Palette Chain Testnet', chainId: 17180, symbol: 'PLT' },
  { name: 'EOS EVM Network', chainId: 17777, symbol: 'EOS' },
  { name: 'Frontier of Dreams Testnet', chainId: 18000, symbol: 'ZKST' },
  { name: 'Smart Trade Networks', chainId: 18122, symbol: 'STN' },
  { name: 'Proof Of Memes', chainId: 18159, symbol: 'POM' },
  { name: 'G8Chain Testnet', chainId: 18181, symbol: 'G8C' },
  { name: 'MXC zkEVM Mainnet', chainId: 18686, symbol: 'MXC' },
  { name: 'HOME Verse Mainnet', chainId: 19011, symbol: 'OAS' },
  { name: 'BTCIX Network', chainId: 19845, symbol: 'BTCIX' },
  { name: 'Camelark Mainnet', chainId: 20001, symbol: 'ETHW' },
  { name: 'Callisto Testnet', chainId: 20729, symbol: 'CLO' },
  { name: 'P12 Chain', chainId: 20736, symbol: 'hP2' },
  { name: 'CENNZnet Azalea', chainId: 21337, symbol: 'CPAY' },
  { name: 'omChain Mainnet', chainId: 21816, symbol: 'OMC' },
  { name: 'Taycan', chainId: 22023, symbol: 'SFL' },
  { name: 'AirDAO Testnet', chainId: 22040, symbol: 'AMB' },
  { name: 'Nautilus Mainnet', chainId: 22222, symbol: 'ZBC' },
  { name: 'MAP Mainnet', chainId: 22776, symbol: 'MAPO' },
  { name: 'Antofy Testnet', chainId: 23006, symbol: 'ABN' },
  { name: 'Opside Testnet', chainId: 23118, symbol: 'IDE' },
  { name: 'Oasis Sapphire', chainId: 23294, symbol: 'ROSE' },
  { name: 'Oasis Sapphire Testnet', chainId: 23295, symbol: 'TEST' },
  { name: 'Webchain', chainId: 24484, symbol: 'WEB' },
  { name: 'MintMe.com Coin', chainId: 24734, symbol: 'MINTME' },
  { name: 'Hammer Chain Mainnet', chainId: 25888, symbol: 'GOLDT' },
  { name: 'Bitkub Chain Testnet', chainId: 25925, symbol: 'tKUB' },
  { name: 'Ferrum Testnet', chainId: 26026, symbol: 'tFRM' },
  { name: 'Hertz Network Mainnet', chainId: 26600, symbol: 'HTZ' },
  { name: 'OasisChain Mainnet', chainId: 26863, symbol: 'OAC' },
  {
    name: 'Optimism Bedrock (Goerli Alpha Testnet)',
    chainId: 28528,
    symbol: 'ETH',
  },
  { name: 'MCH Verse Mainnet', chainId: 29548, symbol: 'OAS' },
  { name: 'Piece testnet', chainId: 30067, symbol: 'ECE' },
  { name: 'Cerium Testnet', chainId: 30103, symbol: 'CAU' },
  { name: 'Ethersocial Network', chainId: 31102, symbol: 'ESN' },
  { name: 'CloudTx Mainnet', chainId: 31223, symbol: 'CLD' },
  { name: 'CloudTx Testnet', chainId: 31224, symbol: 'CLD' },
  { name: 'GoChain Testnet', chainId: 31337, symbol: 'GO' },
  { name: 'Filecoin - Wallaby testnet', chainId: 31415, symbol: 'tFIL' },
  { name: 'Bitgert Mainnet', chainId: 32520, symbol: 'Brise' },
  { name: 'Fusion Mainnet', chainId: 32659, symbol: 'FSN' },
  { name: 'Zilliqa EVM', chainId: 32769, symbol: 'ZIL' },
  { name: 'Zilliqa EVM Isolated Server', chainId: 32990, symbol: 'ZIL' },
  { name: 'Zilliqa EVM Testnet', chainId: 33101, symbol: 'ZIL' },
  { name: 'Cloudverse Subnet', chainId: 33210, symbol: 'XCLOUD' },
  { name: 'Aves Mainnet', chainId: 33333, symbol: 'AVS' },
  { name: 'Zilliqa EVM Devnet', chainId: 33385, symbol: 'ZIL' },
  { name: 'Zilliqa 2 EVM Devnet', chainId: 33469, symbol: 'ZIL' },
  { name: 'J2O Taro', chainId: 35011, symbol: 'taro' },
  { name: 'Q Mainnet', chainId: 35441, symbol: 'Q' },
  { name: 'Q Testnet', chainId: 35443, symbol: 'Q' },
  { name: 'ConnectorManager', chainId: 38400, symbol: 'cmRPG' },
  { name: 'ConnectorManager Robin', chainId: 38401, symbol: 'ttRPG' },
  { name: 'Energi Mainnet', chainId: 39797, symbol: 'NRG' },
  { name: 'OHO Mainnet', chainId: 39815, symbol: 'OHO' },
  { name: 'Opulent-X BETA', chainId: 41500, symbol: 'OXYN' },
  { name: 'pegglecoin', chainId: 42069, symbol: 'peggle' },
  { name: 'Arbitrum One', chainId: 42161, symbol: 'ETH' },
  { name: 'Arbitrum Nova', chainId: 42170, symbol: 'ETH' },
  { name: 'Celo Mainnet', chainId: 42220, symbol: 'CELO' },
  { name: 'Oasis Emerald Testnet', chainId: 42261, symbol: 'ROSE' },
  { name: 'Oasis Emerald', chainId: 42262, symbol: 'ROSE' },
  { name: 'Gesoten Verse Testnet', chainId: 42801, symbol: 'OAS' },
  { name: 'Kinto Testnet', chainId: 42888, symbol: 'ETH' },
  { name: 'Athereum', chainId: 43110, symbol: 'ATH' },
  { name: 'Avalanche Fuji Testnet', chainId: 43113, symbol: 'AVAX' },
  { name: 'Avalanche C-Chain', chainId: 43114, symbol: 'AVAX' },
  { name: 'Boba Avax', chainId: 43288, symbol: 'BOBA' },
  { name: 'Frenchain', chainId: 44444, symbol: 'FREN' },
  { name: 'Celo Alfajores Testnet', chainId: 44787, symbol: 'CELO' },
  { name: 'Autobahn Network', chainId: 45000, symbol: 'TXL' },
  { name: 'Fusion Testnet', chainId: 46688, symbol: 'T-FSN' },
  { name: 'REI Network', chainId: 47805, symbol: 'REI' },
  { name: 'Wireshape Floripa Testnet', chainId: 49049, symbol: 'WIRE' },
  { name: 'Bifrost Testnet', chainId: 49088, symbol: 'BFC' },
  { name: 'Energi Testnet', chainId: 49797, symbol: 'NRG' },
  { name: 'Liveplex OracleEVM', chainId: 50001, symbol: 'ETH' },
  { name: 'GTON Testnet', chainId: 50021, symbol: 'GCD' },
  { name: 'Lumoz Testnet Alpha', chainId: 51178, symbol: 'MOZ' },
  { name: 'Sardis Mainnet', chainId: 51712, symbol: 'SRDX' },
  { name: 'Electroneum Mainnet', chainId: 52014, symbol: 'ETN' },
  { name: 'DFK Chain', chainId: 53935, symbol: 'JEWEL' },
  { name: 'Haqq Chain Testnet', chainId: 54211, symbol: 'ISLMT' },
  { name: 'Toronet Testnet', chainId: 54321, symbol: 'TORO' },
  { name: 'Titan', chainId: 55004, symbol: 'ETH' },
  { name: 'REI Chain Mainnet', chainId: 55555, symbol: 'REI' },
  { name: 'REI Chain Testnet', chainId: 55556, symbol: 'tREI' },
  { name: 'Boba BNB Mainnet', chainId: 56288, symbol: 'BOBA' },
  { name: 'VELO Labs Mainnet', chainId: 56789, symbol: 'NOVA' },
  { name: 'Rollux Testnet', chainId: 57000, symbol: 'TSYS' },
  { name: 'Sepolia PGN (Public Goods Network)', chainId: 58008, symbol: 'ETH' },
  { name: 'Linea Testnet', chainId: 59140, symbol: 'ETH' },
  { name: 'Linea', chainId: 59144, symbol: 'ETH' },
  { name: 'Thinkium Testnet Chain 0', chainId: 60000, symbol: 'TKM' },
  { name: 'Thinkium Testnet Chain 1', chainId: 60001, symbol: 'TKM' },
  { name: 'Thinkium Testnet Chain 2', chainId: 60002, symbol: 'TKM' },
  { name: 'Thinkium Testnet Chain 103', chainId: 60103, symbol: 'TKM' },
  { name: 'AxelChain Dev-Net', chainId: 61800, symbol: 'AIUM' },
  { name: 'Etica Mainnet', chainId: 61803, symbol: 'EGAZ' },
  { name: 'DoKEN Super Chain Mainnet', chainId: 61916, symbol: 'DKN' },
  { name: 'Celo Baklava Testnet', chainId: 62320, symbol: 'CELO' },
  { name: 'MultiVAC Mainnet', chainId: 62621, symbol: 'MTV' },
  { name: 'eCredits Mainnet', chainId: 63000, symbol: 'ECS' },
  { name: 'eCredits Testnet', chainId: 63001, symbol: 'ECS' },
  { name: 'Scolcoin Mainnet', chainId: 65450, symbol: 'SCOL' },
  { name: 'Janus Testnet', chainId: 66988, symbol: 'JNS' },
  { name: 'SiriusNet', chainId: 67390, symbol: 'MCD' },
  { name: 'Cosmic Chain', chainId: 67588, symbol: 'COSMIC' },
  { name: 'DM2 Verse Mainnet', chainId: 68770, symbol: 'OAS' },
  { name: 'Condrieu', chainId: 69420, symbol: 'CTE' },
  { name: 'Thinkium Mainnet Chain 0', chainId: 70000, symbol: 'TKM' },
  { name: 'Thinkium Mainnet Chain 1', chainId: 70001, symbol: 'TKM' },
  { name: 'Thinkium Mainnet Chain 2', chainId: 70002, symbol: 'TKM' },
  { name: 'Thinkium Mainnet Chain 103', chainId: 70103, symbol: 'TKM' },
  { name: 'GuapcoinX', chainId: 71111, symbol: 'GuapX' },
  { name: 'Polyjuice Testnet', chainId: 71393, symbol: 'CKB' },
  { name: 'Godwoken Testnet v1', chainId: 71401, symbol: 'pCKB' },
  { name: 'Godwoken Mainnet', chainId: 71402, symbol: 'pCKB' },
  { name: 'Energy Web Volta Testnet', chainId: 73799, symbol: 'VT' },
  { name: 'Mixin Virtual Machine', chainId: 73927, symbol: 'ETH' },
  { name: 'ResinCoin Mainnet', chainId: 75000, symbol: 'RESIN' },
  { name: 'Foundry Chain Testnet', chainId: 77238, symbol: 'tFNC' },
  { name: 'Vention Smart Chain Mainnet', chainId: 77612, symbol: 'VNT' },
  { name: 'Toronet Mainnet', chainId: 77777, symbol: 'TORO' },
  { name: 'Firenze test network', chainId: 78110, symbol: 'FIN' },
  { name: 'Dragonfly Mainnet (Hexapod)', chainId: 78281, symbol: 'DFLY' },
  { name: 'Amplify Subnet', chainId: 78430, symbol: 'AMP' },
  { name: 'Bulletin Subnet', chainId: 78431, symbol: 'BLT' },
  { name: 'Conduit Subnet', chainId: 78432, symbol: 'CON' },
  { name: 'Gold Smart Chain Testnet', chainId: 79879, symbol: 'STAND' },
  { name: 'Mumbai', chainId: 80001, symbol: 'MATIC' },
  { name: 'Amana Testnet', chainId: 81341, symbol: 'MEER-T' },
  { name: 'Amana Mixnet', chainId: 81342, symbol: 'MEER-M' },
  { name: 'Amana Privnet', chainId: 81343, symbol: 'MEER-P' },
  { name: 'Flana Testnet', chainId: 81351, symbol: 'MEER-T' },
  { name: 'Flana Mixnet', chainId: 81352, symbol: 'MEER-M' },
  { name: 'Flana Privnet', chainId: 81353, symbol: 'MEER-P' },
  { name: 'Mizana Testnet', chainId: 81361, symbol: 'MEER-T' },
  { name: 'Mizana Mixnet', chainId: 81362, symbol: 'MEER-M' },
  { name: 'Mizana Privnet', chainId: 81363, symbol: 'MEER-P' },
  { name: 'Quantum Chain Mainnet', chainId: 81720, symbol: 'QNET' },
  { name: 'Base Goerli Testnet', chainId: 84531, symbol: 'ETH' },
  { name: 'Base Sepolia Testnet', chainId: 84532, symbol: 'ETH' },
  { name: 'Aerie Network', chainId: 84886, symbol: 'AER' },
  { name: 'CYBERTRUST', chainId: 85449, symbol: 'CYBER' },
  { name: 'Nautilus Proteus Testnet', chainId: 88002, symbol: 'tZBC' },
  { name: 'Chiliz Scoville Testnet', chainId: 88880, symbol: 'CHZ' },
  { name: 'IVAR Chain Mainnet', chainId: 88888, symbol: 'IVAR' },
  { name: 'Beverly Hills', chainId: 90210, symbol: 'BVE' },
  { name: 'Nautilus Trition Chain', chainId: 91002, symbol: 'tZBC' },
  { name: 'Lambda Testnet', chainId: 92001, symbol: 'LAMB' },
  { name: 'Mantis Testnet (Hexapod)', chainId: 96970, symbol: 'MANTIS' },
  { name: 'Boba BNB Mainnet Old', chainId: 97288, symbol: 'BOBA' },
  { name: 'eLiberty Testnet', chainId: 99099, symbol: '$EL' },
  { name: 'UB Smart Chain(testnet)', chainId: 99998, symbol: 'UBC' },
  { name: 'UB Smart Chain', chainId: 99999, symbol: 'UBC' },
  { name: 'QuarkChain Mainnet Root', chainId: 100000, symbol: 'QKC' },
  { name: 'QuarkChain Mainnet Shard 0', chainId: 100001, symbol: 'QKC' },
  { name: 'QuarkChain Mainnet Shard 1', chainId: 100002, symbol: 'QKC' },
  { name: 'QuarkChain Mainnet Shard 2', chainId: 100003, symbol: 'QKC' },
  { name: 'QuarkChain Mainnet Shard 3', chainId: 100004, symbol: 'QKC' },
  { name: 'QuarkChain Mainnet Shard 4', chainId: 100005, symbol: 'QKC' },
  { name: 'QuarkChain Mainnet Shard 5', chainId: 100006, symbol: 'QKC' },
  { name: 'QuarkChain Mainnet Shard 6', chainId: 100007, symbol: 'QKC' },
  { name: 'QuarkChain Mainnet Shard 7', chainId: 100008, symbol: 'QKC' },
  { name: 'VeChain', chainId: 100009, symbol: 'VET' },
  { name: 'VeChain Testnet', chainId: 100010, symbol: 'VET' },
  { name: 'Deprecated CHI', chainId: 100100, symbol: 'xDAI' },
  { name: 'Soverun Testnet', chainId: 101010, symbol: 'SVRN' },
  { name: 'Crystaleum', chainId: 103090, symbol: '◈' },
  { name: 'BROChain Mainnet', chainId: 108801, symbol: 'BRO' },
  { name: 'QuarkChain Devnet Root', chainId: 110000, symbol: 'QKC' },
  { name: 'QuarkChain Devnet Shard 0', chainId: 110001, symbol: 'QKC' },
  { name: 'QuarkChain Devnet Shard 1', chainId: 110002, symbol: 'QKC' },
  { name: 'QuarkChain Devnet Shard 2', chainId: 110003, symbol: 'QKC' },
  { name: 'QuarkChain Devnet Shard 3', chainId: 110004, symbol: 'QKC' },
  { name: 'QuarkChain Devnet Shard 4', chainId: 110005, symbol: 'QKC' },
  { name: 'QuarkChain Devnet Shard 5', chainId: 110006, symbol: 'QKC' },
  { name: 'QuarkChain Devnet Shard 6', chainId: 110007, symbol: 'QKC' },
  { name: 'QuarkChain Devnet Shard 7', chainId: 110008, symbol: 'QKC' },
  { name: 'Siberium Test Network', chainId: 111000, symbol: 'SIBR' },
  { name: 'Siberium Network', chainId: 111111, symbol: 'SIBR' },
  { name: 'Metachain One Mainnet', chainId: 112358, symbol: 'METAO' },
  { name: 'ADIL Devnet', chainId: 123456, symbol: 'ADIL' },
  { name: 'ETND Chain Mainnets', chainId: 131419, symbol: 'ETND' },
  { name: 'ICPlaza Mainnet', chainId: 142857, symbol: 'ict' },
  { name: 'Taiko (Alpha-2 Testnet)', chainId: 167004, symbol: 'ETH' },
  { name: 'Taiko Grimsvotn L2', chainId: 167005, symbol: 'ETH' },
  { name: 'Taiko Eldfell L3', chainId: 167006, symbol: 'ETH' },
  { name: 'Taiko Jolnir L2', chainId: 167007, symbol: 'ETH' },
  { name: 'Bitica Chain Mainnet', chainId: 188710, symbol: 'BDCC' },
  { name: 'Condor Test Network', chainId: 188881, symbol: 'CONDOR' },
  { name: 'Milkomeda C1 Testnet', chainId: 200101, symbol: 'mTAda' },
  { name: 'Milkomeda A1 Testnet', chainId: 200202, symbol: 'mTAlgo' },
  { name: 'Akroma', chainId: 200625, symbol: 'AKA' },
  { name: 'Alaya Mainnet', chainId: 201018, symbol: 'atp' },
  { name: 'Alaya Dev Testnet', chainId: 201030, symbol: 'atp' },
  { name: 'Mythical Chain', chainId: 201804, symbol: 'MYTH' },
  { name: 'Decimal Smart Chain Testnet', chainId: 202020, symbol: 'tDEL' },
  { name: 'Jellie', chainId: 202624, symbol: 'TWL' },
  { name: 'PlatON Mainnet', chainId: 210425, symbol: 'lat' },
  { name: 'Mas Mainnet', chainId: 220315, symbol: 'MAS' },
  { name: 'Reapchain Mainnet', chainId: 221230, symbol: 'REAP' },
  { name: 'Reapchain Testnet', chainId: 221231, symbol: 'tREAP' },
  { name: 'Taf ECO Chain Mainnet', chainId: 224168, symbol: 'TAFECO' },
  { name: 'HashKey Chain Testnet', chainId: 230315, symbol: 'tHSK' },
  { name: 'Haymo Testnet', chainId: 234666, symbol: 'HYM' },
  { name: 'ARTIS sigma1', chainId: 246529, symbol: 'ATS' },
  { name: 'ARTIS Testnet tau1', chainId: 246785, symbol: 'tATS' },
  { name: 'Saakuru Testnet', chainId: 247253, symbol: 'OAS' },
  { name: 'CMP-Mainnet', chainId: 256256, symbol: 'CMP' },
  { name: 'Gear Zero Network Testnet', chainId: 266256, symbol: 'GZN' },
  { name: 'EgonCoin Testnet', chainId: 271271, symbol: 'EGON' },
  { name: 'Social Smart Chain Mainnet', chainId: 281121, symbol: '$OC' },
  { name: 'Filecoin - Calibration testnet', chainId: 314159, symbol: 'tFIL' },
  { name: 'TTcoin Smart Chain Mainnet', chainId: 330844, symbol: 'TC' },
  { name: 'Aves Testnet', chainId: 333331, symbol: 'AVST' },
  { name: 'Nativ3 Testnet', chainId: 333333, symbol: 'USNT' },
  { name: 'Oone Chain Testnet', chainId: 333666, symbol: 'tOONE' },
  { name: 'Oone Chain Devnet', chainId: 333777, symbol: 'tOONE' },
  { name: 'Polis Testnet', chainId: 333888, symbol: 'tPOLIS' },
  { name: 'Polis Mainnet', chainId: 333999, symbol: 'POLIS' },
  { name: 'Bitfinity Network Testnet', chainId: 355113, symbol: 'BFT' },
  { name: 'Digit Soul Smart Chain 2', chainId: 363636, symbol: 'DGC' },
  { name: 'HAPchain Testnet', chainId: 373737, symbol: 'HAP' },
  { name: 'Metal C-Chain', chainId: 381931, symbol: 'METAL' },
  { name: 'Metal Tahoe C-Chain', chainId: 381932, symbol: 'METAL' },
  { name: 'Tipboxcoin Mainnet', chainId: 404040, symbol: 'TPBX' },
  { name: 'Kekchain', chainId: 420420, symbol: 'KEK' },
  { name: 'Kekchain (kektest)', chainId: 420666, symbol: 'tKEK' },
  { name: 'Alterium L2 Testnet', chainId: 420692, symbol: 'AltETH' },
  { name: 'Arbitrum Rinkeby', chainId: 421611, symbol: 'ETH' },
  { name: 'Arbitrum Goerli', chainId: 421613, symbol: 'AGOR' },
  { name: 'Arbitrum Sepolia', chainId: 421614, symbol: 'ETH' },
  { name: 'Fastex Chain testnet', chainId: 424242, symbol: 'FTN' },
  { name: 'Markr Go', chainId: 431140, symbol: 'AVAX' },
  { name: 'Dexalot Subnet Testnet', chainId: 432201, symbol: 'ALOT' },
  { name: 'Dexalot Subnet', chainId: 432204, symbol: 'ALOT' },
  { name: 'Weelink Testnet', chainId: 444900, symbol: 'tWLK' },
  { name: 'Patex Sepolia Testnet', chainId: 471100, symbol: 'ETH' },
  { name: 'OpenChain Mainnet', chainId: 474142, symbol: 'OPC' },
  { name: 'CMP-Testnet', chainId: 512512, symbol: 'CMP' },
  { name: 'ethereum Fair', chainId: 513100, symbol: 'ETHF' },
  { name: 'Scroll Sepolia Testnet', chainId: 534351, symbol: 'ETH' },
  { name: 'Scroll', chainId: 534352, symbol: 'ETH' },
  { name: 'Scroll Alpha Testnet', chainId: 534353, symbol: 'ETH' },
  { name: 'Scroll Pre-Alpha Testnet', chainId: 534354, symbol: 'TSETH' },
  { name: 'Shinarium Beta', chainId: 534849, symbol: 'SHI' },
  { name: 'BeanEco SmartChain', chainId: 535037, symbol: 'BESC' },
  { name: 'Rethereum Mainnet', chainId: 622277, symbol: 'RTH' },
  { name: 'Bear Network Chain Mainnet', chainId: 641230, symbol: 'BRNKC' },
  { name: 'ALL Mainnet', chainId: 651940, symbol: 'ALL' },
  { name: 'Vision - Vpioneer Test Chain', chainId: 666666, symbol: 'VS' },
  { name: 'Hela Official Runtime Testnet', chainId: 666888, symbol: 'HLUSD' },
  { name: 'Bear Network Chain Testnet', chainId: 751230, symbol: 'tBRNKC' },
  { name: 'Miexs Smartchain', chainId: 761412, symbol: 'MIX' },
  { name: 'Modularium', chainId: 776877, symbol: 'MDM' },
  { name: 'OctaSpace', chainId: 800001, symbol: 'OCTA' },
  { name: 'CURVE Mainnet', chainId: 827431, symbol: 'CURVE' },
  { name: '4GoodNetwork', chainId: 846000, symbol: 'APTA' },
  { name: 'Dodao', chainId: 855456, symbol: 'DODAO' },
  { name: 'Vision - Mainnet', chainId: 888888, symbol: 'VS' },
  { name: 'Posichain Mainnet Shard 0', chainId: 900000, symbol: 'POSI' },
  { name: 'Posichain Testnet Shard 0', chainId: 910000, symbol: 'POSI' },
  { name: 'Posichain Devnet Shard 0', chainId: 920000, symbol: 'POSI' },
  { name: 'Posichain Devnet Shard 1', chainId: 920001, symbol: 'POSI' },
  { name: 'FNCY Testnet', chainId: 923018, symbol: 'FNCY' },
  { name: 'Eluvio Content Fabric', chainId: 955305, symbol: 'ELV' },
  { name: 'Ecrox Chain Mainnet', chainId: 988207, symbol: 'ECROX' },
  { name: 'zKatana', chainId: 1261120, symbol: 'ETH' },
  { name: 'Etho Protocol', chainId: 1313114, symbol: 'ETHO' },
  { name: 'Xerom', chainId: 1313500, symbol: 'XERO' },
  { name: 'Kintsugi', chainId: 1337702, symbol: 'kiETH' },
  { name: 'Kiln', chainId: 1337802, symbol: 'ETH' },
  { name: 'Zhejiang', chainId: 1337803, symbol: 'ETH' },
  { name: 'DeBank Testnet', chainId: 2021398, symbol: 'USD' },
  { name: 'Plian Mainnet Main', chainId: 2099156, symbol: 'PI' },
  { name: 'PlatON Dev Testnet Deprecated', chainId: 2203181, symbol: 'lat' },
  { name: 'PlatON Dev Testnet2', chainId: 2206132, symbol: 'lat' },
  { name: 'DPU Chain', chainId: 2611555, symbol: 'DGS' },
  { name: 'Filecoin - Butterfly testnet', chainId: 3141592, symbol: 'tFIL' },
  { name: 'Manta Pacific Testnet', chainId: 3441005, symbol: 'MANTA' },
  { name: 'AltLayer Zero Gas Network', chainId: 4000003, symbol: 'ZERO' },
  { name: 'Worlds Caldera', chainId: 4281033, symbol: 'ETH' },
  { name: 'MXC Wannsee zkEVM Testnet', chainId: 5167003, symbol: 'MXC' },
  { name: 'Electroneum Testnet', chainId: 5201420, symbol: 'ETN' },
  { name: 'Imversed Mainnet', chainId: 5555555, symbol: 'IMV' },
  { name: 'Imversed Testnet', chainId: 5555558, symbol: 'IMV' },
  { name: 'Saakuru Mainnet', chainId: 7225878, symbol: 'OAS' },
  { name: 'OpenVessel', chainId: 7355310, symbol: 'VETH' },
  { name: 'QL1 Testnet', chainId: 7668378, symbol: 'QOM' },
  { name: 'Musicoin', chainId: 7762959, symbol: 'MUSIC' },
  { name: 'Zora', chainId: 7777777, symbol: 'ETH' },
  { name: 'Plian Mainnet Subchain 1', chainId: 8007736, symbol: 'PI' },
  { name: 'HAPchain', chainId: 8794598, symbol: 'HAP' },
  { name: 'Quarix Testnet', chainId: 8888881, symbol: 'QARE' },
  { name: 'Quarix', chainId: 8888888, symbol: 'QARE' },
  { name: 'XCAP', chainId: 9322252, symbol: 'GAS' },
  { name: 'Milvine', chainId: 9322253, symbol: 'GAS' },
  { name: 'Plian Testnet Subchain 1', chainId: 10067275, symbol: 'TPI' },
  { name: 'Soverun Mainnet', chainId: 10101010, symbol: 'SVRN' },
  { name: 'Sepolia', chainId: 11155111, symbol: 'ETH' },
  { name: 'PepChain Churchill', chainId: 13371337, symbol: 'TPEP' },
  { name: 'Anduschain Mainnet', chainId: 14288640, symbol: 'DEB' },
  { name: 'Plian Testnet Main', chainId: 16658437, symbol: 'TPI' },
  { name: 'IOLite', chainId: 18289463, symbol: 'ILT' },
  { name: 'SmartMesh Mainnet', chainId: 20180430, symbol: 'SMT' },
  { name: 'quarkblockchain', chainId: 20181205, symbol: 'QKI' },
  { name: 'Pego Network', chainId: 20201022, symbol: 'PG' },
  { name: 'Excelon Mainnet', chainId: 22052002, symbol: 'xlon' },
  { name: 'Excoincial Chain Volta-Testnet', chainId: 27082017, symbol: 'TEXL' },
  { name: 'Excoincial Chain Mainnet', chainId: 27082022, symbol: 'EXL' },
  { name: 'Auxilium Network Mainnet', chainId: 28945486, symbol: 'AUX' },
  { name: 'Flachain Mainnet', chainId: 29032022, symbol: 'FLA' },
  { name: 'Filecoin - Local testnet', chainId: 31415926, symbol: 'tFIL' },
  { name: 'Joys Digital Mainnet', chainId: 35855456, symbol: 'JOYS' },
  { name: 'maistestsubnet', chainId: 43214913, symbol: 'MAI' },
  { name: 'Aquachain', chainId: 61717561, symbol: 'AQUA' },
  {
    name: 'Autonity Bakerloo (Thames) Testnet',
    chainId: 65010000,
    symbol: 'ATN',
  },
  {
    name: 'Autonity Piccadilly (Thames) Testnet',
    chainId: 65100000,
    symbol: 'ATN',
  },
  { name: 'Frame Testnet', chainId: 68840142, symbol: 'ETH' },
  { name: 'T.E.A.M Blockchain', chainId: 88888888, symbol: '$TEAM' },
  { name: 'Joys Digital TestNet', chainId: 99415706, symbol: 'TOYS' },
  { name: 'Gather Mainnet Network', chainId: 192837465, symbol: 'GTH' },
  { name: 'Kanazawa', chainId: 222000222, symbol: 'gMELD' },
  { name: 'Neon EVM DevNet', chainId: 245022926, symbol: 'NEON' },
  { name: 'Neon EVM MainNet', chainId: 245022934, symbol: 'NEON' },
  { name: 'Neon EVM TestNet', chainId: 245022940, symbol: 'NEON' },
  { name: 'Razor Skale Chain', chainId: 278611351, symbol: 'SFUEL' },
  { name: 'OneLedger Mainnet', chainId: 311752642, symbol: 'OLT' },
  { name: 'Meld', chainId: 333000333, symbol: 'gMELD' },
  {
    name: 'Calypso NFT Hub (SKALE Testnet)',
    chainId: 344106930,
    symbol: 'sFUEL',
  },
  { name: 'Gather Testnet Network', chainId: 356256156, symbol: 'GTH' },
  { name: 'Gather Devnet Network', chainId: 486217935, symbol: 'GTH' },
  { name: 'Nebula Staging', chainId: 503129905, symbol: 'sFUEL' },
  { name: 'Zora Sepolia Testnet', chainId: 999999999, symbol: 'ETH' },
  { name: 'IPOS Network', chainId: 1122334455, symbol: 'IPOS' },
  { name: 'CyberdeckNet', chainId: 1146703430, symbol: 'CYB' },
  { name: 'HUMAN Protocol', chainId: 1273227453, symbol: 'sFUEL' },
  { name: 'Aurora Mainnet', chainId: 1313161554, symbol: 'ETH' },
  { name: 'Aurora Testnet', chainId: 1313161555, symbol: 'ETH' },
  { name: 'Aurora Betanet', chainId: 1313161556, symbol: 'ETH' },
  { name: 'Chaos (SKALE Testnet)', chainId: 1351057110, symbol: 'sFUEL' },
  { name: 'RaptorChain', chainId: 1380996178, symbol: 'RPTR' },
  { name: 'Nebula Mainnet', chainId: 1482601649, symbol: 'sFUEL' },
  { name: 'Calypso NFT Hub (SKALE)', chainId: 1564830818, symbol: 'sFUEL' },
  { name: 'Harmony Mainnet Shard 0', chainId: 1666600000, symbol: 'ONE' },
  { name: 'Harmony Mainnet Shard 1', chainId: 1666600001, symbol: 'ONE' },
  { name: 'Harmony Mainnet Shard 2', chainId: 1666600002, symbol: 'ONE' },
  { name: 'Harmony Mainnet Shard 3', chainId: 1666600003, symbol: 'ONE' },
  { name: 'Harmony Testnet Shard 0', chainId: 1666700000, symbol: 'ONE' },
  { name: 'Harmony Testnet Shard 1', chainId: 1666700001, symbol: 'ONE' },
  { name: 'Harmony Devnet Shard 0', chainId: 1666900000, symbol: 'ONE' },
  { name: 'Harmony Devnet Shard 1', chainId: 1666900001, symbol: 'ONE' },
  { name: 'DataHopper', chainId: 2021121117, symbol: 'HOP' },
  { name: 'Europa SKALE Chain', chainId: 2046399126, symbol: 'sFUEL' },
  { name: 'Ancient8 Testnet', chainId: 2863311531, symbol: 'ETH' },
  { name: 'Pirl', chainId: 3125659152, symbol: 'PIRL' },
  {
    name: 'OneLedger Testnet Frankenstein',
    chainId: 4216137055,
    symbol: 'OLT',
  },
  { name: 'Palm Testnet', chainId: 11297108099, symbol: 'PALM' },
  { name: 'Palm', chainId: 11297108109, symbol: 'PALM' },
  { name: 'Alphabet Mainnet', chainId: 111222333444, symbol: 'ALT' },
  { name: 'Ntity Mainnet', chainId: 197710212030, symbol: 'NTT' },
  { name: 'Haradev Testnet', chainId: 197710212031, symbol: 'NTTH' },
  { name: 'Zeniq', chainId: 383414847825, symbol: 'ZENIQ' },
  { name: 'PDC Mainnet', chainId: 666301171999, symbol: 'PDC' },
  { name: 'Molereum Network', chainId: 6022140761023, symbol: 'MOLE' },
  { name: 'Godwoken Testnet (V1)', chainId: 868455272153094, symbol: 'CKB' },
];
