import { ApprovalType } from '@metamask/controller-utils';
import { MESSAGE_TYPE } from './app';

export const NUMBER_OF_REJECTIONS_THRESHOLD = 3;
export const REJECTION_THRESHOLD_IN_MS = 30000;
export const BLOCKING_THRESHOLD_IN_MS = 60000;

export const BLOCKABLE_METHODS: Set<string> = new Set([
  ApprovalType.Transaction,
  MESSAGE_TYPE.ETH_SEND_TRANSACTION,
  MESSAGE_TYPE.ETH_SIGN_TYPED_DATA,
  MESSAGE_TYPE.ETH_SIGN_TYPED_DATA_V1,
  MESSAGE_TYPE.ETH_SIGN_TYPED_DATA_V3,
  MESSAGE_TYPE.ETH_SIGN_TYPED_DATA_V4,
  MESSAGE_TYPE.PERSONAL_SIGN,
  MESSAGE_TYPE.WATCH_ASSET,
  MESSAGE_TYPE.ADD_ETHEREUM_CHAIN,
  MESSAGE_TYPE.SWITCH_ETHEREUM_CHAIN,
]);
