export const QUAI_CONTEXTS = [
  { name: 'Prime', value: 'prime', byte: ['00', '09'], id: '9000' },
  { name: 'Cyprus', value: 'cyprus', byte: ['0a', '13'], id: '9100' },
  { name: 'Cyprus One', value: 'cyprus-1', byte: ['14', '1d'], id: '9101' },
  { name: 'Cyprus Two', value: 'cyprus-2', byte: ['1e', '27'], id: '9102' },
  { name: 'Cyprus Three', value: 'cyprus-3', byte: ['28', '31'], id: '9103' },
  { name: 'Paxos', value: 'paxos', byte: ['32', '3b'], id: '9200' },
  { name: 'Paxos One', value: 'paxos-1', byte: ['3c', '45'], id: '9201' },
  { name: 'Paxos Two', value: 'paxos-2', byte: ['46', '4f'], id: '9202' },
  { name: 'Paxos Three', value: 'paxos-3', byte: ['50', '59'], id: '9203' },
  { name: 'Hydra', value: 'hydra', byte: ['5a', '63'], id: '9300' },
  { name: 'Hydra One', value: 'hydra-1', byte: ['64', '6d'], id: '9301' },
  { name: 'Hydra Two', value: 'hydra-2', byte: ['6e', '77'], id: '9302' },
  { name: 'Hydra Three', value: 'hydra-3', byte: ['78', '81'], id: '9303' },
];

export const QUAI_OPTIONS = [
  { name: 'Prime', value: 'prime' },
  { name: 'Cyprus', value: 'cyprus' },
  { name: 'Paxos', value: 'paxos' },
  { name: 'Hydra', value: 'hydra' },
  { name: 'Cyprus One', value: 'cyprus-1' },
  { name: 'Cyprus Two', value: 'cyprus-2' },
  { name: 'Cyprus Three', value: 'cyprus-3' },
  { name: 'Paxos One', value: 'paxos-1' },
  { name: 'Paxos Two', value: 'paxos-2' },
  { name: 'Paxos Three', value: 'paxos-3' },
  { name: 'Hydra One', value: 'hydra-1' },
  { name: 'Hydra Two', value: 'hydra-2' },
  { name: 'Hydra Three', value: 'hydra-3' },
];
