export const QUAI_TESTNET = 'quai_testnet';

export const QUAI_TESTNET_DISPLAY_NAME = 'Quai Testnet';

export const QUAI_TEST_CONTEXTS = [
  {
    name: 'Prime',
    value: 'prime',
    byte: ['00', '09'],
    id: '0x2328',
    rpc: 'http://45.76.19.78:8546',
    blockExplorerUrl: 'https://quaiscan.io',
  },
  {
    name: 'Cyprus',
    value: 'cyprus',
    byte: ['0a', '13'],
    id: '0x238c',
    rpc: 'http://45.76.19.78:8578',
    blockExplorerUrl: 'https://quaiscan.io',
  },
  {
    name: 'Cyprus One',
    value: 'cyprus-1',
    byte: ['14', '1d'],
    id: '0x16379',
    rpc: 'http://45.76.19.78:8610',
    blockExplorerUrl: 'https://quaiscan.io',
  },
  {
    name: 'Cyprus Two',
    value: 'cyprus-2',
    byte: ['1e', '27'],
    id: '0x1637A',
    rpc: 'http://45.76.19.78:8642',
    blockExplorerUrl: 'https://quaiscan.io',
  },
  {
    name: 'Cyprus Three',
    value: 'cyprus-3',
    byte: ['28', '31'],
    id: '0x1637B',
    rpc: 'http://45.76.19.78:8674',
    blockExplorerUrl: 'https://quaiscan.io',
  },
  {
    name: 'Paxos',
    value: 'paxos',
    byte: ['32', '3b'],
    id: '0x23f0',
    rpc: 'http://45.76.19.78:8580',
    blockExplorerUrl: 'https://quaiscan.io',
  },
  {
    name: 'Paxos One',
    value: 'paxos-1',
    byte: ['3c', '45'],
    id: '0x16761',
    rpc: 'http://45.76.19.78:8612',
    blockExplorerUrl: 'https://quaiscan.io',
  },
  {
    name: 'Paxos Two',
    value: 'paxos-2',
    byte: ['46', '4f'],
    id: '0x16762',
    rpc: 'http://45.76.19.78:8644',
    blockExplorerUrl: 'https://quaiscan.io',
  },
  {
    name: 'Paxos Three',
    value: 'paxos-3',
    byte: ['50', '59'],
    id: '0x16763',
    rpc: 'http://45.76.19.78:8576',
    blockExplorerUrl: 'https://quaiscan.io',
  },
  {
    name: 'Hydra',
    value: 'hydra',
    byte: ['5a', '63'],
    id: '0x2454',
    rpc: 'http://45.76.19.78:8582',
    blockExplorerUrl: 'https://quaiscan.io',
  },
  {
    name: 'Hydra One',
    value: 'hydra-1',
    byte: ['64', '6d'],
    id: '0x16B49',
    rpc: 'http://45.76.19.78:8614',
    blockExplorerUrl: 'https://quaiscan.io',
  },
  {
    name: 'Hydra Two',
    value: 'hydra-2',
    byte: ['6e', '77'],
    id: '0x16B4A',
    rpc: 'http://45.76.19.78:8646',
    blockExplorerUrl: 'https://quaiscan.io',
  },
  {
    name: 'Hydra Three',
    value: 'hydra-3',
    byte: ['78', '81'],
    id: '0x16B4B',
    rpc: 'http://45.76.19.78:8678',
    blockExplorerUrl: 'https://quaiscan.io',
  },
];

export const QUAI_OPTIONS = [
  { name: 'Prime', value: 'prime' },
  { name: 'Cyprus', value: 'cyprus' },
  { name: 'Paxos', value: 'paxos' },
  { name: 'Hydra', value: 'hydra' },
  { name: 'Cyprus One', value: 'cyprus-1' },
  { name: 'Cyprus Two', value: 'cyprus-2' },
  { name: 'Cyprus Three', value: 'cyprus-3' },
  { name: 'Paxos One', value: 'paxos-1' },
  { name: 'Paxos Two', value: 'paxos-2' },
  { name: 'Paxos Three', value: 'paxos-3' },
  { name: 'Hydra One', value: 'hydra-1' },
  { name: 'Hydra Two', value: 'hydra-2' },
  { name: 'Hydra Three', value: 'hydra-3' },
];
