import { SECOND } from './time';

export const FALLBACK_SMART_TRANSACTIONS_REFRESH_TIME = SECOND * 10;
export const FALLBACK_SMART_TRANSACTIONS_DEADLINE = 180;
export const FALLBACK_SMART_TRANSACTIONS_MAX_FEE_MULTIPLIER = 2;
