export const MILLISECOND = 1;
export const SECOND = MILLISECOND * 1000;
export const MINUTE = SECOND * 60;
export const HOUR = MINUTE * 60;
export const DAY = HOUR * 24;
export const WEEK = DAY * 7;
export const FORTNIGHT = DAY * 14;
export const MONTH = DAY * 30;
export const YEAR = DAY * 365;
