/**
 * Custom Jest transform for CSS files that creates a <link> tag instead of inlining styles.
 *
 * This transform is used for the pre-bundled CSS file (test/integration/config/assets/index.css)
 * to avoid jest-preview's CSS inlining which truncates large CSS files.
 *
 * The bundled CSS file is generated by webpack (development/webpack/webpack.integration.tests.config.ts)
 * and contains all styles including design-tokens CSS variables.
 */

module.exports = {
  process(src, filename) {
    // Get relative path from project root (e.g., /test/integration/config/assets/index.css)
    const relativePath = filename.split(process.cwd())[1].replace(/\\/g, '/');

    return {
      code: `
const link = document.createElement('link');
link.rel = 'stylesheet';
link.href = '${relativePath}';
document.head.appendChild(link);
module.exports = {};
`,
    };
  },
};
