
// these are used for global detection by some modules
const safeObjects = sesEval('({ Object, Symbol })')

const defaultGlobals = Object.assign({}, getAndBindGlobals(['console', 'atob', 'btoa', 'setTimeout', 'clearTimeout', 'clearInterval', 'setInterval']), safeObjects)
const moduleGlobals = {}
const depConfig = {}

function getAndBindGlobals (globalNames) {
  const selectedGlobals = {}
  globalNames.forEach(glob => {
    const value = deepGetAndBind(self, glob)
    if (value === undefined) return
    deepSet(selectedGlobals, glob, value)
  })
  return selectedGlobals
}

function deepGetAndBind(obj, pathName) {
  const pathParts = pathName.split('.')
  const parentPath = pathParts.slice(0,-1).join('.')
  const childKey = pathParts[pathParts.length-1]
  const globalRef = typeof self !== 'undefined' ? self : global
  const parent = parentPath ? deepGet(globalRef, parentPath) : globalRef
  if (!parent) return parent
  const value = parent[childKey]
  if (typeof value === 'function') {
    return value.bind(parent)
  }
  return value
}

function deepGet (obj, pathName) {
  let result = obj
  pathName.split('.').forEach(pathPart => {
    if (result === null) {
      result = undefined
      return
    }
    if (result === undefined) {
      return
    }
    result = result[pathPart]
  })
  return result
}

function deepSet (obj, pathName, value) {
  let parent = obj
  const pathParts = pathName.split('.')
  const lastPathPart = pathParts[pathParts.length-1]
  pathParts.slice(0,-1).forEach(pathPart => {
    const prevParent = parent
    parent = parent[pathPart]
    if (parent === null) {
      throw new Error('DeepSet - unable to set "'+pathName+'" on null')
    }
    if (parent === undefined) {
      parent = {}
      prevParent[pathPart] = parent
    }
  })
  parent[lastPathPart] = value
}

function exposeToModule (moduleName, globalNames) {
  const globalsToExpose = getAndBindGlobals(globalNames)
  moduleGlobals[moduleName] = Object.assign({}, defaultGlobals, globalsToExpose)
}

function exposeToDep (moduleName, depPath) {
  depConfig[depPath] = { $: moduleGlobals[moduleName] }
}

// set per-module globals config
exposeToModule('@material-ui/core', ['console.error', 'window'])
exposeToModule('@sentry/browser', ['DOMError', 'DOMException', 'ErrorEvent', 'Headers', 'Request', 'Response', 'XMLHttpRequest', 'document', 'window'])
exposeToModule('@sentry/core', ['console.log'])
exposeToModule('@sentry/utils', ['console.error', 'window'])
exposeToModule('@zxing/library', ['TextDecoder', 'TextEncoder', 'document.createElement', 'document.createElementNS', 'document.getElementById', 'navigator.mediaDevices.enumerateDevices', 'navigator.mediaDevices.getUserMedia', 'window'])
exposeToModule('web3', ['XMLHttpRequest', 'console.warn', 'console.error'])
exposeToModule('async', ['window'])
exposeToModule('bignumber.js', ['crypto'])
exposeToModule('boron', ['addEventListener', 'removeEventListener'])
exposeToModule('brorand', ['crypto', 'msCrypto'])
exposeToModule('vm-browserify', ['document.body.appendChild', 'document.body.removeChild', 'document.createElement'])
exposeToModule('c3', ['MutationObserver', 'SVGPathElement.prototype', 'SVGPathSeg', 'SVGPathSegArcAbs', 'SVGPathSegArcRel', 'SVGPathSegClosePath', 'SVGPathSegCurvetoCubicAbs', 'SVGPathSegCurvetoCubicRel', 'SVGPathSegCurvetoCubicSmoothAbs', 'SVGPathSegCurvetoCubicSmoothRel', 'SVGPathSegCurvetoQuadraticAbs', 'SVGPathSegCurvetoQuadraticRel', 'SVGPathSegCurvetoQuadraticSmoothAbs', 'SVGPathSegCurvetoQuadraticSmoothRel', 'SVGPathSegLinetoAbs', 'SVGPathSegLinetoHorizontalAbs', 'SVGPathSegLinetoHorizontalRel', 'SVGPathSegLinetoRel', 'SVGPathSegLinetoVerticalAbs', 'SVGPathSegLinetoVerticalRel', 'SVGPathSegList', 'SVGPathSegMovetoAbs', 'SVGPathSegMovetoRel', 'addEventListener', 'console.error', 'document.URL.split', 'document.createElement', 'document.createElementNS', 'document.createEvent', 'document.hidden', 'navigator.appVersion.toLowerCase', 'navigator.userAgent', 'onresize', 'removeEventListener', 'window'])
exposeToModule('copy-to-clipboard', ['console.error', 'console.warn', 'document.body.appendChild', 'document.body.removeChild', 'document.createElement', 'document.createRange', 'document.execCommand', 'document.getSelection', 'navigator.userAgent', 'prompt'])
exposeToModule('core-js', ['window', 'document.createTextNode', 'postMessage', 'PromiseRejectionEvent'])
exposeToModule('css-vendor', ['document.createElement', 'document.documentElement', 'getComputedStyle'])
exposeToModule('d3-fetch', ['DOMParser', 'Image', 'fetch'])
exposeToModule('d3-interpolate', ['document.createElement', 'document.createElementNS', 'document.defaultView', 'document.documentElement'])
exposeToModule('d3-selection', ['document'])
exposeToModule('d3-timer', ['performance', 'requestAnimationFrame', 'window'])
exposeToModule('d3-zoom', ['SVGElement'])
exposeToModule('detectrtc', ['InstallTrigger', 'MediaStream', 'MediaStreamTrack', 'RTCIceGatherer', 'RTCPeerConnection', 'WebSocket', 'chrome', 'document', 'indexedDB', 'localStorage', 'location', 'mozRTCPeerConnection', 'navigator', 'opera', 'screen', 'webkitMediaStream', 'webkitRTCPeerConnection', 'webkitRequestFileSystem', 'window'])
exposeToModule('dom-helpers', ['document', 'getComputedStyle', 'document.createElement', 'window', 'document.body.appendChild', 'document.body.removeChild'])
exposeToModule('domkit', ['document.createElement', 'document.documentElement', 'getComputedStyle', 'document.getElementsByTagName', 'window'])
exposeToModule('eth-token-tracker', ['console.error', 'console.warn'])
exposeToModule('eth-block-tracker', ['console.error'])
exposeToModule('eth-ens-namehash', ['name'])
exposeToModule('js-sha3', ['window', 'navigator.userAgent.indexOf'])
exposeToModule('extensionizer', ['browser', 'chrome', 'window'])
exposeToModule('fbjs', ['console.error', 'Worker', 'addEventListener', 'document', 'screen', 'document.createElement', 'window', 'msPerformance', 'performance', 'webkitPerformance'])
exposeToModule('history', ['confirm', 'document', 'history', 'navigator.userAgent', 'location', 'window', 'location.hash', 'location.href', 'location.replace'])
exposeToModule('inject-css', ['document.createElement', 'document.getElementsByTagName'])
exposeToModule('is-dom', ['Node'])
exposeToModule('is-in-browser', ['document', 'window'])
exposeToModule('jazzicon', ['document.createElement'])
exposeToModule('jss', ['document.createElement', 'document.getElementsByTagName', 'document.head', 'document.querySelector'])
exposeToModule('loglevel', ['document.cookie', 'localStorage'])
exposeToModule('luxon', ['Intl'])
exposeToModule('metamask-logo', ['addEventListener', 'document.body.appendChild', 'document.createElementNS', 'innerHeight', 'innerWidth', 'requestAnimationFrame'])
exposeToModule('obj-multiplex', ['console.warn'])
exposeToModule('pbkdf2', ['crypto'])
exposeToModule('popper.js', ['Node.DOCUMENT_POSITION_FOLLOWING', 'cancelAnimationFrame', 'console.warn', 'document', 'getComputedStyle', 'innerHeight', 'innerWidth', 'navigator.appVersion.indexOf', 'navigator.userAgent.indexOf', 'requestAnimationFrame', 'window'])
exposeToModule('randombytes', ['crypto', 'msCrypto'])
exposeToModule('randomfill', ['crypto', 'msCrypto'])
exposeToModule('raphael', ['ActiveXObject', 'DocumentTouch', 'document', 'mozRequestAnimationFrame', 'msRequestAnimationFrame', 'oRequestAnimationFrame', 'requestAnimationFrame', 'webkitRequestAnimationFrame', 'window'])
exposeToModule('react-dom', ['document', 'opera', 'window', 'document.createElement', 'document.documentElement.style.cssFloat', 'document.documentMode', 'document.createTextNode', 'navigator', 'document.createEvent', 'console.debug', 'location.protocol.indexOf', 'navigator.userAgent.indexOf', 'top', 'getSelection', 'location.href', 'performance', 'dispatchEvent', 'document.documentElement', 'document.selection', 'console.time', 'console.timeEnd', 'document.body.appendChild', 'document.body.removeChild', 'MSApp'])
exposeToModule('react-event-listener', ['window', 'addEventListener'])
exposeToModule('react-input-autosize', ['getComputedStyle', 'navigator.userAgent'])
exposeToModule('react-inspector', ['Node.TEXT_NODE', 'Node.CDATA_SECTION_NODE', 'Node.COMMENT_NODE', 'Node.DOCUMENT_FRAGMENT_NODE', 'Node.DOCUMENT_NODE', 'Node.DOCUMENT_TYPE_NODE', 'Node.ELEMENT_NODE', 'Node.PROCESSING_INSTRUCTION_NODE'])
exposeToModule('react-media', ['window'])
exposeToModule('react-select', ['location.href', 'open', 'document.activeElement', 'document.addEventListener', 'document.attachEvent', 'document.detachEvent', 'document.removeEventListener', 'innerHeight', 'scrollBy'])
exposeToModule('react-simple-file-input', ['File', 'FileReader', 'console.warn', 'window'])
exposeToModule('react-tippy', ['Element', 'MSStream', 'MutationObserver', 'addEventListener', 'console.error', 'console.warn', 'document', 'getComputedStyle', 'innerHeight', 'innerWidth', 'navigator.maxTouchPoints', 'navigator.msMaxTouchPoints', 'navigator.userAgent', 'performance', 'requestAnimationFrame', 'window'])
exposeToModule('react-toggle-button', ['console.warn', 'performance', 'window'])
exposeToModule('react-tooltip-component', ['document.body', 'document.createElement', 'pageXOffset', 'pageYOffset', 'scrollX', 'scrollY'])
exposeToModule('react', ['console.reactStack', 'console.reactStackEnd'])
exposeToModule('readable-stream', ['window'])
exposeToModule('recompose', ['console.error'])
exposeToModule('redux-logger', ['performance', 'window'])
exposeToModule('rtcpeerconnection-shim', ['Event', 'console.warn', 'document.createDocumentFragment'])
exposeToModule('set-immediate-shim', ['setTimeout.apply'])
exposeToModule('symbol-observable', ['window'])
exposeToModule('textarea-caret', ['document.body.appendChild', 'document.body.removeChild', 'document.createElement', 'document.querySelector', 'getComputedStyle', 'mozInnerScreenX'])
exposeToModule('timers-browserify', ['window'])
exposeToModule('toggle-selection', ['document.activeElement', 'document.getSelection'])
exposeToModule('util-deprecate', ['console.trace', 'console.warn', 'window'])
exposeToModule('util', ['console.error', 'console.log', 'console.trace', 'window'])
exposeToModule('webrtc-adapter', ['window', 'DOMException', 'Event', 'RTCSessionDescription', 'console.error', 'navigator.getDisplayMedia', 'navigator.mediaDevices.getUserMedia'])
exposeToModule('xhr2', ['XMLHttpRequest'])
// set in dep graph
// depGraph goes here
exposeToDep('@material-ui/core', '@material-ui/core')
exposeToDep('@sentry/browser', '@sentry/browser')
exposeToDep('@sentry/core', '@sentry/browser @sentry/core')
exposeToDep('@sentry/utils', '@sentry/browser @sentry/core @sentry/utils')
exposeToDep('@sentry/utils', '@sentry/browser @sentry/core @sentry/hub @sentry/utils')
exposeToDep('@sentry/utils', '@sentry/browser @sentry/core @sentry/minimal @sentry/hub @sentry/utils')
exposeToDep('@zxing/library', '@zxing/library')
exposeToDep('web3', 'abi-decoder web3')
exposeToDep('async', 'async')
exposeToDep('async', 'eth-token-tracker eth-block-tracker async-eventemitter async')
exposeToDep('bignumber.js', 'abi-decoder web3 bignumber.js')
exposeToDep('bignumber.js', 'bignumber.js')
exposeToDep('boron', 'boron')
exposeToDep('brorand', 'abi-decoder web3 bignumber.js crypto-browserify browserify-sign elliptic brorand')
exposeToDep('brorand', 'bignumber.js crypto-browserify browserify-sign elliptic brorand')
exposeToDep('brorand', 'abi-decoder web3 bignumber.js crypto-browserify create-ecdh elliptic brorand')
exposeToDep('brorand', 'bignumber.js crypto-browserify create-ecdh elliptic brorand')
exposeToDep('brorand', 'ethereumjs-util secp256k1 elliptic brorand')
exposeToDep('brorand', 'ethereumjs-abi ethereumjs-util secp256k1 elliptic brorand')
exposeToDep('brorand', 'abi-decoder web3 bignumber.js crypto-browserify diffie-hellman miller-rabin brorand')
exposeToDep('brorand', 'bignumber.js crypto-browserify diffie-hellman miller-rabin brorand')
exposeToDep('vm-browserify', 'abi-decoder web3 bignumber.js crypto-browserify browserify-sign parse-asn1 asn1.js vm-browserify')
exposeToDep('vm-browserify', 'bignumber.js crypto-browserify browserify-sign parse-asn1 asn1.js vm-browserify')
exposeToDep('vm-browserify', 'abi-decoder web3 bignumber.js crypto-browserify public-encrypt parse-asn1 asn1.js vm-browserify')
exposeToDep('vm-browserify', 'bignumber.js crypto-browserify public-encrypt parse-asn1 asn1.js vm-browserify')
exposeToDep('c3', 'c3')
exposeToDep('copy-to-clipboard', 'copy-to-clipboard')
exposeToDep('core-js', '@material-ui/core @babel/runtime core-js')
exposeToDep('core-js', 'babel-runtime core-js')
exposeToDep('core-js', 'recompose babel-runtime core-js')
exposeToDep('core-js', '@material-ui/core recompose babel-runtime core-js')
exposeToDep('core-js', 'ethjs ethjs-contract babel-runtime core-js')
exposeToDep('core-js', 'eth-method-registry ethjs ethjs-contract babel-runtime core-js')
exposeToDep('core-js', 'eth-token-tracker ethjs ethjs-contract babel-runtime core-js')
exposeToDep('core-js', 'eth-token-tracker ethjs-contract babel-runtime core-js')
exposeToDep('core-js', 'ethjs-ens ethjs-contract babel-runtime core-js')
exposeToDep('core-js', 'ethjs-contract babel-runtime core-js')
exposeToDep('core-js', 'ethjs ethjs-query babel-runtime core-js')
exposeToDep('core-js', 'eth-method-registry ethjs ethjs-query babel-runtime core-js')
exposeToDep('core-js', 'eth-token-tracker ethjs ethjs-query babel-runtime core-js')
exposeToDep('core-js', 'eth-token-tracker ethjs-query babel-runtime core-js')
exposeToDep('core-js', 'ethjs-ens ethjs-query babel-runtime core-js')
exposeToDep('core-js', 'ethjs-query babel-runtime core-js')
exposeToDep('core-js', 'eth-token-tracker babel-runtime core-js')
exposeToDep('core-js', 'eth-token-tracker eth-block-tracker babel-runtime core-js')
exposeToDep('core-js', '@material-ui/core react-event-listener babel-runtime core-js')
exposeToDep('core-js', 'react-inspector babel-runtime core-js')
exposeToDep('css-vendor', '@material-ui/core jss-vendor-prefixer css-vendor')
exposeToDep('d3-fetch', 'c3 d3 d3-fetch')
exposeToDep('d3-fetch', 'd3 d3-fetch')
exposeToDep('d3-interpolate', 'c3 d3 d3-brush d3-interpolate')
exposeToDep('d3-interpolate', 'd3 d3-brush d3-interpolate')
exposeToDep('d3-interpolate', 'c3 d3 d3-scale-chromatic d3-interpolate')
exposeToDep('d3-interpolate', 'd3 d3-scale-chromatic d3-interpolate')
exposeToDep('d3-interpolate', 'c3 d3 d3-scale d3-interpolate')
exposeToDep('d3-interpolate', 'd3 d3-scale d3-interpolate')
exposeToDep('d3-interpolate', 'c3 d3 d3-brush d3-transition d3-interpolate')
exposeToDep('d3-interpolate', 'd3 d3-brush d3-transition d3-interpolate')
exposeToDep('d3-interpolate', 'c3 d3 d3-zoom d3-transition d3-interpolate')
exposeToDep('d3-interpolate', 'd3 d3-zoom d3-transition d3-interpolate')
exposeToDep('d3-interpolate', 'c3 d3 d3-transition d3-interpolate')
exposeToDep('d3-interpolate', 'd3 d3-transition d3-interpolate')
exposeToDep('d3-interpolate', 'c3 d3 d3-zoom d3-interpolate')
exposeToDep('d3-interpolate', 'd3 d3-zoom d3-interpolate')
exposeToDep('d3-interpolate', 'c3 d3 d3-interpolate')
exposeToDep('d3-interpolate', 'd3 d3-interpolate')
exposeToDep('d3-selection', 'c3 d3 d3-brush d3-selection')
exposeToDep('d3-selection', 'd3 d3-brush d3-selection')
exposeToDep('d3-selection', 'c3 d3 d3-brush d3-drag d3-selection')
exposeToDep('d3-selection', 'd3 d3-brush d3-drag d3-selection')
exposeToDep('d3-selection', 'c3 d3 d3-zoom d3-drag d3-selection')
exposeToDep('d3-selection', 'd3 d3-zoom d3-drag d3-selection')
exposeToDep('d3-selection', 'c3 d3 d3-drag d3-selection')
exposeToDep('d3-selection', 'd3 d3-drag d3-selection')
exposeToDep('d3-selection', 'c3 d3 d3-brush d3-transition d3-selection')
exposeToDep('d3-selection', 'd3 d3-brush d3-transition d3-selection')
exposeToDep('d3-selection', 'c3 d3 d3-zoom d3-transition d3-selection')
exposeToDep('d3-selection', 'd3 d3-zoom d3-transition d3-selection')
exposeToDep('d3-selection', 'c3 d3 d3-transition d3-selection')
exposeToDep('d3-selection', 'd3 d3-transition d3-selection')
exposeToDep('d3-selection', 'c3 d3 d3-zoom d3-selection')
exposeToDep('d3-selection', 'd3 d3-zoom d3-selection')
exposeToDep('d3-selection', 'c3 d3 d3-selection')
exposeToDep('d3-selection', 'd3 d3-selection')
exposeToDep('d3-timer', 'c3 d3 d3-force d3-timer')
exposeToDep('d3-timer', 'd3 d3-force d3-timer')
exposeToDep('d3-timer', 'c3 d3 d3-brush d3-transition d3-timer')
exposeToDep('d3-timer', 'd3 d3-brush d3-transition d3-timer')
exposeToDep('d3-timer', 'c3 d3 d3-zoom d3-transition d3-timer')
exposeToDep('d3-timer', 'd3 d3-zoom d3-transition d3-timer')
exposeToDep('d3-timer', 'c3 d3 d3-transition d3-timer')
exposeToDep('d3-timer', 'd3 d3-transition d3-timer')
exposeToDep('d3-timer', 'c3 d3 d3-timer')
exposeToDep('d3-timer', 'd3 d3-timer')
exposeToDep('d3-zoom', 'c3 d3 d3-zoom')
exposeToDep('d3-zoom', 'd3 d3-zoom')
exposeToDep('detectrtc', 'detectrtc')
exposeToDep('dom-helpers', '@material-ui/core dom-helpers')
exposeToDep('dom-helpers', '@material-ui/core react-transition-group dom-helpers')
exposeToDep('dom-helpers', 'react-addons-css-transition-group react-transition-group dom-helpers')
exposeToDep('domkit', 'boron domkit')
exposeToDep('eth-token-tracker', 'eth-token-tracker')
exposeToDep('eth-block-tracker', 'eth-token-tracker eth-block-tracker')
exposeToDep('eth-ens-namehash', 'ethjs-ens eth-ens-namehash')
exposeToDep('js-sha3', 'ethereumjs-util keccakjs browserify-sha3 js-sha3')
exposeToDep('js-sha3', 'ethereumjs-abi ethereumjs-util keccakjs browserify-sha3 js-sha3')
exposeToDep('js-sha3', 'ethjs ethjs-contract ethjs-abi js-sha3')
exposeToDep('js-sha3', 'eth-method-registry ethjs ethjs-contract ethjs-abi js-sha3')
exposeToDep('js-sha3', 'eth-token-tracker ethjs ethjs-contract ethjs-abi js-sha3')
exposeToDep('js-sha3', 'eth-token-tracker ethjs-contract ethjs-abi js-sha3')
exposeToDep('js-sha3', 'ethjs-ens ethjs-contract ethjs-abi js-sha3')
exposeToDep('js-sha3', 'ethjs-contract ethjs-abi js-sha3')
exposeToDep('js-sha3', 'ethjs ethjs-abi js-sha3')
exposeToDep('js-sha3', 'eth-method-registry ethjs ethjs-abi js-sha3')
exposeToDep('js-sha3', 'eth-token-tracker ethjs ethjs-abi js-sha3')
exposeToDep('js-sha3', 'ethjs ethjs-contract js-sha3')
exposeToDep('js-sha3', 'eth-method-registry ethjs ethjs-contract js-sha3')
exposeToDep('js-sha3', 'eth-token-tracker ethjs ethjs-contract js-sha3')
exposeToDep('js-sha3', 'eth-token-tracker ethjs-contract js-sha3')
exposeToDep('js-sha3', 'ethjs-ens ethjs-contract js-sha3')
exposeToDep('js-sha3', 'ethjs-contract js-sha3')
exposeToDep('js-sha3', 'ethjs js-sha3')
exposeToDep('js-sha3', 'eth-method-registry ethjs js-sha3')
exposeToDep('js-sha3', 'eth-token-tracker ethjs js-sha3')
exposeToDep('js-sha3', 'ethjs-ens eth-ens-namehash js-sha3')
exposeToDep('extensionizer', 'extensionizer')
exposeToDep('extensionizer', 'extension-link-enabler extensionizer')
exposeToDep('fbjs', 'recompose fbjs')
exposeToDep('fbjs', '@material-ui/core recompose fbjs')
exposeToDep('fbjs', 'react create-react-class fbjs')
exposeToDep('fbjs', '@material-ui/core react create-react-class fbjs')
exposeToDep('fbjs', 'recompose react create-react-class fbjs')
exposeToDep('fbjs', '@material-ui/core recompose react create-react-class fbjs')
exposeToDep('fbjs', 'boron react create-react-class fbjs')
exposeToDep('fbjs', '@material-ui/core react-transition-group react create-react-class fbjs')
exposeToDep('fbjs', 'react-addons-css-transition-group react-transition-group react create-react-class fbjs')
exposeToDep('fbjs', '@material-ui/core react-dom react create-react-class fbjs')
exposeToDep('fbjs', '@material-ui/core react-transition-group react-dom react create-react-class fbjs')
exposeToDep('fbjs', 'react-addons-css-transition-group react-transition-group react-dom react create-react-class fbjs')
exposeToDep('fbjs', 'react-select react-dom react create-react-class fbjs')
exposeToDep('fbjs', 'react-tippy react-dom react create-react-class fbjs')
exposeToDep('fbjs', 'react-tooltip-component react-dom react create-react-class fbjs')
exposeToDep('fbjs', 'react-dom react create-react-class fbjs')
exposeToDep('fbjs', '@material-ui/core react-event-listener react create-react-class fbjs')
exposeToDep('fbjs', 'sandwich-expando react-hyperscript react create-react-class fbjs')
exposeToDep('fbjs', 'react-hyperscript react create-react-class fbjs')
exposeToDep('fbjs', 'react-select react-input-autosize react create-react-class fbjs')
exposeToDep('fbjs', 'react-inspector react create-react-class fbjs')
exposeToDep('fbjs', 'react-markdown react create-react-class fbjs')
exposeToDep('fbjs', 'react-media react create-react-class fbjs')
exposeToDep('fbjs', 'react-redux react create-react-class fbjs')
exposeToDep('fbjs', 'react-router-dom react create-react-class fbjs')
exposeToDep('fbjs', 'react-router-dom react-router react create-react-class fbjs')
exposeToDep('fbjs', 'react-select react create-react-class fbjs')
exposeToDep('fbjs', 'react-simple-file-input react create-react-class fbjs')
exposeToDep('fbjs', 'react-tippy react create-react-class fbjs')
exposeToDep('fbjs', 'react-toggle-button react create-react-class fbjs')
exposeToDep('fbjs', 'react-tooltip-component react create-react-class fbjs')
exposeToDep('fbjs', 'sandwich-expando react create-react-class fbjs')
exposeToDep('fbjs', 'prop-types fbjs')
exposeToDep('fbjs', '@material-ui/core prop-types fbjs')
exposeToDep('fbjs', '@material-ui/core react-transition-group prop-types fbjs')
exposeToDep('fbjs', 'react-addons-css-transition-group react-transition-group prop-types fbjs')
exposeToDep('fbjs', '@material-ui/core react-dom prop-types fbjs')
exposeToDep('fbjs', '@material-ui/core react-transition-group react-dom prop-types fbjs')
exposeToDep('fbjs', 'react-addons-css-transition-group react-transition-group react-dom prop-types fbjs')
exposeToDep('fbjs', 'react-select react-dom prop-types fbjs')
exposeToDep('fbjs', 'react-tippy react-dom prop-types fbjs')
exposeToDep('fbjs', 'react-tooltip-component react-dom prop-types fbjs')
exposeToDep('fbjs', 'react-dom prop-types fbjs')
exposeToDep('fbjs', '@material-ui/core react-event-listener prop-types fbjs')
exposeToDep('fbjs', 'react-select react-input-autosize prop-types fbjs')
exposeToDep('fbjs', 'react-inspector prop-types fbjs')
exposeToDep('fbjs', '@material-ui/core react-jss prop-types fbjs')
exposeToDep('fbjs', 'react-markdown prop-types fbjs')
exposeToDep('fbjs', 'react-redux prop-types fbjs')
exposeToDep('fbjs', 'react-router-dom prop-types fbjs')
exposeToDep('fbjs', 'react-router-dom react-router prop-types fbjs')
exposeToDep('fbjs', 'react-select prop-types fbjs')
exposeToDep('fbjs', 'react-simple-file-input prop-types fbjs')
exposeToDep('fbjs', 'react prop-types fbjs')
exposeToDep('fbjs', '@material-ui/core react prop-types fbjs')
exposeToDep('fbjs', 'recompose react prop-types fbjs')
exposeToDep('fbjs', '@material-ui/core recompose react prop-types fbjs')
exposeToDep('fbjs', 'boron react prop-types fbjs')
exposeToDep('fbjs', '@material-ui/core react-transition-group react prop-types fbjs')
exposeToDep('fbjs', 'react-addons-css-transition-group react-transition-group react prop-types fbjs')
exposeToDep('fbjs', '@material-ui/core react-dom react prop-types fbjs')
exposeToDep('fbjs', '@material-ui/core react-transition-group react-dom react prop-types fbjs')
exposeToDep('fbjs', 'react-addons-css-transition-group react-transition-group react-dom react prop-types fbjs')
exposeToDep('fbjs', 'react-select react-dom react prop-types fbjs')
exposeToDep('fbjs', 'react-tippy react-dom react prop-types fbjs')
exposeToDep('fbjs', 'react-tooltip-component react-dom react prop-types fbjs')
exposeToDep('fbjs', 'react-dom react prop-types fbjs')
exposeToDep('fbjs', '@material-ui/core react-event-listener react prop-types fbjs')
exposeToDep('fbjs', 'sandwich-expando react-hyperscript react prop-types fbjs')
exposeToDep('fbjs', 'react-hyperscript react prop-types fbjs')
exposeToDep('fbjs', 'react-select react-input-autosize react prop-types fbjs')
exposeToDep('fbjs', 'react-inspector react prop-types fbjs')
exposeToDep('fbjs', 'react-markdown react prop-types fbjs')
exposeToDep('fbjs', 'react-media react prop-types fbjs')
exposeToDep('fbjs', 'react-redux react prop-types fbjs')
exposeToDep('fbjs', 'react-router-dom react prop-types fbjs')
exposeToDep('fbjs', 'react-router-dom react-router react prop-types fbjs')
exposeToDep('fbjs', 'react-select react prop-types fbjs')
exposeToDep('fbjs', 'react-simple-file-input react prop-types fbjs')
exposeToDep('fbjs', 'react-tippy react prop-types fbjs')
exposeToDep('fbjs', 'react-toggle-button react prop-types fbjs')
exposeToDep('fbjs', 'react-tooltip-component react prop-types fbjs')
exposeToDep('fbjs', 'sandwich-expando react prop-types fbjs')
exposeToDep('fbjs', '@material-ui/core react-dom fbjs')
exposeToDep('fbjs', '@material-ui/core react-transition-group react-dom fbjs')
exposeToDep('fbjs', 'react-addons-css-transition-group react-transition-group react-dom fbjs')
exposeToDep('fbjs', 'react-select react-dom fbjs')
exposeToDep('fbjs', 'react-tippy react-dom fbjs')
exposeToDep('fbjs', 'react-tooltip-component react-dom fbjs')
exposeToDep('fbjs', 'react-dom fbjs')
exposeToDep('fbjs', '@material-ui/core react-event-listener fbjs')
exposeToDep('fbjs', 'react fbjs')
exposeToDep('fbjs', '@material-ui/core react fbjs')
exposeToDep('fbjs', 'recompose react fbjs')
exposeToDep('fbjs', '@material-ui/core recompose react fbjs')
exposeToDep('fbjs', 'boron react fbjs')
exposeToDep('fbjs', '@material-ui/core react-transition-group react fbjs')
exposeToDep('fbjs', 'react-addons-css-transition-group react-transition-group react fbjs')
exposeToDep('fbjs', '@material-ui/core react-dom react fbjs')
exposeToDep('fbjs', '@material-ui/core react-transition-group react-dom react fbjs')
exposeToDep('fbjs', 'react-addons-css-transition-group react-transition-group react-dom react fbjs')
exposeToDep('fbjs', 'react-select react-dom react fbjs')
exposeToDep('fbjs', 'react-tippy react-dom react fbjs')
exposeToDep('fbjs', 'react-tooltip-component react-dom react fbjs')
exposeToDep('fbjs', 'react-dom react fbjs')
exposeToDep('fbjs', '@material-ui/core react-event-listener react fbjs')
exposeToDep('fbjs', 'sandwich-expando react-hyperscript react fbjs')
exposeToDep('fbjs', 'react-hyperscript react fbjs')
exposeToDep('fbjs', 'react-select react-input-autosize react fbjs')
exposeToDep('fbjs', 'react-inspector react fbjs')
exposeToDep('fbjs', 'react-markdown react fbjs')
exposeToDep('fbjs', 'react-media react fbjs')
exposeToDep('fbjs', 'react-redux react fbjs')
exposeToDep('fbjs', 'react-router-dom react fbjs')
exposeToDep('fbjs', 'react-router-dom react-router react fbjs')
exposeToDep('fbjs', 'react-select react fbjs')
exposeToDep('fbjs', 'react-simple-file-input react fbjs')
exposeToDep('fbjs', 'react-tippy react fbjs')
exposeToDep('fbjs', 'react-toggle-button react fbjs')
exposeToDep('fbjs', 'react-tooltip-component react fbjs')
exposeToDep('fbjs', 'sandwich-expando react fbjs')
exposeToDep('history', 'react-router-dom history')
exposeToDep('history', 'react-router-dom react-router history')
exposeToDep('inject-css', 'inject-css')
exposeToDep('is-dom', 'react-inspector is-dom')
exposeToDep('is-in-browser', '@material-ui/core jss-vendor-prefixer css-vendor is-in-browser')
exposeToDep('is-in-browser', '@material-ui/core jss is-in-browser')
exposeToDep('is-in-browser', '@material-ui/core jss-global jss is-in-browser')
exposeToDep('jazzicon', 'jazzicon')
exposeToDep('jss', '@material-ui/core jss')
exposeToDep('jss', '@material-ui/core jss-global jss')
exposeToDep('loglevel', 'loglevel')
exposeToDep('luxon', 'luxon')
exposeToDep('metamask-logo', 'metamask-logo')
exposeToDep('obj-multiplex', 'obj-multiplex')
exposeToDep('pbkdf2', 'bip39 pbkdf2')
exposeToDep('pbkdf2', 'abi-decoder web3 bignumber.js crypto-browserify pbkdf2')
exposeToDep('pbkdf2', 'bignumber.js crypto-browserify pbkdf2')
exposeToDep('pbkdf2', 'abi-decoder web3 bignumber.js crypto-browserify browserify-sign parse-asn1 pbkdf2')
exposeToDep('pbkdf2', 'bignumber.js crypto-browserify browserify-sign parse-asn1 pbkdf2')
exposeToDep('pbkdf2', 'abi-decoder web3 bignumber.js crypto-browserify public-encrypt parse-asn1 pbkdf2')
exposeToDep('pbkdf2', 'bignumber.js crypto-browserify public-encrypt parse-asn1 pbkdf2')
exposeToDep('popper.js', 'react-tippy popper.js')
exposeToDep('randombytes', 'bip39 randombytes')
exposeToDep('randombytes', 'abi-decoder web3 bignumber.js crypto-browserify browserify-sign browserify-rsa randombytes')
exposeToDep('randombytes', 'bignumber.js crypto-browserify browserify-sign browserify-rsa randombytes')
exposeToDep('randombytes', 'abi-decoder web3 bignumber.js crypto-browserify public-encrypt browserify-rsa randombytes')
exposeToDep('randombytes', 'bignumber.js crypto-browserify public-encrypt browserify-rsa randombytes')
exposeToDep('randombytes', 'abi-decoder web3 bignumber.js crypto-browserify randombytes')
exposeToDep('randombytes', 'bignumber.js crypto-browserify randombytes')
exposeToDep('randombytes', 'abi-decoder web3 bignumber.js crypto-browserify diffie-hellman randombytes')
exposeToDep('randombytes', 'bignumber.js crypto-browserify diffie-hellman randombytes')
exposeToDep('randombytes', 'abi-decoder web3 bignumber.js crypto-browserify public-encrypt randombytes')
exposeToDep('randombytes', 'bignumber.js crypto-browserify public-encrypt randombytes')
exposeToDep('randombytes', 'abi-decoder web3 bignumber.js crypto-browserify randomfill randombytes')
exposeToDep('randombytes', 'bignumber.js crypto-browserify randomfill randombytes')
exposeToDep('randomfill', 'abi-decoder web3 bignumber.js crypto-browserify randomfill')
exposeToDep('randomfill', 'bignumber.js crypto-browserify randomfill')
exposeToDep('raphael', 'jazzicon raphael')
exposeToDep('react-dom', '@material-ui/core react-dom')
exposeToDep('react-dom', '@material-ui/core react-transition-group react-dom')
exposeToDep('react-dom', 'react-addons-css-transition-group react-transition-group react-dom')
exposeToDep('react-dom', 'react-select react-dom')
exposeToDep('react-dom', 'react-tippy react-dom')
exposeToDep('react-dom', 'react-tooltip-component react-dom')
exposeToDep('react-dom', 'react-dom')
exposeToDep('react-event-listener', '@material-ui/core react-event-listener')
exposeToDep('react-input-autosize', 'react-select react-input-autosize')
exposeToDep('react-inspector', 'react-inspector')
exposeToDep('react-media', 'react-media')
exposeToDep('react-select', 'react-select')
exposeToDep('react-simple-file-input', 'react-simple-file-input')
exposeToDep('react-tippy', 'react-tippy')
exposeToDep('react-toggle-button', 'react-toggle-button')
exposeToDep('react-tooltip-component', 'react-tooltip-component')
exposeToDep('react', 'react')
exposeToDep('react', '@material-ui/core react')
exposeToDep('react', 'recompose react')
exposeToDep('react', '@material-ui/core recompose react')
exposeToDep('react', 'boron react')
exposeToDep('react', '@material-ui/core react-transition-group react')
exposeToDep('react', 'react-addons-css-transition-group react-transition-group react')
exposeToDep('react', '@material-ui/core react-dom react')
exposeToDep('react', '@material-ui/core react-transition-group react-dom react')
exposeToDep('react', 'react-addons-css-transition-group react-transition-group react-dom react')
exposeToDep('react', 'react-select react-dom react')
exposeToDep('react', 'react-tippy react-dom react')
exposeToDep('react', 'react-tooltip-component react-dom react')
exposeToDep('react', 'react-dom react')
exposeToDep('react', '@material-ui/core react-event-listener react')
exposeToDep('react', 'sandwich-expando react-hyperscript react')
exposeToDep('react', 'react-hyperscript react')
exposeToDep('react', 'react-select react-input-autosize react')
exposeToDep('react', 'react-inspector react')
exposeToDep('react', 'react-markdown react')
exposeToDep('react', 'react-media react')
exposeToDep('react', 'react-redux react')
exposeToDep('react', 'react-router-dom react')
exposeToDep('react', 'react-router-dom react-router react')
exposeToDep('react', 'react-select react')
exposeToDep('react', 'react-simple-file-input react')
exposeToDep('react', 'react-tippy react')
exposeToDep('react', 'react-toggle-button react')
exposeToDep('react', 'react-tooltip-component react')
exposeToDep('react', 'sandwich-expando react')
exposeToDep('readable-stream', 'extension-port-stream readable-stream')
exposeToDep('readable-stream', 'obj-multiplex readable-stream')
exposeToDep('readable-stream', 'abi-decoder web3 bignumber.js crypto-browserify browserify-sign stream-browserify readable-stream')
exposeToDep('readable-stream', 'bignumber.js crypto-browserify browserify-sign stream-browserify readable-stream')
exposeToDep('readable-stream', 'abi-decoder web3 bignumber.js crypto-browserify browserify-cipher browserify-aes cipher-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'bignumber.js crypto-browserify browserify-cipher browserify-aes cipher-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'abi-decoder web3 bignumber.js crypto-browserify browserify-sign parse-asn1 browserify-aes cipher-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'bignumber.js crypto-browserify browserify-sign parse-asn1 browserify-aes cipher-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'abi-decoder web3 bignumber.js crypto-browserify public-encrypt parse-asn1 browserify-aes cipher-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'bignumber.js crypto-browserify public-encrypt parse-asn1 browserify-aes cipher-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'abi-decoder web3 bignumber.js crypto-browserify browserify-cipher browserify-des cipher-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'bignumber.js crypto-browserify browserify-cipher browserify-des cipher-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'bip39 create-hash cipher-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'abi-decoder web3 bignumber.js crypto-browserify browserify-sign create-hash cipher-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'bignumber.js crypto-browserify browserify-sign create-hash cipher-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'abi-decoder web3 bignumber.js crypto-browserify browserify-sign create-hmac create-hash cipher-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'bignumber.js crypto-browserify browserify-sign create-hmac create-hash cipher-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'abi-decoder web3 bignumber.js crypto-browserify create-hmac create-hash cipher-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'bignumber.js crypto-browserify create-hmac create-hash cipher-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'abi-decoder web3 bignumber.js crypto-browserify create-hash cipher-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'bignumber.js crypto-browserify create-hash cipher-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'ethereumjs-util create-hash cipher-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'ethereumjs-abi ethereumjs-util create-hash cipher-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'bip39 pbkdf2 create-hash cipher-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'abi-decoder web3 bignumber.js crypto-browserify pbkdf2 create-hash cipher-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'bignumber.js crypto-browserify pbkdf2 create-hash cipher-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'abi-decoder web3 bignumber.js crypto-browserify browserify-sign parse-asn1 pbkdf2 create-hash cipher-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'bignumber.js crypto-browserify browserify-sign parse-asn1 pbkdf2 create-hash cipher-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'abi-decoder web3 bignumber.js crypto-browserify public-encrypt parse-asn1 pbkdf2 create-hash cipher-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'bignumber.js crypto-browserify public-encrypt parse-asn1 pbkdf2 create-hash cipher-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'abi-decoder web3 bignumber.js crypto-browserify public-encrypt create-hash cipher-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'bignumber.js crypto-browserify public-encrypt create-hash cipher-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'ethereumjs-util secp256k1 create-hash cipher-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'ethereumjs-abi ethereumjs-util secp256k1 create-hash cipher-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'abi-decoder web3 bignumber.js crypto-browserify browserify-sign create-hmac cipher-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'bignumber.js crypto-browserify browserify-sign create-hmac cipher-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'abi-decoder web3 bignumber.js crypto-browserify create-hmac cipher-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'bignumber.js crypto-browserify create-hmac cipher-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'dnode stream-browserify readable-stream')
exposeToDep('readable-stream', 'abi-decoder web3 bignumber.js crypto-browserify browserify-cipher browserify-aes evp_bytestokey md5.js hash-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'bignumber.js crypto-browserify browserify-cipher browserify-aes evp_bytestokey md5.js hash-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'abi-decoder web3 bignumber.js crypto-browserify browserify-sign parse-asn1 browserify-aes evp_bytestokey md5.js hash-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'bignumber.js crypto-browserify browserify-sign parse-asn1 browserify-aes evp_bytestokey md5.js hash-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'abi-decoder web3 bignumber.js crypto-browserify public-encrypt parse-asn1 browserify-aes evp_bytestokey md5.js hash-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'bignumber.js crypto-browserify public-encrypt parse-asn1 browserify-aes evp_bytestokey md5.js hash-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'abi-decoder web3 bignumber.js crypto-browserify browserify-cipher evp_bytestokey md5.js hash-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'bignumber.js crypto-browserify browserify-cipher evp_bytestokey md5.js hash-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'abi-decoder web3 bignumber.js crypto-browserify browserify-sign parse-asn1 evp_bytestokey md5.js hash-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'bignumber.js crypto-browserify browserify-sign parse-asn1 evp_bytestokey md5.js hash-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'abi-decoder web3 bignumber.js crypto-browserify public-encrypt parse-asn1 evp_bytestokey md5.js hash-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'bignumber.js crypto-browserify public-encrypt parse-asn1 evp_bytestokey md5.js hash-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'bip39 create-hash ripemd160 hash-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'abi-decoder web3 bignumber.js crypto-browserify browserify-sign create-hash ripemd160 hash-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'bignumber.js crypto-browserify browserify-sign create-hash ripemd160 hash-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'abi-decoder web3 bignumber.js crypto-browserify browserify-sign create-hmac create-hash ripemd160 hash-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'bignumber.js crypto-browserify browserify-sign create-hmac create-hash ripemd160 hash-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'abi-decoder web3 bignumber.js crypto-browserify create-hmac create-hash ripemd160 hash-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'bignumber.js crypto-browserify create-hmac create-hash ripemd160 hash-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'abi-decoder web3 bignumber.js crypto-browserify create-hash ripemd160 hash-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'bignumber.js crypto-browserify create-hash ripemd160 hash-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'ethereumjs-util create-hash ripemd160 hash-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'ethereumjs-abi ethereumjs-util create-hash ripemd160 hash-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'bip39 pbkdf2 create-hash ripemd160 hash-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'abi-decoder web3 bignumber.js crypto-browserify pbkdf2 create-hash ripemd160 hash-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'bignumber.js crypto-browserify pbkdf2 create-hash ripemd160 hash-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'abi-decoder web3 bignumber.js crypto-browserify browserify-sign parse-asn1 pbkdf2 create-hash ripemd160 hash-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'bignumber.js crypto-browserify browserify-sign parse-asn1 pbkdf2 create-hash ripemd160 hash-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'abi-decoder web3 bignumber.js crypto-browserify public-encrypt parse-asn1 pbkdf2 create-hash ripemd160 hash-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'bignumber.js crypto-browserify public-encrypt parse-asn1 pbkdf2 create-hash ripemd160 hash-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'abi-decoder web3 bignumber.js crypto-browserify public-encrypt create-hash ripemd160 hash-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'bignumber.js crypto-browserify public-encrypt create-hash ripemd160 hash-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'ethereumjs-util secp256k1 create-hash ripemd160 hash-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'ethereumjs-abi ethereumjs-util secp256k1 create-hash ripemd160 hash-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'abi-decoder web3 bignumber.js crypto-browserify browserify-sign create-hmac ripemd160 hash-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'bignumber.js crypto-browserify browserify-sign create-hmac ripemd160 hash-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'abi-decoder web3 bignumber.js crypto-browserify create-hmac ripemd160 hash-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'bignumber.js crypto-browserify create-hmac ripemd160 hash-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'bip39 pbkdf2 ripemd160 hash-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'abi-decoder web3 bignumber.js crypto-browserify pbkdf2 ripemd160 hash-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'bignumber.js crypto-browserify pbkdf2 ripemd160 hash-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'abi-decoder web3 bignumber.js crypto-browserify browserify-sign parse-asn1 pbkdf2 ripemd160 hash-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'bignumber.js crypto-browserify browserify-sign parse-asn1 pbkdf2 ripemd160 hash-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'abi-decoder web3 bignumber.js crypto-browserify public-encrypt parse-asn1 pbkdf2 ripemd160 hash-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'bignumber.js crypto-browserify public-encrypt parse-asn1 pbkdf2 ripemd160 hash-base stream-browserify readable-stream')
exposeToDep('readable-stream', 'ethereumjs-util keccak stream-browserify readable-stream')
exposeToDep('readable-stream', 'ethereumjs-abi ethereumjs-util keccak stream-browserify readable-stream')
exposeToDep('readable-stream', 'through2 readable-stream')
exposeToDep('readable-stream', 'web3-stream-provider readable-stream')
exposeToDep('recompose', 'recompose')
exposeToDep('recompose', '@material-ui/core recompose')
exposeToDep('redux-logger', 'redux-logger')
exposeToDep('rtcpeerconnection-shim', 'webrtc-adapter rtcpeerconnection-shim')
exposeToDep('set-immediate-shim', 'ethjs ethjs-contract promise-to-callback set-immediate-shim')
exposeToDep('set-immediate-shim', 'eth-method-registry ethjs ethjs-contract promise-to-callback set-immediate-shim')
exposeToDep('set-immediate-shim', 'eth-token-tracker ethjs ethjs-contract promise-to-callback set-immediate-shim')
exposeToDep('set-immediate-shim', 'eth-token-tracker ethjs-contract promise-to-callback set-immediate-shim')
exposeToDep('set-immediate-shim', 'ethjs-ens ethjs-contract promise-to-callback set-immediate-shim')
exposeToDep('set-immediate-shim', 'ethjs-contract promise-to-callback set-immediate-shim')
exposeToDep('set-immediate-shim', 'ethjs ethjs-query promise-to-callback set-immediate-shim')
exposeToDep('set-immediate-shim', 'eth-method-registry ethjs ethjs-query promise-to-callback set-immediate-shim')
exposeToDep('set-immediate-shim', 'eth-token-tracker ethjs ethjs-query promise-to-callback set-immediate-shim')
exposeToDep('set-immediate-shim', 'eth-token-tracker ethjs-query promise-to-callback set-immediate-shim')
exposeToDep('set-immediate-shim', 'ethjs-ens ethjs-query promise-to-callback set-immediate-shim')
exposeToDep('set-immediate-shim', 'ethjs-query promise-to-callback set-immediate-shim')
exposeToDep('set-immediate-shim', 'ethjs ethjs-query ethjs-rpc promise-to-callback set-immediate-shim')
exposeToDep('set-immediate-shim', 'eth-method-registry ethjs ethjs-query ethjs-rpc promise-to-callback set-immediate-shim')
exposeToDep('set-immediate-shim', 'eth-token-tracker ethjs ethjs-query ethjs-rpc promise-to-callback set-immediate-shim')
exposeToDep('set-immediate-shim', 'eth-token-tracker ethjs-query ethjs-rpc promise-to-callback set-immediate-shim')
exposeToDep('set-immediate-shim', 'ethjs-ens ethjs-query ethjs-rpc promise-to-callback set-immediate-shim')
exposeToDep('set-immediate-shim', 'ethjs-query ethjs-rpc promise-to-callback set-immediate-shim')
exposeToDep('symbol-observable', '@material-ui/core jss symbol-observable')
exposeToDep('symbol-observable', '@material-ui/core jss-global jss symbol-observable')
exposeToDep('symbol-observable', 'recompose symbol-observable')
exposeToDep('symbol-observable', '@material-ui/core recompose symbol-observable')
exposeToDep('symbol-observable', 'react-redux redux symbol-observable')
exposeToDep('symbol-observable', 'redux symbol-observable')
exposeToDep('textarea-caret', 'textarea-caret')
exposeToDep('timers-browserify', 'async timers-browserify')
exposeToDep('timers-browserify', 'eth-token-tracker eth-block-tracker async-eventemitter async timers-browserify')
exposeToDep('timers-browserify', 'extension-port-stream readable-stream timers-browserify')
exposeToDep('timers-browserify', 'obj-multiplex readable-stream timers-browserify')
exposeToDep('timers-browserify', 'abi-decoder web3 bignumber.js crypto-browserify browserify-sign stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'bignumber.js crypto-browserify browserify-sign stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'abi-decoder web3 bignumber.js crypto-browserify browserify-cipher browserify-aes cipher-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'bignumber.js crypto-browserify browserify-cipher browserify-aes cipher-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'abi-decoder web3 bignumber.js crypto-browserify browserify-sign parse-asn1 browserify-aes cipher-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'bignumber.js crypto-browserify browserify-sign parse-asn1 browserify-aes cipher-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'abi-decoder web3 bignumber.js crypto-browserify public-encrypt parse-asn1 browserify-aes cipher-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'bignumber.js crypto-browserify public-encrypt parse-asn1 browserify-aes cipher-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'abi-decoder web3 bignumber.js crypto-browserify browserify-cipher browserify-des cipher-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'bignumber.js crypto-browserify browserify-cipher browserify-des cipher-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'bip39 create-hash cipher-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'abi-decoder web3 bignumber.js crypto-browserify browserify-sign create-hash cipher-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'bignumber.js crypto-browserify browserify-sign create-hash cipher-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'abi-decoder web3 bignumber.js crypto-browserify browserify-sign create-hmac create-hash cipher-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'bignumber.js crypto-browserify browserify-sign create-hmac create-hash cipher-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'abi-decoder web3 bignumber.js crypto-browserify create-hmac create-hash cipher-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'bignumber.js crypto-browserify create-hmac create-hash cipher-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'abi-decoder web3 bignumber.js crypto-browserify create-hash cipher-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'bignumber.js crypto-browserify create-hash cipher-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'ethereumjs-util create-hash cipher-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'ethereumjs-abi ethereumjs-util create-hash cipher-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'bip39 pbkdf2 create-hash cipher-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'abi-decoder web3 bignumber.js crypto-browserify pbkdf2 create-hash cipher-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'bignumber.js crypto-browserify pbkdf2 create-hash cipher-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'abi-decoder web3 bignumber.js crypto-browserify browserify-sign parse-asn1 pbkdf2 create-hash cipher-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'bignumber.js crypto-browserify browserify-sign parse-asn1 pbkdf2 create-hash cipher-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'abi-decoder web3 bignumber.js crypto-browserify public-encrypt parse-asn1 pbkdf2 create-hash cipher-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'bignumber.js crypto-browserify public-encrypt parse-asn1 pbkdf2 create-hash cipher-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'abi-decoder web3 bignumber.js crypto-browserify public-encrypt create-hash cipher-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'bignumber.js crypto-browserify public-encrypt create-hash cipher-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'ethereumjs-util secp256k1 create-hash cipher-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'ethereumjs-abi ethereumjs-util secp256k1 create-hash cipher-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'abi-decoder web3 bignumber.js crypto-browserify browserify-sign create-hmac cipher-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'bignumber.js crypto-browserify browserify-sign create-hmac cipher-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'abi-decoder web3 bignumber.js crypto-browserify create-hmac cipher-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'bignumber.js crypto-browserify create-hmac cipher-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'dnode stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'abi-decoder web3 bignumber.js crypto-browserify browserify-cipher browserify-aes evp_bytestokey md5.js hash-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'bignumber.js crypto-browserify browserify-cipher browserify-aes evp_bytestokey md5.js hash-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'abi-decoder web3 bignumber.js crypto-browserify browserify-sign parse-asn1 browserify-aes evp_bytestokey md5.js hash-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'bignumber.js crypto-browserify browserify-sign parse-asn1 browserify-aes evp_bytestokey md5.js hash-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'abi-decoder web3 bignumber.js crypto-browserify public-encrypt parse-asn1 browserify-aes evp_bytestokey md5.js hash-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'bignumber.js crypto-browserify public-encrypt parse-asn1 browserify-aes evp_bytestokey md5.js hash-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'abi-decoder web3 bignumber.js crypto-browserify browserify-cipher evp_bytestokey md5.js hash-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'bignumber.js crypto-browserify browserify-cipher evp_bytestokey md5.js hash-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'abi-decoder web3 bignumber.js crypto-browserify browserify-sign parse-asn1 evp_bytestokey md5.js hash-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'bignumber.js crypto-browserify browserify-sign parse-asn1 evp_bytestokey md5.js hash-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'abi-decoder web3 bignumber.js crypto-browserify public-encrypt parse-asn1 evp_bytestokey md5.js hash-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'bignumber.js crypto-browserify public-encrypt parse-asn1 evp_bytestokey md5.js hash-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'bip39 create-hash ripemd160 hash-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'abi-decoder web3 bignumber.js crypto-browserify browserify-sign create-hash ripemd160 hash-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'bignumber.js crypto-browserify browserify-sign create-hash ripemd160 hash-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'abi-decoder web3 bignumber.js crypto-browserify browserify-sign create-hmac create-hash ripemd160 hash-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'bignumber.js crypto-browserify browserify-sign create-hmac create-hash ripemd160 hash-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'abi-decoder web3 bignumber.js crypto-browserify create-hmac create-hash ripemd160 hash-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'bignumber.js crypto-browserify create-hmac create-hash ripemd160 hash-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'abi-decoder web3 bignumber.js crypto-browserify create-hash ripemd160 hash-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'bignumber.js crypto-browserify create-hash ripemd160 hash-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'ethereumjs-util create-hash ripemd160 hash-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'ethereumjs-abi ethereumjs-util create-hash ripemd160 hash-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'bip39 pbkdf2 create-hash ripemd160 hash-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'abi-decoder web3 bignumber.js crypto-browserify pbkdf2 create-hash ripemd160 hash-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'bignumber.js crypto-browserify pbkdf2 create-hash ripemd160 hash-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'abi-decoder web3 bignumber.js crypto-browserify browserify-sign parse-asn1 pbkdf2 create-hash ripemd160 hash-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'bignumber.js crypto-browserify browserify-sign parse-asn1 pbkdf2 create-hash ripemd160 hash-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'abi-decoder web3 bignumber.js crypto-browserify public-encrypt parse-asn1 pbkdf2 create-hash ripemd160 hash-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'bignumber.js crypto-browserify public-encrypt parse-asn1 pbkdf2 create-hash ripemd160 hash-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'abi-decoder web3 bignumber.js crypto-browserify public-encrypt create-hash ripemd160 hash-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'bignumber.js crypto-browserify public-encrypt create-hash ripemd160 hash-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'ethereumjs-util secp256k1 create-hash ripemd160 hash-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'ethereumjs-abi ethereumjs-util secp256k1 create-hash ripemd160 hash-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'abi-decoder web3 bignumber.js crypto-browserify browserify-sign create-hmac ripemd160 hash-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'bignumber.js crypto-browserify browserify-sign create-hmac ripemd160 hash-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'abi-decoder web3 bignumber.js crypto-browserify create-hmac ripemd160 hash-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'bignumber.js crypto-browserify create-hmac ripemd160 hash-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'bip39 pbkdf2 ripemd160 hash-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'abi-decoder web3 bignumber.js crypto-browserify pbkdf2 ripemd160 hash-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'bignumber.js crypto-browserify pbkdf2 ripemd160 hash-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'abi-decoder web3 bignumber.js crypto-browserify browserify-sign parse-asn1 pbkdf2 ripemd160 hash-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'bignumber.js crypto-browserify browserify-sign parse-asn1 pbkdf2 ripemd160 hash-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'abi-decoder web3 bignumber.js crypto-browserify public-encrypt parse-asn1 pbkdf2 ripemd160 hash-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'bignumber.js crypto-browserify public-encrypt parse-asn1 pbkdf2 ripemd160 hash-base stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'ethereumjs-util keccak stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'ethereumjs-abi ethereumjs-util keccak stream-browserify readable-stream timers-browserify')
exposeToDep('timers-browserify', 'through2 readable-stream timers-browserify')
exposeToDep('timers-browserify', 'web3-stream-provider readable-stream timers-browserify')
exposeToDep('timers-browserify', 'ethjs ethjs-contract promise-to-callback set-immediate-shim timers-browserify')
exposeToDep('timers-browserify', 'eth-method-registry ethjs ethjs-contract promise-to-callback set-immediate-shim timers-browserify')
exposeToDep('timers-browserify', 'eth-token-tracker ethjs ethjs-contract promise-to-callback set-immediate-shim timers-browserify')
exposeToDep('timers-browserify', 'eth-token-tracker ethjs-contract promise-to-callback set-immediate-shim timers-browserify')
exposeToDep('timers-browserify', 'ethjs-ens ethjs-contract promise-to-callback set-immediate-shim timers-browserify')
exposeToDep('timers-browserify', 'ethjs-contract promise-to-callback set-immediate-shim timers-browserify')
exposeToDep('timers-browserify', 'ethjs ethjs-query promise-to-callback set-immediate-shim timers-browserify')
exposeToDep('timers-browserify', 'eth-method-registry ethjs ethjs-query promise-to-callback set-immediate-shim timers-browserify')
exposeToDep('timers-browserify', 'eth-token-tracker ethjs ethjs-query promise-to-callback set-immediate-shim timers-browserify')
exposeToDep('timers-browserify', 'eth-token-tracker ethjs-query promise-to-callback set-immediate-shim timers-browserify')
exposeToDep('timers-browserify', 'ethjs-ens ethjs-query promise-to-callback set-immediate-shim timers-browserify')
exposeToDep('timers-browserify', 'ethjs-query promise-to-callback set-immediate-shim timers-browserify')
exposeToDep('timers-browserify', 'ethjs ethjs-query ethjs-rpc promise-to-callback set-immediate-shim timers-browserify')
exposeToDep('timers-browserify', 'eth-method-registry ethjs ethjs-query ethjs-rpc promise-to-callback set-immediate-shim timers-browserify')
exposeToDep('timers-browserify', 'eth-token-tracker ethjs ethjs-query ethjs-rpc promise-to-callback set-immediate-shim timers-browserify')
exposeToDep('timers-browserify', 'eth-token-tracker ethjs-query ethjs-rpc promise-to-callback set-immediate-shim timers-browserify')
exposeToDep('timers-browserify', 'ethjs-ens ethjs-query ethjs-rpc promise-to-callback set-immediate-shim timers-browserify')
exposeToDep('timers-browserify', 'ethjs-query ethjs-rpc promise-to-callback set-immediate-shim timers-browserify')
exposeToDep('toggle-selection', 'copy-to-clipboard toggle-selection')
exposeToDep('util-deprecate', 'extension-port-stream readable-stream util-deprecate')
exposeToDep('util-deprecate', 'obj-multiplex readable-stream util-deprecate')
exposeToDep('util-deprecate', 'abi-decoder web3 bignumber.js crypto-browserify browserify-sign stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'bignumber.js crypto-browserify browserify-sign stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'abi-decoder web3 bignumber.js crypto-browserify browserify-cipher browserify-aes cipher-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'bignumber.js crypto-browserify browserify-cipher browserify-aes cipher-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'abi-decoder web3 bignumber.js crypto-browserify browserify-sign parse-asn1 browserify-aes cipher-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'bignumber.js crypto-browserify browserify-sign parse-asn1 browserify-aes cipher-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'abi-decoder web3 bignumber.js crypto-browserify public-encrypt parse-asn1 browserify-aes cipher-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'bignumber.js crypto-browserify public-encrypt parse-asn1 browserify-aes cipher-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'abi-decoder web3 bignumber.js crypto-browserify browserify-cipher browserify-des cipher-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'bignumber.js crypto-browserify browserify-cipher browserify-des cipher-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'bip39 create-hash cipher-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'abi-decoder web3 bignumber.js crypto-browserify browserify-sign create-hash cipher-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'bignumber.js crypto-browserify browserify-sign create-hash cipher-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'abi-decoder web3 bignumber.js crypto-browserify browserify-sign create-hmac create-hash cipher-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'bignumber.js crypto-browserify browserify-sign create-hmac create-hash cipher-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'abi-decoder web3 bignumber.js crypto-browserify create-hmac create-hash cipher-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'bignumber.js crypto-browserify create-hmac create-hash cipher-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'abi-decoder web3 bignumber.js crypto-browserify create-hash cipher-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'bignumber.js crypto-browserify create-hash cipher-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'ethereumjs-util create-hash cipher-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'ethereumjs-abi ethereumjs-util create-hash cipher-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'bip39 pbkdf2 create-hash cipher-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'abi-decoder web3 bignumber.js crypto-browserify pbkdf2 create-hash cipher-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'bignumber.js crypto-browserify pbkdf2 create-hash cipher-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'abi-decoder web3 bignumber.js crypto-browserify browserify-sign parse-asn1 pbkdf2 create-hash cipher-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'bignumber.js crypto-browserify browserify-sign parse-asn1 pbkdf2 create-hash cipher-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'abi-decoder web3 bignumber.js crypto-browserify public-encrypt parse-asn1 pbkdf2 create-hash cipher-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'bignumber.js crypto-browserify public-encrypt parse-asn1 pbkdf2 create-hash cipher-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'abi-decoder web3 bignumber.js crypto-browserify public-encrypt create-hash cipher-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'bignumber.js crypto-browserify public-encrypt create-hash cipher-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'ethereumjs-util secp256k1 create-hash cipher-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'ethereumjs-abi ethereumjs-util secp256k1 create-hash cipher-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'abi-decoder web3 bignumber.js crypto-browserify browserify-sign create-hmac cipher-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'bignumber.js crypto-browserify browserify-sign create-hmac cipher-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'abi-decoder web3 bignumber.js crypto-browserify create-hmac cipher-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'bignumber.js crypto-browserify create-hmac cipher-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'dnode stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'abi-decoder web3 bignumber.js crypto-browserify browserify-cipher browserify-aes evp_bytestokey md5.js hash-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'bignumber.js crypto-browserify browserify-cipher browserify-aes evp_bytestokey md5.js hash-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'abi-decoder web3 bignumber.js crypto-browserify browserify-sign parse-asn1 browserify-aes evp_bytestokey md5.js hash-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'bignumber.js crypto-browserify browserify-sign parse-asn1 browserify-aes evp_bytestokey md5.js hash-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'abi-decoder web3 bignumber.js crypto-browserify public-encrypt parse-asn1 browserify-aes evp_bytestokey md5.js hash-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'bignumber.js crypto-browserify public-encrypt parse-asn1 browserify-aes evp_bytestokey md5.js hash-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'abi-decoder web3 bignumber.js crypto-browserify browserify-cipher evp_bytestokey md5.js hash-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'bignumber.js crypto-browserify browserify-cipher evp_bytestokey md5.js hash-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'abi-decoder web3 bignumber.js crypto-browserify browserify-sign parse-asn1 evp_bytestokey md5.js hash-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'bignumber.js crypto-browserify browserify-sign parse-asn1 evp_bytestokey md5.js hash-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'abi-decoder web3 bignumber.js crypto-browserify public-encrypt parse-asn1 evp_bytestokey md5.js hash-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'bignumber.js crypto-browserify public-encrypt parse-asn1 evp_bytestokey md5.js hash-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'bip39 create-hash ripemd160 hash-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'abi-decoder web3 bignumber.js crypto-browserify browserify-sign create-hash ripemd160 hash-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'bignumber.js crypto-browserify browserify-sign create-hash ripemd160 hash-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'abi-decoder web3 bignumber.js crypto-browserify browserify-sign create-hmac create-hash ripemd160 hash-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'bignumber.js crypto-browserify browserify-sign create-hmac create-hash ripemd160 hash-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'abi-decoder web3 bignumber.js crypto-browserify create-hmac create-hash ripemd160 hash-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'bignumber.js crypto-browserify create-hmac create-hash ripemd160 hash-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'abi-decoder web3 bignumber.js crypto-browserify create-hash ripemd160 hash-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'bignumber.js crypto-browserify create-hash ripemd160 hash-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'ethereumjs-util create-hash ripemd160 hash-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'ethereumjs-abi ethereumjs-util create-hash ripemd160 hash-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'bip39 pbkdf2 create-hash ripemd160 hash-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'abi-decoder web3 bignumber.js crypto-browserify pbkdf2 create-hash ripemd160 hash-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'bignumber.js crypto-browserify pbkdf2 create-hash ripemd160 hash-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'abi-decoder web3 bignumber.js crypto-browserify browserify-sign parse-asn1 pbkdf2 create-hash ripemd160 hash-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'bignumber.js crypto-browserify browserify-sign parse-asn1 pbkdf2 create-hash ripemd160 hash-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'abi-decoder web3 bignumber.js crypto-browserify public-encrypt parse-asn1 pbkdf2 create-hash ripemd160 hash-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'bignumber.js crypto-browserify public-encrypt parse-asn1 pbkdf2 create-hash ripemd160 hash-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'abi-decoder web3 bignumber.js crypto-browserify public-encrypt create-hash ripemd160 hash-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'bignumber.js crypto-browserify public-encrypt create-hash ripemd160 hash-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'ethereumjs-util secp256k1 create-hash ripemd160 hash-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'ethereumjs-abi ethereumjs-util secp256k1 create-hash ripemd160 hash-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'abi-decoder web3 bignumber.js crypto-browserify browserify-sign create-hmac ripemd160 hash-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'bignumber.js crypto-browserify browserify-sign create-hmac ripemd160 hash-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'abi-decoder web3 bignumber.js crypto-browserify create-hmac ripemd160 hash-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'bignumber.js crypto-browserify create-hmac ripemd160 hash-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'bip39 pbkdf2 ripemd160 hash-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'abi-decoder web3 bignumber.js crypto-browserify pbkdf2 ripemd160 hash-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'bignumber.js crypto-browserify pbkdf2 ripemd160 hash-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'abi-decoder web3 bignumber.js crypto-browserify browserify-sign parse-asn1 pbkdf2 ripemd160 hash-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'bignumber.js crypto-browserify browserify-sign parse-asn1 pbkdf2 ripemd160 hash-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'abi-decoder web3 bignumber.js crypto-browserify public-encrypt parse-asn1 pbkdf2 ripemd160 hash-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'bignumber.js crypto-browserify public-encrypt parse-asn1 pbkdf2 ripemd160 hash-base stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'ethereumjs-util keccak stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'ethereumjs-abi ethereumjs-util keccak stream-browserify readable-stream util-deprecate')
exposeToDep('util-deprecate', 'through2 readable-stream util-deprecate')
exposeToDep('util-deprecate', 'web3-stream-provider readable-stream util-deprecate')
exposeToDep('util', 'assert util')
exposeToDep('util', 'ethereumjs-util assert util')
exposeToDep('util', 'ethereumjs-abi ethereumjs-util assert util')
exposeToDep('util', 'ethereumjs-util rlp assert util')
exposeToDep('util', 'ethereumjs-abi ethereumjs-util rlp assert util')
exposeToDep('util', 'eth-token-tracker eth-block-tracker async-eventemitter util')
exposeToDep('util', 'extension-port-stream util')
exposeToDep('util', 'sandwich-expando util')
exposeToDep('util', 'through2 util')
exposeToDep('util', 'web3-stream-provider util')
exposeToDep('util', 'util')
exposeToDep('webrtc-adapter', 'webrtc-adapter')
exposeToDep('xhr2', 'abi-decoder web3 xhr2')
exposeToDep('xhr2', 'ethjs ethjs-provider-http xhr2')
exposeToDep('xhr2', 'eth-method-registry ethjs ethjs-provider-http xhr2')
exposeToDep('xhr2', 'eth-token-tracker ethjs ethjs-provider-http xhr2')

const config = {
  dependencies: depConfig,
  global: {},
  defaultGlobals,
}

return config