import { MetaMaskReduxState } from '../../../ui/store/store';
import {
  HardwareTransportStates,
  WebHIDConnectedStatuses,
} from '../../../shared/constants/hardware-wallets';
import { AlertTypes } from '../../../shared/constants/alerts';
import { SortOrder } from '@metamask/bridge-controller';
import sentryBackgroundStateFixture from './sentry-background-state-fixture';
import { FlattenedBackgroundStateProxy } from '../../../shared/types/background';

const flattenedBackgroundState = Object.values(
  sentryBackgroundStateFixture,
).reduce<FlattenedBackgroundStateProxy>((backgroundState: any, controllerState: any) => {
  return {
    ...backgroundState,
    ...controllerState,
  };
}, {} as FlattenedBackgroundStateProxy);

const fixture = {
  [AlertTypes.invalidCustomNetwork]: {
    state: 'CLOSED' as const,
    networkName: '',
  },
  activeTab: {
    origin: 'https://example.com',
  },
  DNS: {
    stage: 'UNINITIALIZED' as const,
    resolutions: null,
    error: null,
    warning: null,
    chainId: null,
    domainName: null,
  },
  gas: {
    customData: {
      price: null,
      limit: null,
    },
  },
  history: {
    mostRecentOverviewPage: '/home',
    redirectAfterDefaultPage: null,
  },
  send: {
    amountMode: 'INPUT' as const,
    currentTransactionUUID: '',
    disabledSwapAndSendNetworks: [],
    draftTransactions: {},
    eip1559support: false,
    gasEstimateIsLoading: false,
    gasIsSetInModal: false,
    gasPriceEstimate: '0x0',
    gasLimitMinimum: '0x5208',
    gasTotalForLayer1: '0x0',
    prevSwapAndSendInput: {},
    recipientMode: 'CONTACT_LIST' as const,
    recipientInput: '',
    selectedAccount: {
      address: '',
      balance: '0x0',
    },
    stage: 'INACTIVE' as const,
    swapsBlockedTokens: [],
  },
  confirmAlerts: {
    alerts: {},
    confirmed: {},
  },
  confirmTransaction: {
    txData: {},
    tokenData: {},
    tokenProps: {},
    fiatTransactionAmount: '',
    fiatTransactionFee: '',
    fiatTransactionTotal: '',
    ethTransactionAmount: '',
    ethTransactionFee: '',
    ethTransactionTotal: '',
    hexTransactionAmount: '',
    hexTransactionFee: '',
    hexTransactionTotal: '',
    nonce: '',
    maxValueMode: {},
  },
  swaps: {
    aggregatorMetadata: null,
    approveTxId: null,
    tradeTxId: null,
    balanceError: false,
    fetchingQuotes: false,
    fromToken: null,
    fromTokenInputValue: '',
    fromTokenError: null,
    isFeatureFlagLoaded: false,
    maxSlippage: 3,
    quotesFetchStartTime: null,
    reviewSwapClickedTimestamp: null,
    topAssets: {},
    toToken: null,
    customGas: {
      price: null,
      limit: null,
      loading: 'INITIAL' as const,
      priceEstimates: {},
      fallBackPrice: null,
    },
    currentSmartTransactionsError: '',
    swapsSTXLoading: false,
    transactionSettingsOpened: false,
    latestAddedTokenTo: '',
  },
  ramps: {
    buyableChains: [],
    isFetched: false,
  },
  bridge: {
    toChainId: null,
    fromToken: null,
    toToken: null,
    fromTokenInputValue: null,
    fromTokenExchangeRate: null,
    toTokenExchangeRate: null,
    toTokenUsdExchangeRate: null,
    fromTokenBalance: null,
    fromNativeBalance: null,
    sortOrder: SortOrder.COST_ASC,
    selectedQuote: null,
    wasTxDeclined: false,
    slippage: 0.005,
    txAlert: null,
  },
  localeMessages: {},
  smartAccounts: {
    toggleStates: {},
  },
  appState: {
    customNonceValue: '',
    isAccountMenuOpen: false,
    isNetworkMenuOpen: false,
    nextNonce: null,
    pendingTokens: {},
    welcomeScreenSeen: false,
    confirmationExchangeRates: {},
    shouldClose: false,
    menuOpen: false,
    modal: {
      open: false,
      modalState: {
        name: null,
        props: {},
      },
      previousModalState: {
        name: null,
      },
    },
    alertOpen: false,
    alertMessage: null,
    qrCodeData: null,
    networkDropdownOpen: false,
    importNftsModal: { open: false },
    showPermittedNetworkToastOpen: false,
    showIpfsModalOpen: false,
    showSupportDataConsentModal: false,
    keyringRemovalSnapModal: {
      snapName: '',
      result: 'none' as const,
    },
    showKeyringRemovalSnapModal: false,
    importTokensModalOpen: false,
    deprecatedNetworkModalOpen: false,
    accountDetail: {
      privateKey: '',
    },
    isLoading: false,
    isNftStillFetchingIndication: false,
    showNftDetectionEnablementToast: false,
    loadingMessage: null,
    scrollToBottom: true,
    warning: null,
    buyView: {},
    defaultHdPaths: {
      trezor: `m/44'/60'/0'/0`,
      oneKey: `m/44'/60'/0'/0`,
      ledger: `m/44'/60'/0'/0/0`,
      lattice: `m/44'/60'/0'/0`,
    },
    networksTabSelectedRpcUrl: '',
    requestAccountTabs: {},
    openMetaMaskTabs: {},
    currentWindowTab: {},
    showWhatsNewPopup: true,
    showTermsOfUsePopup: true,
    singleExceptions: {
      testKey: null,
    },
    gasLoadingAnimationIsShowing: false,
    smartTransactionsError: null,
    smartTransactionsErrorMessageDismissed: false,
    ledgerWebHidConnectedStatus: WebHIDConnectedStatuses.unknown,
    ledgerTransportStatus: HardwareTransportStates.none,
    showBasicFunctionalityModal: false,
    externalServicesOnboardingToggleState: true,
    newNftAddedMessage: '',
    removeNftMessage: '',
    newNetworkAddedName: '',
    newNetworkAddedConfigurationId: '',
    selectedNetworkConfigurationId: '',
    sendInputCurrencySwitched: false,
    newTokensImported: '',
    newTokensImportedError: '',
    onboardedInThisUISession: false,
    customTokenAmount: '',
    txId: null,
    accountDetailsAddress: '',
    showDeleteMetaMetricsDataModal: false,
    showDataDeletionErrorModal: false,
    snapsInstallPrivacyWarningShown: false,
    isAddingNewNetwork: false,
    isMultiRpcOnboarding: false,
    isAccessedFromDappConnectedSitePopover: false,
    errorInSettings: null,
    showNewSrpAddedToast: false,
    showPasswordChangeToast: null,
    showCopyAddressToast: false,
    showClaimSubmitToast: null,
    showConnectionsRemovedModal: false,
  },
  metamask: flattenedBackgroundState,
  unconnectedAccount: {
    state: 'CLOSED' as const,
  },
} as const satisfies MetaMaskReduxState;

export default fixture;
