export const STATUS_CONNECTED = 'STATUS_CONNECTED';
export const STATUS_CONNECTED_TO_ANOTHER_ACCOUNT =
  'STATUS_CONNECTED_TO_ANOTHER_ACCOUNT';
export const STATUS_NOT_CONNECTED = 'STATUS_NOT_CONNECTED';
export const STATUS_CONNECTED_TO_SNAP = 'STATUS_CONNECTED_TO_SNAP';
