const SURVEY_DATE = 'February 28 2024';
const SURVEY_GMT = 'GMT-0600';
const SURVEY_START_HOUR = '12:00:00';
const SURVEY_END_HOUR = '13:00:00';

const SURVEY_START_TIME = `${SURVEY_START_HOUR} ${SURVEY_GMT}`;
const SURVEY_END_TIME = `${SURVEY_END_HOUR} ${SURVEY_GMT}`;

export {
  SURVEY_DATE,
  SURVEY_GMT,
  SURVEY_START_HOUR,
  SURVEY_END_HOUR,
  SURVEY_START_TIME,
  SURVEY_END_TIME,
};
