const ZENDESK_URLS = {
  ACCOUNT_UPGRADE:
    'https://support.metamask.io/configure/accounts/what-is-a-smart-account',
  ADD_CUSTOM_TOKENS:
    'https://support.metamask.io/managing-my-tokens/custom-tokens/how-to-display-tokens-in-metamask/',
  ADD_SOLANA_ACCOUNTS:
    'https://support.metamask.io/configure/accounts/how-to-add-accounts-in-your-wallet/#solana-accounts',
  ADD_MISSING_ACCOUNTS:
    'https://support.metamask.io/managing-my-wallet/accounts-and-addresses/how-to-add-missing-accounts-after-restoring-with-secret-recovery-phrase/',
  BASIC_SAFETY:
    'https://support.metamask.io/privacy-and-security/basic-safety-and-security-tips-for-metamask/',
  CUSTOMIZE_NONCE:
    'https://support.metamask.io/transactions-and-gas/transactions/how-to-customize-a-transaction-nonce/',
  GAS_FEES: 'https://support.metamask.io/transactions-and-gas/gas-fees/',
  SWAPS_GAS_FEES:
    'https://support.metamask.io/token-swaps/user-guide-swaps/#gas-fees',
  HARDWARE_CONNECTION:
    'https://support.metamask.io/privacy-and-security/hardware-wallet-hub/',
  IMPORT_ACCOUNTS:
    'https://support.metamask.io/managing-my-wallet/accounts-and-addresses/how-to-import-an-account/',
  IMPORTED_ACCOUNTS:
    'https://support.metamask.io/managing-my-wallet/accounts-and-addresses/what-are-imported-accounts-/',
  INFURA_BLOCKAGE:
    'https://support.metamask.io/troubleshooting/why-infura-cannot-serve-certain-areas/',
  LEDGER_FIREFOX_U2F_GUIDE:
    'https://support.ledger.com/hc/en-us/articles/10371387758493-MetaMask-Firefox-Ledger-Integration-Issue?support=true',
  LEGACY_WEB3:
    'https://support.metamask.io/third-party-platforms-and-dapps/metamask-legacy-web3/',
  NFT_TOKENS:
    'https://support.metamask.io/nfts/nft-tokens-in-your-metamask-wallet/',
  PASSWORD_ARTICLE:
    'https://support.metamask.io/configure/wallet/passwords-and-metamask/',
  PASSWORD_AND_SRP_ARTICLE:
    'https://support.metamask.io/getting-started/user-guide-secret-recovery-phrase-password-and-private-keys/',
  RESET_ADD_MISSING_ACCOUNT:
    'https://support.metamask.io/configure/accounts/how-to-add-missing-accounts-after-restoring-with-secret-recovery-phrase/',
  RESET_DISPLAY_TOKENS:
    'https://support.metamask.io/manage-crypto/tokens/how-to-display-tokens-in-metamask/',
  RESET_IMPORT_AN_ACCOUNT:
    'https://support.metamask.io/start/how-to-import-an-account/',
  SECRET_RECOVERY_PHRASE:
    'https://support.metamask.io/privacy-and-security/what-is-a-secret-recovery-phrase-and-how-to-keep-your-crypto-wallet-secure/',
  NON_CUSTODIAL_WALLET:
    'https://support.metamask.io/getting-started/metamask-is-a-self-custodial-wallet/',
  SPEEDUP_CANCEL:
    'https://support.metamask.io/transactions-and-gas/transactions/how-to-speed-up-or-cancel-a-pending-transaction/',
  SUPPORT_URL: 'https://support.metamask.io',
  TOKEN_ALLOWANCE_WITH_SPENDING_CAP:
    'https://support.metamask.io/privacy-and-security/how-to-customize-token-approvals-with-a-spending-cap/',
  TOKEN_SAFETY_PRACTICES:
    'https://support.metamask.io/managing-my-tokens/token-safety-practices/',
  UNKNOWN_NETWORK:
    'https://support.metamask.io/networks-and-sidechains/managing-networks/the-risks-of-connecting-to-an-unknown-network/',
  USER_GUIDE_CUSTOM_NETWORKS:
    'https://support.metamask.io/networks-and-sidechains/managing-networks/user-guide-custom-networks-and-sidechains/',
  USER_GUIDE_DAPPS:
    'https://support.metamask.io/third-party-platforms-and-dapps/user-guide-dapps/',
  USER_GUIDE_GAS:
    'https://support.metamask.io/transactions-and-gas/gas-fees/user-guide-gas/',
  VERIFY_CUSTOM_NETWORK:
    'https://support.metamask.io/networks-and-sidechains/managing-networks/verifying-custom-network-information/',
  NETWORK_DEPRECATED:
    'https://support.metamask.io/networks-and-sidechains/eth-on-testnets/',
  SOLANA_ACCOUNTS:
    'https://support.metamask.io/configure/accounts/how-to-add-accounts-in-your-wallet/#solana-accounts',
};

export default ZENDESK_URLS;
