import type { Position, Order, PerpsMarketData } from '../controllers/types';

/**
 * Mock data for Perps UI development
 * Used for building UI while PerpsController is being migrated to core
 */

/**
 * Mock positions data
 * Includes various scenarios: long, short, with/without TP/SL, different leverage types
 */
export const mockPositions: Position[] = [
  {
    coin: 'ETH',
    size: '2.5',
    entryPrice: '2850.00',
    positionValue: '7125.00',
    unrealizedPnl: '375.00',
    marginUsed: '2375.00',
    leverage: {
      type: 'isolated',
      value: 3,
      rawUsd: '2375.00',
    },
    liquidationPrice: '2400.00',
    maxLeverage: 50,
    returnOnEquity: '15.79',
    cumulativeFunding: {
      allTime: '12.50',
      sinceOpen: '8.30',
      sinceChange: '0.00',
    },
    takeProfitPrice: '3200.00',
    stopLossPrice: '2600.00',
    takeProfitCount: 1,
    stopLossCount: 1,
  },
  {
    coin: 'BTC',
    size: '-0.5',
    entryPrice: '45000.00',
    positionValue: '22500.00',
    unrealizedPnl: '-250.00',
    marginUsed: '1500.00',
    leverage: {
      type: 'cross',
      value: 15,
    },
    liquidationPrice: '48000.00',
    maxLeverage: 50,
    returnOnEquity: '-16.67',
    cumulativeFunding: {
      allTime: '-5.20',
      sinceOpen: '-3.10',
      sinceChange: '0.00',
    },
    takeProfitPrice: undefined,
    stopLossPrice: '47000.00',
    takeProfitCount: 0,
    stopLossCount: 1,
  },
  {
    coin: 'SOL',
    size: '50.0',
    entryPrice: '95.00',
    positionValue: '4750.00',
    unrealizedPnl: '125.00',
    marginUsed: '475.00',
    leverage: {
      type: 'isolated',
      value: 10,
      rawUsd: '475.00',
    },
    liquidationPrice: '85.00',
    maxLeverage: 20,
    returnOnEquity: '26.32',
    cumulativeFunding: {
      allTime: '2.50',
      sinceOpen: '1.80',
      sinceChange: '0.00',
    },
    takeProfitPrice: undefined,
    stopLossPrice: undefined,
    takeProfitCount: 0,
    stopLossCount: 0,
  },
  {
    coin: 'ARB',
    size: '1000.0',
    entryPrice: '1.20',
    positionValue: '1200.00',
    unrealizedPnl: '-50.00',
    marginUsed: '120.00',
    leverage: {
      type: 'cross',
      value: 10,
    },
    liquidationPrice: '1.08',
    maxLeverage: 25,
    returnOnEquity: '-41.67',
    cumulativeFunding: {
      allTime: '-1.20',
      sinceOpen: '-0.80',
      sinceChange: '0.00',
    },
    takeProfitPrice: '1.50',
    stopLossPrice: undefined,
    takeProfitCount: 1,
    stopLossCount: 0,
  },
  {
    coin: 'POL',
    size: '-5000.0',
    entryPrice: '0.75',
    positionValue: '3750.00',
    unrealizedPnl: '100.00',
    marginUsed: '375.00',
    leverage: {
      type: 'isolated',
      value: 10,
      rawUsd: '375.00',
    },
    liquidationPrice: '0.80',
    maxLeverage: 20,
    returnOnEquity: '26.67',
    cumulativeFunding: {
      allTime: '3.50',
      sinceOpen: '2.20',
      sinceChange: '0.00',
    },
    takeProfitPrice: undefined,
    stopLossPrice: undefined,
    takeProfitCount: 0,
    stopLossCount: 0,
  },
];

/**
 * Mock orders data
 * Includes various order types: limit, market, with/without TP/SL, different statuses
 */
export const mockOrders: Order[] = [
  {
    orderId: 'order-001',
    symbol: 'ETH',
    side: 'buy',
    orderType: 'limit',
    size: '1.0',
    originalSize: '1.0',
    price: '3000.00',
    filledSize: '0',
    remainingSize: '1.0',
    status: 'open',
    timestamp: Date.now() - 3600000, // 1 hour ago
    takeProfitPrice: '3200.00',
    stopLossPrice: '2800.00',
    takeProfitOrderId: 'tp-order-001',
    stopLossOrderId: 'sl-order-001',
    reduceOnly: false,
  },
  {
    orderId: 'order-002',
    symbol: 'BTC',
    side: 'sell',
    orderType: 'limit',
    size: '0.2',
    originalSize: '0.2',
    price: '46000.00',
    filledSize: '0.1',
    remainingSize: '0.1',
    status: 'open',
    timestamp: Date.now() - 7200000, // 2 hours ago
    lastUpdated: Date.now() - 1800000, // 30 minutes ago
    reduceOnly: true,
  },
  {
    orderId: 'order-003',
    symbol: 'SOL',
    side: 'buy',
    orderType: 'market',
    size: '25.0',
    originalSize: '25.0',
    price: '0', // Market orders don't have a price
    filledSize: '0',
    remainingSize: '25.0',
    status: 'queued',
    timestamp: Date.now() - 300000, // 5 minutes ago
  },
  {
    orderId: 'order-004',
    symbol: 'ARB',
    side: 'sell',
    orderType: 'limit',
    size: '500.0',
    originalSize: '500.0',
    price: '1.15',
    filledSize: '0',
    remainingSize: '500.0',
    status: 'open',
    timestamp: Date.now() - 5400000, // 1.5 hours ago
    isTrigger: true,
    triggerPrice: '1.15',
    detailedOrderType: 'Take Profit Limit',
    takeProfitOrderId: 'tp-order-004',
  },
  {
    orderId: 'order-005',
    symbol: 'POL',
    side: 'buy',
    orderType: 'limit',
    size: '2000.0',
    originalSize: '2000.0',
    price: '0.70',
    filledSize: '0',
    remainingSize: '2000.0',
    status: 'open',
    timestamp: Date.now() - 900000, // 15 minutes ago
    isTrigger: true,
    triggerPrice: '0.70',
    detailedOrderType: 'Stop Market',
    stopLossOrderId: 'sl-order-005',
  },
  {
    orderId: 'order-006',
    symbol: 'ETH',
    side: 'sell',
    orderType: 'limit',
    size: '0.5',
    originalSize: '0.5',
    price: '2950.00',
    filledSize: '0.5',
    remainingSize: '0',
    status: 'filled',
    timestamp: Date.now() - 10800000, // 3 hours ago
    lastUpdated: Date.now() - 10800000,
  },
];

/**
 * Mock crypto markets data (main DEX, no marketType)
 * Standard cryptocurrency perpetual markets
 */
export const mockCryptoMarkets: PerpsMarketData[] = [
  {
    symbol: 'BTC',
    name: 'Bitcoin',
    maxLeverage: '50x',
    price: '$45,250.00',
    change24h: '+$1,250.00',
    change24hPercent: '+2.84%',
    volume: '$1.2B',
    openInterest: '$2.5B',
    nextFundingTime: Date.now() + 3600000, // 1 hour from now
    fundingIntervalHours: 8,
    fundingRate: 0.0001,
    marketSource: undefined,
    marketType: undefined, // Crypto markets have no marketType
  },
  {
    symbol: 'ETH',
    name: 'Ethereum',
    maxLeverage: '50x',
    price: '$3,025.50',
    change24h: '+$75.50',
    change24hPercent: '+2.56%',
    volume: '$850M',
    openInterest: '$1.8B',
    nextFundingTime: Date.now() + 3600000,
    fundingIntervalHours: 8,
    fundingRate: 0.00008,
    marketSource: undefined,
    marketType: undefined,
  },
  {
    symbol: 'SOL',
    name: 'Solana',
    maxLeverage: '20x',
    price: '$97.25',
    change24h: '-$2.25',
    change24hPercent: '-2.26%',
    volume: '$120M',
    openInterest: '$450M',
    nextFundingTime: Date.now() + 3600000,
    fundingIntervalHours: 8,
    fundingRate: -0.00005,
    marketSource: undefined,
    marketType: undefined,
  },
  {
    symbol: 'ARB',
    name: 'Arbitrum',
    maxLeverage: '25x',
    price: '$1.15',
    change24h: '+$0.05',
    change24hPercent: '+4.55%',
    volume: '$45M',
    openInterest: '$180M',
    nextFundingTime: Date.now() + 3600000,
    fundingIntervalHours: 8,
    fundingRate: 0.00012,
    marketSource: undefined,
    marketType: undefined,
  },
  {
    symbol: 'POL',
    name: 'Polygon',
    maxLeverage: '20x',
    price: '$0.77',
    change24h: '+$0.02',
    change24hPercent: '+2.67%',
    volume: '$35M',
    openInterest: '$95M',
    nextFundingTime: Date.now() + 3600000,
    fundingIntervalHours: 8,
    fundingRate: 0.00006,
    marketSource: undefined,
    marketType: undefined,
  },
  {
    symbol: 'AVAX',
    name: 'Avalanche',
    maxLeverage: '20x',
    price: '$38.50',
    change24h: '-$1.20',
    change24hPercent: '-3.02%',
    volume: '$28M',
    openInterest: '$120M',
    nextFundingTime: Date.now() + 3600000,
    fundingIntervalHours: 8,
    fundingRate: -0.00003,
    marketSource: undefined,
    marketType: undefined,
  },
  {
    symbol: 'LINK',
    name: 'Chainlink',
    maxLeverage: '25x',
    price: '$14.85',
    change24h: '+$0.35',
    change24hPercent: '+2.41%',
    volume: '$22M',
    openInterest: '$85M',
    nextFundingTime: Date.now() + 3600000,
    fundingIntervalHours: 8,
    fundingRate: 0.00009,
    marketSource: undefined,
    marketType: undefined,
  },
  {
    symbol: 'UNI',
    name: 'Uniswap',
    maxLeverage: '25x',
    price: '$6.25',
    change24h: '-$0.15',
    change24hPercent: '-2.34%',
    volume: '$18M',
    openInterest: '$65M',
    nextFundingTime: Date.now() + 3600000,
    fundingIntervalHours: 8,
    fundingRate: -0.00004,
    marketSource: undefined,
    marketType: undefined,
  },
];

/**
 * Mock HIP-3 markets data
 * Includes equity (stocks), commodity, and forex markets from HIP-3 DEXs
 */
export const mockHip3Markets: PerpsMarketData[] = [
  // Equity markets (stocks)
  {
    symbol: 'flx:TSLA',
    name: 'Tesla',
    maxLeverage: '10x',
    price: '$245.50',
    change24h: '+$5.20',
    change24hPercent: '+2.17%',
    volume: '$125M',
    openInterest: '$380M',
    nextFundingTime: Date.now() + 3600000,
    fundingIntervalHours: 8,
    fundingRate: 0.00015,
    marketSource: 'flx',
    marketType: 'equity',
  },
  {
    symbol: 'flx:AAPL',
    name: 'Apple',
    maxLeverage: '10x',
    price: '$178.25',
    change24h: '-$2.15',
    change24hPercent: '-1.19%',
    volume: '$95M',
    openInterest: '$420M',
    nextFundingTime: Date.now() + 3600000,
    fundingIntervalHours: 8,
    fundingRate: 0.00012,
    marketSource: 'flx',
    marketType: 'equity',
  },
  {
    symbol: 'flx:MSFT',
    name: 'Microsoft',
    maxLeverage: '10x',
    price: '$385.75',
    change24h: '+$8.50',
    change24hPercent: '+2.25%',
    volume: '$88M',
    openInterest: '$350M',
    nextFundingTime: Date.now() + 3600000,
    fundingIntervalHours: 8,
    fundingRate: 0.0001,
    marketSource: 'flx',
    marketType: 'equity',
  },
  {
    symbol: 'flx:NVDA',
    name: 'NVIDIA',
    maxLeverage: '10x',
    price: '$485.20',
    change24h: '+$12.80',
    change24hPercent: '+2.71%',
    volume: '$145M',
    openInterest: '$520M',
    nextFundingTime: Date.now() + 3600000,
    fundingIntervalHours: 8,
    fundingRate: 0.00018,
    marketSource: 'flx',
    marketType: 'equity',
  },
  {
    symbol: 'flx:AMZN',
    name: 'Amazon',
    maxLeverage: '10x',
    price: '$152.80',
    change24h: '-$1.20',
    change24hPercent: '-0.78%',
    volume: '$72M',
    openInterest: '$280M',
    nextFundingTime: Date.now() + 3600000,
    fundingIntervalHours: 8,
    fundingRate: 0.00011,
    marketSource: 'flx',
    marketType: 'equity',
  },
  {
    symbol: 'flx:GOOGL',
    name: 'Alphabet',
    maxLeverage: '10x',
    price: '$142.50',
    change24h: '+$3.25',
    change24hPercent: '+2.33%',
    volume: '$65M',
    openInterest: '$240M',
    nextFundingTime: Date.now() + 3600000,
    fundingIntervalHours: 8,
    fundingRate: 0.00009,
    marketSource: 'flx',
    marketType: 'equity',
  },
  // Commodity markets
  {
    symbol: 'flx:GOLD',
    name: 'Gold',
    maxLeverage: '20x',
    price: '$2,045.50',
    change24h: '+$15.25',
    change24hPercent: '+0.75%',
    volume: '$45M',
    openInterest: '$180M',
    nextFundingTime: Date.now() + 3600000,
    fundingIntervalHours: 8,
    fundingRate: 0.00008,
    marketSource: 'flx',
    marketType: 'commodity',
  },
  {
    symbol: 'flx:SILVER',
    name: 'Silver',
    maxLeverage: '20x',
    price: '$24.85',
    change24h: '-$0.35',
    change24hPercent: '-1.39%',
    volume: '$28M',
    openInterest: '$95M',
    nextFundingTime: Date.now() + 3600000,
    fundingIntervalHours: 8,
    fundingRate: 0.00006,
    marketSource: 'flx',
    marketType: 'commodity',
  },
  {
    symbol: 'flx:OIL',
    name: 'Crude Oil',
    maxLeverage: '20x',
    price: '$78.25',
    change24h: '+$1.50',
    change24hPercent: '+1.95%',
    volume: '$35M',
    openInterest: '$120M',
    nextFundingTime: Date.now() + 3600000,
    fundingIntervalHours: 8,
    fundingRate: 0.0001,
    marketSource: 'flx',
    marketType: 'commodity',
  },
  {
    symbol: 'flx:COPPER',
    name: 'Copper',
    maxLeverage: '20x',
    price: '$4.15',
    change24h: '+$0.08',
    change24hPercent: '+1.96%',
    volume: '$18M',
    openInterest: '$65M',
    nextFundingTime: Date.now() + 3600000,
    fundingIntervalHours: 8,
    fundingRate: 0.00007,
    marketSource: 'flx',
    marketType: 'commodity',
  },
  // Forex markets
  {
    symbol: 'flx:EURUSD',
    name: 'EUR/USD',
    maxLeverage: '50x',
    price: '$1.0850',
    change24h: '+$0.0025',
    change24hPercent: '+0.23%',
    volume: '$55M',
    openInterest: '$220M',
    nextFundingTime: Date.now() + 3600000,
    fundingIntervalHours: 8,
    fundingRate: 0.00005,
    marketSource: 'flx',
    marketType: 'forex',
  },
  {
    symbol: 'flx:GBPUSD',
    name: 'GBP/USD',
    maxLeverage: '50x',
    price: '$1.2650',
    change24h: '-$0.0035',
    change24hPercent: '-0.28%',
    volume: '$42M',
    openInterest: '$165M',
    nextFundingTime: Date.now() + 3600000,
    fundingIntervalHours: 8,
    fundingRate: 0.00004,
    marketSource: 'flx',
    marketType: 'forex',
  },
  {
    symbol: 'flx:USDJPY',
    name: 'USD/JPY',
    maxLeverage: '50x',
    price: '$149.85',
    change24h: '+$0.45',
    change24hPercent: '+0.30%',
    volume: '$38M',
    openInterest: '$145M',
    nextFundingTime: Date.now() + 3600000,
    fundingIntervalHours: 8,
    fundingRate: 0.00006,
    marketSource: 'flx',
    marketType: 'forex',
  },
  {
    symbol: 'flx:AUDUSD',
    name: 'AUD/USD',
    maxLeverage: '50x',
    price: '$0.6525',
    change24h: '-$0.0015',
    change24hPercent: '-0.23%',
    volume: '$25M',
    openInterest: '$95M',
    nextFundingTime: Date.now() + 3600000,
    fundingIntervalHours: 8,
    fundingRate: 0.00005,
    marketSource: 'flx',
    marketType: 'forex',
  },
  // Additional equity markets from different DEX
  {
    symbol: 'xyz:SPY',
    name: 'SPDR S&P 500',
    maxLeverage: '10x',
    price: '$445.75',
    change24h: '+$3.25',
    change24hPercent: '+0.73%',
    volume: '$85M',
    openInterest: '$320M',
    nextFundingTime: Date.now() + 3600000,
    fundingIntervalHours: 8,
    fundingRate: 0.0001,
    marketSource: 'xyz',
    marketType: 'equity',
  },
  {
    symbol: 'xyz:QQQ',
    name: 'Invesco QQQ',
    maxLeverage: '10x',
    price: '$375.50',
    change24h: '+$5.20',
    change24hPercent: '+1.40%',
    volume: '$68M',
    openInterest: '$280M',
    nextFundingTime: Date.now() + 3600000,
    fundingIntervalHours: 8,
    fundingRate: 0.00012,
    marketSource: 'xyz',
    marketType: 'equity',
  },
];
