/**
 * Mock data for Perps UI development
 * Used for building UI while PerpsController is being migrated to core
 *
 * @deprecated These mocks are being migrated to the controller layer.
 * Once integration is complete, import from:
 * `app/scripts/controllers/perps/mocks`
 */

import {
  FillType,
  PerpsOrderTransactionStatus,
  PerpsOrderTransactionStatusType,
} from './types/transactionHistory';
import type { PerpsTransaction } from './types';
import {
  AccountState,
  Order,
  PerpsMarketData,
  Position,
} from '@metamask/perps-controller';

/**
 * Mock account state data
 * Represents the user's perps trading account balance and P&L
 */
export const mockAccountState: AccountState = {
  totalBalance: '15250.00',
  availableBalance: '10125.00',
  marginUsed: '5125.00',
  unrealizedPnl: '375.00',
  returnOnEquity: '7.32',
};

/**
 * Mock positions data
 * Includes various scenarios: long, short, with/without TP/SL, different leverage types
 */
export const mockPositions: Position[] = [
  {
    symbol: 'ETH',
    size: '2.5',
    entryPrice: '2850.00',
    positionValue: '7125.00',
    unrealizedPnl: '375.00',
    marginUsed: '2375.00',
    leverage: {
      type: 'isolated',
      value: 3,
      rawUsd: '2375.00',
    },
    liquidationPrice: '2400.00',
    maxLeverage: 20,
    returnOnEquity: '15.79',
    cumulativeFunding: {
      allTime: '12.50',
      sinceOpen: '8.30',
      sinceChange: '0.00',
    },
    takeProfitPrice: '3200.00',
    stopLossPrice: '2600.00',
    takeProfitCount: 1,
    stopLossCount: 1,
  },
  {
    symbol: 'BTC',
    size: '-0.5',
    entryPrice: '45000.00',
    positionValue: '22500.00',
    unrealizedPnl: '-250.00',
    marginUsed: '1500.00',
    leverage: {
      type: 'cross',
      value: 15,
    },
    liquidationPrice: '48000.00',
    maxLeverage: 20,
    returnOnEquity: '-16.67',
    cumulativeFunding: {
      allTime: '-5.20',
      sinceOpen: '-3.10',
      sinceChange: '0.00',
    },
    takeProfitPrice: undefined,
    stopLossPrice: '47000.00',
    takeProfitCount: 0,
    stopLossCount: 1,
  },
  {
    symbol: 'SOL',
    size: '50.0',
    entryPrice: '95.00',
    positionValue: '4750.00',
    unrealizedPnl: '125.00',
    marginUsed: '475.00',
    leverage: {
      type: 'isolated',
      value: 10,
      rawUsd: '475.00',
    },
    liquidationPrice: '85.00',
    maxLeverage: 20,
    returnOnEquity: '26.32',
    cumulativeFunding: {
      allTime: '2.50',
      sinceOpen: '1.80',
      sinceChange: '0.00',
    },
    takeProfitPrice: undefined,
    stopLossPrice: undefined,
    takeProfitCount: 0,
    stopLossCount: 0,
  },
  {
    symbol: 'ARB',
    size: '1000.0',
    entryPrice: '1.20',
    positionValue: '1200.00',
    unrealizedPnl: '-50.00',
    marginUsed: '120.00',
    leverage: {
      type: 'cross',
      value: 10,
    },
    liquidationPrice: '1.08',
    maxLeverage: 20,
    returnOnEquity: '-41.67',
    cumulativeFunding: {
      allTime: '-1.20',
      sinceOpen: '-0.80',
      sinceChange: '0.00',
    },
    takeProfitPrice: '1.50',
    stopLossPrice: undefined,
    takeProfitCount: 1,
    stopLossCount: 0,
  },
  {
    symbol: 'POL',
    size: '-5000.0',
    entryPrice: '0.75',
    positionValue: '3750.00',
    unrealizedPnl: '100.00',
    marginUsed: '375.00',
    leverage: {
      type: 'isolated',
      value: 10,
      rawUsd: '375.00',
    },
    liquidationPrice: '0.80',
    maxLeverage: 20,
    returnOnEquity: '26.67',
    cumulativeFunding: {
      allTime: '3.50',
      sinceOpen: '2.20',
      sinceChange: '0.00',
    },
    takeProfitPrice: undefined,
    stopLossPrice: undefined,
    takeProfitCount: 0,
    stopLossCount: 0,
  },
  // HIP-3 Equity positions (stocks)
  {
    symbol: 'xyz:TSLA',
    size: '10.0',
    entryPrice: '240.00',
    positionValue: '2400.00',
    unrealizedPnl: '55.00',
    marginUsed: '240.00',
    leverage: {
      type: 'isolated',
      value: 10,
      rawUsd: '240.00',
    },
    liquidationPrice: '216.00',
    maxLeverage: 10,
    returnOnEquity: '22.92',
    cumulativeFunding: {
      allTime: '4.80',
      sinceOpen: '2.40',
      sinceChange: '0.00',
    },
    takeProfitPrice: '280.00',
    stopLossPrice: '220.00',
    takeProfitCount: 1,
    stopLossCount: 1,
  },
  {
    symbol: 'xyz:NVDA',
    size: '-5.0',
    entryPrice: '480.00',
    positionValue: '2400.00',
    unrealizedPnl: '-25.00',
    marginUsed: '240.00',
    leverage: {
      type: 'cross',
      value: 10,
    },
    liquidationPrice: '528.00',
    maxLeverage: 10,
    returnOnEquity: '-10.42',
    cumulativeFunding: {
      allTime: '-2.10',
      sinceOpen: '-1.50',
      sinceChange: '0.00',
    },
    takeProfitPrice: '420.00',
    stopLossPrice: undefined,
    takeProfitCount: 1,
    stopLossCount: 0,
  },
  // HIP-3 Commodity position
  {
    symbol: 'xyz:GOLD',
    size: '2.0',
    entryPrice: '2030.00',
    positionValue: '4060.00',
    unrealizedPnl: '31.00',
    marginUsed: '203.00',
    leverage: {
      type: 'isolated',
      value: 20,
      rawUsd: '203.00',
    },
    liquidationPrice: '1930.00',
    maxLeverage: 20,
    returnOnEquity: '15.27',
    cumulativeFunding: {
      allTime: '1.20',
      sinceOpen: '0.80',
      sinceChange: '0.00',
    },
    takeProfitPrice: undefined,
    stopLossPrice: '1980.00',
    takeProfitCount: 0,
    stopLossCount: 1,
  },
  // HIP-3 Forex position
  {
    symbol: 'xyz:EUR',
    size: '50000.0',
    entryPrice: '1.0820',
    positionValue: '54100.00',
    unrealizedPnl: '150.00',
    marginUsed: '1082.00',
    leverage: {
      type: 'cross',
      value: 50,
    },
    liquidationPrice: '1.0600',
    maxLeverage: 20,
    returnOnEquity: '13.86',
    cumulativeFunding: {
      allTime: '8.50',
      sinceOpen: '5.20',
      sinceChange: '0.00',
    },
    takeProfitPrice: '1.0950',
    stopLossPrice: '1.0750',
    takeProfitCount: 1,
    stopLossCount: 1,
  },
];

/**
 * Mock orders data
 * Includes various order types: limit, market, with/without TP/SL, different statuses
 */
export const mockOrders: Order[] = [
  {
    orderId: 'order-001',
    symbol: 'ETH',
    side: 'buy',
    orderType: 'limit',
    size: '1.0',
    originalSize: '1.0',
    price: '3000.00',
    filledSize: '0',
    remainingSize: '1.0',
    status: 'open',
    timestamp: Date.now() - 3600000, // 1 hour ago
    takeProfitPrice: '3200.00',
    stopLossPrice: '2800.00',
    takeProfitOrderId: 'tp-order-001',
    stopLossOrderId: 'sl-order-001',
    reduceOnly: false,
  },
  {
    orderId: 'order-002',
    symbol: 'BTC',
    side: 'sell',
    orderType: 'limit',
    size: '0.2',
    originalSize: '0.2',
    price: '46000.00',
    filledSize: '0.1',
    remainingSize: '0.1',
    status: 'open',
    timestamp: Date.now() - 7200000, // 2 hours ago
    lastUpdated: Date.now() - 1800000, // 30 minutes ago
    reduceOnly: true,
  },
  {
    orderId: 'order-003',
    symbol: 'SOL',
    side: 'buy',
    orderType: 'market',
    size: '25.0',
    originalSize: '25.0',
    price: '0', // Market orders don't have a price
    filledSize: '0',
    remainingSize: '25.0',
    status: 'queued',
    timestamp: Date.now() - 300000, // 5 minutes ago
  },
  {
    orderId: 'order-004',
    symbol: 'ARB',
    side: 'sell',
    orderType: 'limit',
    size: '500.0',
    originalSize: '500.0',
    price: '1.15',
    filledSize: '0',
    remainingSize: '500.0',
    status: 'open',
    timestamp: Date.now() - 5400000, // 1.5 hours ago
    isTrigger: true,
    triggerPrice: '1.15',
    detailedOrderType: 'Take Profit Limit',
    takeProfitOrderId: 'tp-order-004',
  },
  {
    orderId: 'order-005',
    symbol: 'POL',
    side: 'buy',
    orderType: 'limit',
    size: '2000.0',
    originalSize: '2000.0',
    price: '0.70',
    filledSize: '0',
    remainingSize: '2000.0',
    status: 'open',
    timestamp: Date.now() - 900000, // 15 minutes ago
    isTrigger: true,
    triggerPrice: '0.70',
    detailedOrderType: 'Stop Market',
    stopLossOrderId: 'sl-order-005',
  },
  {
    orderId: 'order-006',
    symbol: 'ETH',
    side: 'sell',
    orderType: 'limit',
    size: '0.5',
    originalSize: '0.5',
    price: '2950.00',
    filledSize: '0.5',
    remainingSize: '0',
    status: 'filled',
    timestamp: Date.now() - 10800000, // 3 hours ago
    lastUpdated: Date.now() - 10800000,
  },
  // HIP-3 Equity orders (stocks)
  {
    orderId: 'order-007',
    symbol: 'xyz:AAPL',
    side: 'buy',
    orderType: 'limit',
    size: '15.0',
    originalSize: '15.0',
    price: '175.00',
    filledSize: '0',
    remainingSize: '15.0',
    status: 'open',
    timestamp: Date.now() - 1800000, // 30 minutes ago
    takeProfitPrice: '190.00',
    stopLossPrice: '165.00',
    takeProfitOrderId: 'tp-order-007',
    stopLossOrderId: 'sl-order-007',
    reduceOnly: false,
  },
  {
    orderId: 'order-008',
    symbol: 'xyz:MSFT',
    side: 'sell',
    orderType: 'limit',
    size: '8.0',
    originalSize: '8.0',
    price: '390.00',
    filledSize: '0',
    remainingSize: '8.0',
    status: 'open',
    timestamp: Date.now() - 2400000, // 40 minutes ago
    reduceOnly: true,
  },
  // HIP-3 Commodity order
  {
    orderId: 'order-009',
    symbol: 'xyz:CL',
    side: 'buy',
    orderType: 'limit',
    size: '100.0',
    originalSize: '100.0',
    price: '76.50',
    filledSize: '0',
    remainingSize: '100.0',
    status: 'open',
    timestamp: Date.now() - 600000, // 10 minutes ago
  },
];

/**
 * Mock crypto markets data (main DEX, no marketType)
 * Standard cryptocurrency perpetual markets
 */
export const mockCryptoMarkets: PerpsMarketData[] = [
  {
    symbol: 'BTC',
    name: 'Bitcoin',
    maxLeverage: '20x',
    price: '$45,250.00',
    change24h: '+$1,250.00',
    change24hPercent: '+2.84%',
    volume: '$1.2B',
    openInterest: '$2.5B',
    nextFundingTime: Date.now() + 3600000, // 1 hour from now
    fundingIntervalHours: 8,
    fundingRate: 0.0001,
    marketSource: undefined,
    marketType: undefined, // Crypto markets have no marketType
  },
  {
    symbol: 'ETH',
    name: 'Ethereum',
    maxLeverage: '20x',
    price: '$3,025.50',
    change24h: '+$75.50',
    change24hPercent: '+2.56%',
    volume: '$850M',
    openInterest: '$1.8B',
    nextFundingTime: Date.now() + 3600000,
    fundingIntervalHours: 8,
    fundingRate: 0.00008,
    marketSource: undefined,
    marketType: undefined,
  },
  {
    symbol: 'SOL',
    name: 'Solana',
    maxLeverage: '20x',
    price: '$97.25',
    change24h: '-$2.25',
    change24hPercent: '-2.26%',
    volume: '$120M',
    openInterest: '$450M',
    nextFundingTime: Date.now() + 3600000,
    fundingIntervalHours: 8,
    fundingRate: -0.00005,
    marketSource: undefined,
    marketType: undefined,
  },
  {
    symbol: 'ARB',
    name: 'Arbitrum',
    maxLeverage: '20x',
    price: '$1.15',
    change24h: '+$0.05',
    change24hPercent: '+4.55%',
    volume: '$45M',
    openInterest: '$180M',
    nextFundingTime: Date.now() + 3600000,
    fundingIntervalHours: 8,
    fundingRate: 0.00012,
    marketSource: undefined,
    marketType: undefined,
  },
  {
    symbol: 'POL',
    name: 'Polygon',
    maxLeverage: '20x',
    price: '$0.77',
    change24h: '+$0.02',
    change24hPercent: '+2.67%',
    volume: '$35M',
    openInterest: '$95M',
    nextFundingTime: Date.now() + 3600000,
    fundingIntervalHours: 8,
    fundingRate: 0.00006,
    marketSource: undefined,
    marketType: undefined,
  },
  {
    symbol: 'AVAX',
    name: 'Avalanche',
    maxLeverage: '20x',
    price: '$38.50',
    change24h: '-$1.20',
    change24hPercent: '-3.02%',
    volume: '$28M',
    openInterest: '$120M',
    nextFundingTime: Date.now() + 3600000,
    fundingIntervalHours: 8,
    fundingRate: -0.00003,
    marketSource: undefined,
    marketType: undefined,
  },
  {
    symbol: 'LINK',
    name: 'Chainlink',
    maxLeverage: '20x',
    price: '$14.85',
    change24h: '+$0.35',
    change24hPercent: '+2.41%',
    volume: '$22M',
    openInterest: '$85M',
    nextFundingTime: Date.now() + 3600000,
    fundingIntervalHours: 8,
    fundingRate: 0.00009,
    marketSource: undefined,
    marketType: undefined,
  },
  {
    symbol: 'UNI',
    name: 'Uniswap',
    maxLeverage: '20x',
    price: '$6.25',
    change24h: '-$0.15',
    change24hPercent: '-2.34%',
    volume: '$18M',
    openInterest: '$65M',
    nextFundingTime: Date.now() + 3600000,
    fundingIntervalHours: 8,
    fundingRate: -0.00004,
    marketSource: undefined,
    marketType: undefined,
  },
];

/**
 * Mock HIP-3 markets data
 * Includes equity (stocks), commodity, and forex markets from HIP-3 DEXs
 */
export const mockHip3Markets: PerpsMarketData[] = [
  // Equity markets (stocks)
  {
    symbol: 'xyz:TSLA',
    name: 'Tesla',
    maxLeverage: '10x',
    price: '$245.50',
    change24h: '+$5.20',
    change24hPercent: '+2.17%',
    volume: '$125M',
    openInterest: '$380M',
    nextFundingTime: Date.now() + 3600000,
    fundingIntervalHours: 8,
    fundingRate: 0.00015,
    marketSource: 'xyz',
    marketType: 'equity',
  },
  {
    symbol: 'xyz:AAPL',
    name: 'Apple',
    maxLeverage: '10x',
    price: '$178.25',
    change24h: '-$2.15',
    change24hPercent: '-1.19%',
    volume: '$95M',
    openInterest: '$420M',
    nextFundingTime: Date.now() + 3600000,
    fundingIntervalHours: 8,
    fundingRate: 0.00012,
    marketSource: 'xyz',
    marketType: 'equity',
  },
  {
    symbol: 'xyz:MSFT',
    name: 'Microsoft',
    maxLeverage: '10x',
    price: '$385.75',
    change24h: '+$8.50',
    change24hPercent: '+2.25%',
    volume: '$88M',
    openInterest: '$350M',
    nextFundingTime: Date.now() + 3600000,
    fundingIntervalHours: 8,
    fundingRate: 0.0001,
    marketSource: 'xyz',
    marketType: 'equity',
  },
  {
    symbol: 'xyz:NVDA',
    name: 'NVIDIA',
    maxLeverage: '10x',
    price: '$485.20',
    change24h: '+$12.80',
    change24hPercent: '+2.71%',
    volume: '$145M',
    openInterest: '$520M',
    nextFundingTime: Date.now() + 3600000,
    fundingIntervalHours: 8,
    fundingRate: 0.00018,
    marketSource: 'xyz',
    marketType: 'equity',
  },
  {
    symbol: 'xyz:AMZN',
    name: 'Amazon',
    maxLeverage: '10x',
    price: '$152.80',
    change24h: '-$1.20',
    change24hPercent: '-0.78%',
    volume: '$72M',
    openInterest: '$280M',
    nextFundingTime: Date.now() + 3600000,
    fundingIntervalHours: 8,
    fundingRate: 0.00011,
    marketSource: 'xyz',
    marketType: 'equity',
  },
  {
    symbol: 'xyz:GOOGL',
    name: 'Alphabet',
    maxLeverage: '10x',
    price: '$142.50',
    change24h: '+$3.25',
    change24hPercent: '+2.33%',
    volume: '$65M',
    openInterest: '$240M',
    nextFundingTime: Date.now() + 3600000,
    fundingIntervalHours: 8,
    fundingRate: 0.00009,
    marketSource: 'xyz',
    marketType: 'equity',
  },
  // Commodity markets
  {
    symbol: 'xyz:GOLD',
    name: 'Gold',
    maxLeverage: '20x',
    price: '$2,045.50',
    change24h: '+$15.25',
    change24hPercent: '+0.75%',
    volume: '$45M',
    openInterest: '$180M',
    nextFundingTime: Date.now() + 3600000,
    fundingIntervalHours: 8,
    fundingRate: 0.00008,
    marketSource: 'xyz',
    marketType: 'commodity',
  },
  {
    symbol: 'xyz:SILVER',
    name: 'Silver',
    maxLeverage: '20x',
    price: '$24.85',
    change24h: '-$0.35',
    change24hPercent: '-1.39%',
    volume: '$28M',
    openInterest: '$95M',
    nextFundingTime: Date.now() + 3600000,
    fundingIntervalHours: 8,
    fundingRate: 0.00006,
    marketSource: 'xyz',
    marketType: 'commodity',
  },
  {
    symbol: 'xyz:CL',
    name: 'Crude Oil',
    maxLeverage: '20x',
    price: '$78.25',
    change24h: '+$1.50',
    change24hPercent: '+1.95%',
    volume: '$35M',
    openInterest: '$120M',
    nextFundingTime: Date.now() + 3600000,
    fundingIntervalHours: 8,
    fundingRate: 0.0001,
    marketSource: 'xyz',
    marketType: 'commodity',
  },
];

/**
 * Mock transactions data
 * Includes trades, orders, funding payments, and deposits/withdrawals
 */
export const mockTransactions: PerpsTransaction[] = [
  // Recent trades
  {
    id: 'tx-001',
    type: 'trade',
    category: 'position_open',
    symbol: 'ETH',
    title: 'Opened long',
    subtitle: '2.5 ETH @ $2,850.00',
    timestamp: Date.now() - 3600000, // 1 hour ago
    fill: {
      shortTitle: 'Opened long',
      amount: '+$7,125.00',
      amountNumber: 7125,
      isPositive: true,
      size: '2.5',
      entryPrice: '2850.00',
      points: '0',
      pnl: '0',
      fee: '7.13',
      action: 'Opened',
      feeToken: 'USDC',
      fillType: FillType.Standard,
    },
  },
  {
    id: 'tx-002',
    type: 'trade',
    category: 'position_close',
    symbol: 'BTC',
    title: 'Closed short',
    subtitle: '0.5 BTC @ $45,250.00',
    timestamp: Date.now() - 7200000, // 2 hours ago
    fill: {
      shortTitle: 'Closed short',
      amount: '+$125.00',
      amountNumber: 125,
      isPositive: true,
      size: '0.5',
      entryPrice: '45250.00',
      points: '0',
      pnl: '+125.00',
      fee: '22.63',
      action: 'Closed',
      feeToken: 'USDC',
      fillType: FillType.Standard,
    },
  },
  {
    id: 'tx-002b',
    type: 'trade',
    category: 'position_close',
    symbol: 'SOL',
    title: 'Closed long',
    subtitle: '15 SOL @ $92.50',
    timestamp: Date.now() - 9000000, // 2.5 hours ago
    fill: {
      shortTitle: 'Closed long',
      amount: '-$45.50',
      amountNumber: -45.5,
      isPositive: false,
      size: '15',
      entryPrice: '92.50',
      points: '0',
      pnl: '-45.50',
      fee: '1.39',
      action: 'Closed',
      feeToken: 'USDC',
      fillType: FillType.Standard,
    },
  },
  {
    id: 'tx-003',
    type: 'funding',
    category: 'funding_fee',
    symbol: 'ETH',
    title: 'Received funding fee',
    subtitle: 'ETH',
    timestamp: Date.now() - 10800000, // 3 hours ago
    fundingAmount: {
      isPositive: true,
      fee: '+8.30',
      feeNumber: 8.3,
      rate: '0.0001',
    },
  },
  {
    id: 'tx-004',
    type: 'order',
    category: 'limit_order',
    symbol: 'SOL',
    title: 'Limit long',
    subtitle: '25 SOL @ $95.00',
    timestamp: Date.now() - 14400000, // 4 hours ago
    order: {
      text: PerpsOrderTransactionStatus.Open,
      statusType: PerpsOrderTransactionStatusType.Pending,
      type: 'limit',
      size: '$2,375.00',
      limitPrice: '95.00',
      filled: '0%',
    },
  },
  {
    id: 'tx-004b',
    type: 'order',
    category: 'limit_order',
    symbol: 'BTC',
    title: 'Market close short',
    subtitle: '0.1 BTC @ $45,000.00',
    timestamp: Date.now() - 16200000, // 4.5 hours ago
    order: {
      text: PerpsOrderTransactionStatus.Filled,
      statusType: PerpsOrderTransactionStatusType.Filled,
      type: 'market',
      size: '$4,500.00',
      limitPrice: '45000.00',
      filled: '100%',
    },
  },
  {
    id: 'tx-004c',
    type: 'order',
    category: 'limit_order',
    symbol: 'ARB',
    title: 'Stop market close long',
    subtitle: '500 ARB @ $1.10',
    timestamp: Date.now() - 18000000, // 5 hours ago
    order: {
      text: PerpsOrderTransactionStatus.Canceled,
      statusType: PerpsOrderTransactionStatusType.Canceled,
      type: 'market',
      size: '$550.00',
      limitPrice: '1.10',
      filled: '0%',
    },
  },
  {
    id: 'tx-004d',
    type: 'order',
    category: 'limit_order',
    symbol: 'ETH',
    title: 'Market long',
    subtitle: '1.5 ETH @ $2,900.00',
    timestamp: Date.now() - 19800000, // 5.5 hours ago
    order: {
      text: PerpsOrderTransactionStatus.Queued,
      statusType: PerpsOrderTransactionStatusType.Pending,
      type: 'market',
      size: '$4,350.00',
      limitPrice: '2900.00',
      filled: '0%',
    },
  },
  {
    id: 'tx-005',
    type: 'deposit',
    category: 'deposit',
    symbol: 'USDC',
    title: 'Deposited 5000 USDC',
    subtitle: 'Completed',
    timestamp: Date.now() - 86400000, // 1 day ago
    depositWithdrawal: {
      amount: '5000.00',
      amountNumber: 5000,
      isPositive: true,
      asset: 'USDC',
      txHash: '0x1234567890abcdef1234567890abcdef12345678',
      status: 'completed',
      type: 'deposit',
    },
  },
  {
    id: 'tx-006',
    type: 'trade',
    category: 'position_open',
    symbol: 'ARB',
    title: 'Opened long',
    subtitle: '1000 ARB @ $1.20',
    timestamp: Date.now() - 90000000, // ~1 day ago
    fill: {
      shortTitle: 'Opened long',
      amount: '+$1,200.00',
      amountNumber: 1200,
      isPositive: true,
      size: '1000',
      entryPrice: '1.20',
      points: '0',
      pnl: '0',
      fee: '1.20',
      action: 'Opened',
      feeToken: 'USDC',
      fillType: FillType.Standard,
    },
  },
  {
    id: 'tx-007',
    type: 'funding',
    category: 'funding_fee',
    symbol: 'BTC',
    title: 'Paid funding fee',
    subtitle: 'BTC',
    timestamp: Date.now() - 97200000, // ~1 day ago
    fundingAmount: {
      isPositive: false,
      fee: '-3.10',
      feeNumber: -3.1,
      rate: '-0.00005',
    },
  },
  {
    id: 'tx-008',
    type: 'trade',
    category: 'position_open',
    symbol: 'POL',
    title: 'Opened short',
    subtitle: '5000 POL @ $0.75',
    timestamp: Date.now() - 172800000, // 2 days ago
    fill: {
      shortTitle: 'Opened short',
      amount: '-$3,750.00',
      amountNumber: -3750,
      isPositive: false,
      size: '5000',
      entryPrice: '0.75',
      points: '0',
      pnl: '0',
      fee: '3.75',
      action: 'Opened',
      feeToken: 'USDC',
      fillType: FillType.Standard,
    },
  },
  {
    id: 'tx-009',
    type: 'withdrawal',
    category: 'withdrawal',
    symbol: 'USDC',
    title: 'Withdrew 2000 USDC',
    subtitle: 'Completed',
    timestamp: Date.now() - 259200000, // 3 days ago
    depositWithdrawal: {
      amount: '2000.00',
      amountNumber: 2000,
      isPositive: false,
      asset: 'USDC',
      txHash: '0xabcdef1234567890abcdef1234567890abcdef12',
      status: 'completed',
      type: 'withdrawal',
    },
  },
  {
    id: 'tx-010',
    type: 'order',
    category: 'limit_order',
    symbol: 'ETH',
    title: 'Limit close long',
    subtitle: '1.0 ETH @ $3,000.00',
    timestamp: Date.now() - 345600000, // 4 days ago
    order: {
      text: PerpsOrderTransactionStatus.Filled,
      statusType: PerpsOrderTransactionStatusType.Filled,
      type: 'limit',
      size: '$3,000.00',
      limitPrice: '3000.00',
      filled: '100%',
    },
  },
  // HIP-3 transactions
  {
    id: 'tx-011',
    type: 'trade',
    category: 'position_open',
    symbol: 'xyz:TSLA',
    title: 'Opened long',
    subtitle: '10 TSLA @ $240.00',
    timestamp: Date.now() - 432000000, // 5 days ago
    fill: {
      shortTitle: 'Opened long',
      amount: '+$2,400.00',
      amountNumber: 2400,
      isPositive: true,
      size: '10',
      entryPrice: '240.00',
      points: '0',
      pnl: '0',
      fee: '2.40',
      action: 'Opened',
      feeToken: 'USDC',
      fillType: FillType.Standard,
    },
  },
  {
    id: 'tx-012',
    type: 'funding',
    category: 'funding_fee',
    symbol: 'xyz:GOLD',
    title: 'Received funding fee',
    subtitle: 'Gold',
    timestamp: Date.now() - 518400000, // 6 days ago
    fundingAmount: {
      isPositive: true,
      fee: '+0.80',
      feeNumber: 0.8,
      rate: '0.00008',
    },
  },
];
