export enum AlertsName {
  AddressPoisoning = 'address_poisoning',
  GasEstimateFailed = 'gasEstimateFailed',
  GasFeeLow = 'gasFeeLow',
  GasTooLow = 'gasTooLow',
  InsufficientBalance = 'insufficientBalance',
  InsufficientPayTokenBalance = 'insufficientPayTokenBalance',
  InsufficientPayTokenNative = 'insufficientPayTokenNative',
  InsufficientPayTokenFees = 'insufficientPayTokenFees',
  NetworkBusy = 'networkBusy',
  NoGasPrice = 'noGasPrice',
  NoPayTokenQuotes = 'noPayTokenQuotes',
  PendingTransaction = 'pendingTransactions',
  PerpsWithdrawBalanceUnavailable = 'perpsWithdrawBalanceUnavailable',
  PayHardwareAccount = 'payHardwareAccount',
  SigningOrSubmitting = 'signingOrSubmitting',
  Blockaid = 'blockaid',
}
