#!/usr/bin/env bash

set -x
set -e
set -u
set -o pipefail

# prepare artifacts dir
mkdir -p ./build-artifacts/deps-viz/

# generate viz
yarn build lavamoat:dashboard
npx sesify-viz --deps dist/lavamoat/deps.json --config dist/lavamoat/lavamoat-config.json --dest ./build-artifacts/deps-viz/