#!/usr/bin/env bash

set -e
set -u
set -o pipefail

if ! npm audit --production
then
    ! npm audit --production --json > audit.json
    printf '%s\n' ''
    node .circleci/scripts/npm-audit-check.js
fi
