export const GO_HOME = 'GO_HOME'
// modal state
export const MODAL_OPEN = 'UI_MODAL_OPEN'
export const MODAL_CLOSE = 'UI_MODAL_CLOSE'
// notification state
export const CLOSE_NOTIFICATION_WINDOW = 'CLOSE_NOTIFICATION_WINDOW'
// sidebar state
export const SIDEBAR_OPEN = 'UI_SIDEBAR_OPEN'
export const SIDEBAR_CLOSE = 'UI_SIDEBAR_CLOSE'
// alert state
export const ALERT_OPEN = 'UI_ALERT_OPEN'
export const ALERT_CLOSE = 'UI_ALERT_CLOSE'
export const QR_CODE_DETECTED = 'UI_QR_CODE_DETECTED'
// network dropdown open
export const NETWORK_DROPDOWN_OPEN = 'UI_NETWORK_DROPDOWN_OPEN'
export const NETWORK_DROPDOWN_CLOSE = 'UI_NETWORK_DROPDOWN_CLOSE'
// remote state
export const UPDATE_METAMASK_STATE = 'UPDATE_METAMASK_STATE'
export const SELECTED_ADDRESS_CHANGED = 'SELECTED_ADDRESS_CHANGED'
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD'
export const CLOSE_WELCOME_SCREEN = 'CLOSE_WELCOME_SCREEN'
// unlock screen
export const UNLOCK_IN_PROGRESS = 'UNLOCK_IN_PROGRESS'
export const UNLOCK_FAILED = 'UNLOCK_FAILED'
export const UNLOCK_SUCCEEDED = 'UNLOCK_SUCCEEDED'
export const LOCK_METAMASK = 'LOCK_METAMASK'
// error handling
export const DISPLAY_WARNING = 'DISPLAY_WARNING'
export const HIDE_WARNING = 'HIDE_WARNING'
// accounts screen
export const SHOW_ACCOUNT_DETAIL = 'SHOW_ACCOUNT_DETAIL'
export const SHOW_ACCOUNTS_PAGE = 'SHOW_ACCOUNTS_PAGE'
export const SHOW_CONF_TX_PAGE = 'SHOW_CONF_TX_PAGE'
export const SET_CURRENT_FIAT = 'SET_CURRENT_FIAT'
// account detail screen
export const SHOW_SEND_TOKEN_PAGE = 'SHOW_SEND_TOKEN_PAGE'
export const SHOW_PRIVATE_KEY = 'SHOW_PRIVATE_KEY'
export const SET_ACCOUNT_LABEL = 'SET_ACCOUNT_LABEL'
export const CLEAR_ACCOUNT_DETAILS = 'CLEAR_ACCOUNT_DETAILS'
// tx conf screen
export const COMPLETED_TX = 'COMPLETED_TX'
export const TRANSACTION_ERROR = 'TRANSACTION_ERROR'
export const UPDATE_TRANSACTION_PARAMS = 'UPDATE_TRANSACTION_PARAMS'
export const SET_NEXT_NONCE = 'SET_NEXT_NONCE'
// send screen
export const UPDATE_GAS_LIMIT = 'UPDATE_GAS_LIMIT'
export const UPDATE_GAS_PRICE = 'UPDATE_GAS_PRICE'
export const UPDATE_GAS_TOTAL = 'UPDATE_GAS_TOTAL'
export const UPDATE_SEND_HEX_DATA = 'UPDATE_SEND_HEX_DATA'
export const UPDATE_SEND_TOKEN_BALANCE = 'UPDATE_SEND_TOKEN_BALANCE'
export const UPDATE_SEND_TO = 'UPDATE_SEND_TO'
export const UPDATE_SEND_AMOUNT = 'UPDATE_SEND_AMOUNT'
export const UPDATE_SEND_ERRORS = 'UPDATE_SEND_ERRORS'
export const UPDATE_MAX_MODE = 'UPDATE_MAX_MODE'
export const UPDATE_SEND = 'UPDATE_SEND'
export const UPDATE_SEND_TOKEN = 'UPDATE_SEND_TOKEN'
export const CLEAR_SEND = 'CLEAR_SEND'
export const GAS_LOADING_STARTED = 'GAS_LOADING_STARTED'
export const GAS_LOADING_FINISHED = 'GAS_LOADING_FINISHED'
export const UPDATE_SEND_ENS_RESOLUTION = 'UPDATE_SEND_ENS_RESOLUTION'
export const UPDATE_SEND_ENS_RESOLUTION_ERROR =
  'UPDATE_SEND_ENS_RESOLUTION_ERROR'
// config screen
export const SET_RPC_TARGET = 'SET_RPC_TARGET'
export const SET_PROVIDER_TYPE = 'SET_PROVIDER_TYPE'
export const SET_PREVIOUS_PROVIDER = 'SET_PREVIOUS_PROVIDER'
export const UPDATE_TOKENS = 'UPDATE_TOKENS'
export const SET_HARDWARE_WALLET_DEFAULT_HD_PATH =
  'SET_HARDWARE_WALLET_DEFAULT_HD_PATH'
// loading overlay
export const SHOW_LOADING = 'SHOW_LOADING_INDICATION'
export const HIDE_LOADING = 'HIDE_LOADING_INDICATION'

export const BUY_ETH = 'BUY_ETH'

export const TOGGLE_ACCOUNT_MENU = 'TOGGLE_ACCOUNT_MENU'

export const SET_USE_BLOCKIE = 'SET_USE_BLOCKIE'
export const SET_USE_NONCEFIELD = 'SET_USE_NONCEFIELD'
export const UPDATE_CUSTOM_NONCE = 'UPDATE_CUSTOM_NONCE'
export const SET_IPFS_GATEWAY = 'SET_IPFS_GATEWAY'

export const SET_PARTICIPATE_IN_METAMETRICS = 'SET_PARTICIPATE_IN_METAMETRICS'
export const SET_METAMETRICS_SEND_COUNT = 'SET_METAMETRICS_SEND_COUNT'

// locale
export const SET_CURRENT_LOCALE = 'SET_CURRENT_LOCALE'

// Feature Flags
export const UPDATE_FEATURE_FLAGS = 'UPDATE_FEATURE_FLAGS'

// Preferences
export const UPDATE_PREFERENCES = 'UPDATE_PREFERENCES'

// Onboarding
export const COMPLETE_ONBOARDING = 'COMPLETE_ONBOARDING'

export const SET_MOUSE_USER_STATE = 'SET_MOUSE_USER_STATE'

// Network
export const SET_PENDING_TOKENS = 'SET_PENDING_TOKENS'
export const CLEAR_PENDING_TOKENS = 'CLEAR_PENDING_TOKENS'

export const SET_FIRST_TIME_FLOW_TYPE = 'SET_FIRST_TIME_FLOW_TYPE'

export const SET_SELECTED_SETTINGS_RPC_URL = 'SET_SELECTED_SETTINGS_RPC_URL'
export const SET_NETWORKS_TAB_ADD_MODE = 'SET_NETWORKS_TAB_ADD_MODE'

export const LOADING_METHOD_DATA_STARTED = 'LOADING_METHOD_DATA_STARTED'
export const LOADING_METHOD_DATA_FINISHED = 'LOADING_METHOD_DATA_FINISHED'

export const LOADING_TOKEN_PARAMS_STARTED = 'LOADING_TOKEN_PARAMS_STARTED'
export const LOADING_TOKEN_PARAMS_FINISHED = 'LOADING_TOKEN_PARAMS_FINISHED'

export const SET_REQUEST_ACCOUNT_TABS = 'SET_REQUEST_ACCOUNT_TABS'
export const SET_CURRENT_WINDOW_TAB = 'SET_CURRENT_WINDOW_TAB'
export const SET_OPEN_METAMASK_TAB_IDS = 'SET_OPEN_METAMASK_TAB_IDS'
