/**
 * E2E Tests: Account Count Display
 * Feature: account-count-display
 *
 * NOTE: This test was generated by spec-kit using Playwright syntax.
 * MetaMask E2E tests use Mocha + Selenium WebDriver with the withFixtures
 * pattern and page objects. This file serves as a reference for the test
 * scenarios — it needs adaptation to MetaMask's E2E framework to run.
 *
 * To adapt, follow the pattern in account-pin-unpin.spec.ts:
 * - Use withFixtures() + FixtureBuilder
 * - Use Driver instead of Playwright page
 * - Use page objects (HeaderNavbar, AccountListPage, etc.)
 */

import { Suite } from 'mocha';
import { Driver } from '../../webdriver/driver';
import { withFixtures } from '../../helpers';
import FixtureBuilder from '../../fixtures/fixture-builder';
import { loginWithBalanceValidation } from '../../page-objects/flows/login.flow';
import HeaderNavbar from '../../page-objects/pages/header-navbar';

describe('Account Count Display', function (this: Suite) {
  describe('US1: View Total Account Count', function () {
    it('displays total account count on home page', async function () {
      await withFixtures(
        {
          fixtures: new FixtureBuilder().build(),
          title: this.test?.fullTitle(),
        },
        async ({ driver }: { driver: Driver }) => {
          await loginWithBalanceValidation(driver);

          // Verify the account count display component is visible on home page
          const accountCountDisplay = await driver.findElement(
            '[data-testid="account-count-display"]',
          );
          await driver.waitForSelector(
            '[data-testid="account-count-display"]',
          );

          // Verify it shows "Total accounts:" label
          const text = await accountCountDisplay.getText();
          if (!text.includes('Total accounts:')) {
            throw new Error(
              `Expected "Total accounts:" in display, got: ${text}`,
            );
          }
        },
      );
    });
  });

  describe('US2: Wallet Breakdown on Hover', function () {
    it('shows breakdown popover on hover', async function () {
      await withFixtures(
        {
          fixtures: new FixtureBuilder().build(),
          title: this.test?.fullTitle(),
        },
        async ({ driver }: { driver: Driver }) => {
          await loginWithBalanceValidation(driver);

          // Hover over the account count display
          const accountCountDisplay = await driver.findElement(
            '[data-testid="account-count-display"]',
          );
          await driver.actions().move({ origin: accountCountDisplay }).perform();

          // Verify breakdown appears
          await driver.waitForSelector(
            '[data-testid="account-count-display-breakdown"]',
          );
        },
      );
    });
  });

  describe('US3: Navigate to Accounts Menu', function () {
    it('clicking total count navigates to accounts menu', async function () {
      await withFixtures(
        {
          fixtures: new FixtureBuilder().build(),
          title: this.test?.fullTitle(),
        },
        async ({ driver }: { driver: Driver }) => {
          await loginWithBalanceValidation(driver);

          // Click on the account count display
          await driver.clickElement(
            '[data-testid="account-count-display"]',
          );

          // Verify accounts menu opens
          // NOTE: This assertion depends on the navigation callback implementation
        },
      );
    });
  });
});
