import { Driver } from '../../webdriver/driver';

// This wallet selection modal is generated by Stellar Wallets Kit inside the test dapp.
export default class StellarWalletModal {
  private readonly driver: Driver;

  private readonly metaMaskWalletButtonSelector = {
    css: '.stellar-wallets-kit li',
    text: 'MetaMask',
  };

  private readonly walletModalSelector = '.stellar-wallets-kit';

  constructor(driver: Driver) {
    this.driver = driver;
  }

  async checkPageIsLoaded(): Promise<void> {
    await this.driver.waitForSelector(this.walletModalSelector);
  }

  async connectToMetaMaskWallet(): Promise<void> {
    await this.driver.clickElement(this.metaMaskWalletButtonSelector);
  }
}
