#+TITLE: ConfluxPortal
#+Author: Conflux Team

* ConfluxPortal
Test version (extremely unstable) of Conflux MetaMask (wallet as a browser extension) that can
connect to Conflux test net.

Conflux 版本的 MetaMask (浏览器插件钱包), 目前为内部测试版本(非常不稳定), 能够连接 Conflux
测试网

** Report bug/提交Bug
Please report any bug at our [[https://github.com/Conflux-Chain/metamask-extension/issues][github issue page]]

** Download/下载
- [[http://13.57.190.119:9000/metamask-chrome-0.0.2.zip][chrome]]
- [[http://13.57.190.119:9000/metamask-firefox-0.0.2.zip][firefox]]
- [[http://13.57.190.119:9000/metamask-opera-0.0.2.zip][opera]]

** Install/安装
*** chrome
Open ~chrome://extensions/~ through chrome location bar, drag the zip file into chrome.

在chrome地址栏中输入 ~chrome://extensions/~, 将下载的 zip 文件拖拽到打开的页面中

*** firefox
Open ~about:debugging#/runtime/this-firefox~ through firefox location bar, load
the zip file through *Load Temporary Add-on* button.

在firefox地址栏中输入 ~about:debugging#/runtime/this-firefox~, 点击加载临时插件
按钮, 选择 zip 文件.

*** opera
Open ~opera://extensions~ through opera location bar, turn developer mode, unzip
the zip file, use *Load unpacked* button to load the unziped folder.

在opera地址栏中输入 ~opera://extensions~, 打开开发这模式, 解压zip文件, 通过加载
未打包插件按钮加载解压后的文件夹.

** Examples
- [[http://13.57.190.119:9000/contract.html][example]] for testing dapp functionalities ([[https://github.com/Conflux-Chain/metamask-extension/blob/cfx-develop/test/e2e/contract-test/contract.js][code]])

** Changelog
*** Unreleased
**** Change
- default gas price in inpage.js changed to 1 Gdrip (from 100 Drip)
- default gas in inpage.js changed to 21000 (from 1000000)

Commits https://github.com/Conflux-Chain/metamask-extension/compare/0.0.2...HEAD

*** 0.0.2 - <2020-01-10 Fri>
- Some "Etherscan" to "Confluxscan"
- Get default gas price from json rpc
