#+TITLE: ConfluxPortal
#+Author: Conflux Team

* ConfluxPortal
Test version (extremely unstable) of ConfluxPortal (wallet as a browser extension) that can
connect to Conflux test net.

ConfluxPortal 是 Conflux 版本的 MetaMask (浏览器插件钱包), 目前为内部测试版本(非
常不稳定), 能够连接 Conflux 测试网

** Report bug/提交Bug
Please report any bug at our [[https://github.com/Conflux-Chain/conflux-portal/issues][github issue page]]

** Documentation/文档
ConfluxPortal support most MetaMask features. Check below pages for details.

- [[https://github.com/Conflux-Chain/conflux-portal/blob/cfx-develop/docs/differences-between-confluxportal-and-metamask.org][Differences between ConfluxPortal and MetaMask]]
- [[https://conflux-chain.github.io/conflux-portal-docs/][ConfluxPortal Developer Docs]]

** Download/下载
- [[http://13.57.190.119:9000/conflux-portal-chrome-0.0.3.zip][chrome]]
- [[http://13.57.190.119:9000/conflux-portal-firefox-0.0.3.zip][firefox]]
- [[http://13.57.190.119:9000/conflux-portal-opera-0.0.3.zip][opera]]

** Install/安装
*** chrome
Open ~chrome://extensions/~ through chrome location bar, drag the zip file into chrome.

在chrome地址栏中输入 ~chrome://extensions/~, 将下载的 zip 文件拖拽到打开的页面中

*** firefox
Open ~about:debugging#/runtime/this-firefox~ through firefox location bar, load
the zip file through *Load Temporary Add-on* button.

在firefox地址栏中输入 ~about:debugging#/runtime/this-firefox~, 点击加载临时插件
按钮, 选择 zip 文件.

*** opera
Open ~opera://extensions~ through opera location bar, turn developer mode, unzip
the zip file, use *Load unpacked* button to load the unziped folder.

在opera地址栏中输入 ~opera://extensions~, 打开开发这模式, 解压zip文件, 通过加载
未打包插件按钮加载解压后的文件夹.

** Examples
- [[http://13.57.190.119:9000/contract.html][example]] for testing dapp functionalities ([[https://github.com/Conflux-Chain/conflux-portal/blob/cfx-develop/test/e2e/contract-test/contract.js][code]])

** Changelog
*** Unreleased

Commits https://github.com/Conflux-Chain/conflux-portal-extension/compare/0.0.3...HEAD

*** 0.0.3 - <2020-01-16 Thu>
**** Change
- remove preset default gas and default gas price in injected web3
- injected conflux version of web3 is now ~window.confluxJS~
- injected ~window.ethereum~ changed to ~window.conflux~
- ~window.ethereum.isMetaMask~ changed to ~window.conflux.isConfluxPortal~
- support skipped transaction

Commits https://github.com/Conflux-Chain/conflux-portal-extension/compare/0.0.2...0.0.3

*** 0.0.2 - <2020-01-10 Fri>
- Some "Etherscan" to "Confluxscan"
- Get default gas price from json rpc
