/** Address of the first account generated by the default local node mnemonic. */
export const LOCAL_NODE_ACCOUNT = '0xe18035bf8712672935fdb4e5e431b1a0183d2dfc';

/** Private key for the local node default account. */
export const LOCAL_NODE_PRIVATE_KEY =
  '0x4cfd3e90fc78b0f86bf7524722150bb8da9c60cd532564d7ff43f5716514f553';

/** Mnemonic for the local node default account. */
export const LOCAL_NODE_MNEMONIC =
  'spread raise short crane omit tent fringe mandate neglect detail suspect cradle';

/** networkClientId for localhost (0x539); matches default-fixture.json. */
export const LOCALHOST_NETWORK_CLIENT_ID =
  '3a5eb6f2-cb62-428d-897c-b7ded577d7c2';

/**
 * Network client IDs. Each key maps to the `networkClientId` used inside
 * `NetworkController.networkConfigurationsByChainId`.
 */
export const NETWORK_CLIENT_ID = Object.freeze({
  MAINNET: 'mainnet',
  ARBITRUM_MAINNET: 'arbitrum-mainnet',
  BASE_MAINNET: 'base-mainnet',
  BSC_MAINNET: 'bsc-mainnet',
  LINEA_MAINNET: 'linea-mainnet',
  LINEA_SEPOLIA: 'linea-sepolia',
  LOCALHOST: LOCALHOST_NETWORK_CLIENT_ID,
  MEGAETH_TESTNET_V2: 'megaeth-testnet-v2',
  MONAD_TESTNET: 'monad-testnet',
  OPTIMISM_MAINNET: 'optimism-mainnet',
  POLYGON_MAINNET: 'polygon-mainnet',
  SEPOLIA: 'sepolia',
} as const);

/** Address of the account derived from the default onboarding fixture. */
export const DEFAULT_FIXTURE_ACCOUNT =
  '0x5CfE73b6021E818B776b421B1c4Db2474086a7e1';

export const DEFAULT_FIXTURE_ACCOUNT_LOWERCASE =
  DEFAULT_FIXTURE_ACCOUNT.toLowerCase();

/** KeyringController vault for withLedgerAccount fixture (HD + Ledger accounts). */
export const LEDGER_FIXTURE_VAULT =
  '{"data":"dwEWCLyS14yChQuzUYsiVhfaSZ7pzwjnhUhmTlz/5Nmxn3aTN/tIicWEMGjQ3+GgJw7E1fkn2OLfA4U9iw5eV5ZVozHLJC+4K3YihNJGcLaxQQj9hb8fnxWhRR2NWgKlThkGiGBF+66qE5rCgmGijYy3WA19OrpgTANYRE9IZifS46MokrWxHlZNY90PQWl+6ROc6XtfbdetpslQkOBCGDTp49FZz0E2M62crLMAU+cSLHuMIkwq7WfbJwy5ybMe085Bo3ghzrwwpysu39vUozGbaQN4EUhNgE7vzxPcasQWwqi/3aLKTm2JATs3sia0jIp5OSdaZkcTX4pcvqgXxGUrxsqK56FtFzAg4TE7qjl2smX3ScW1xJopYHvI8Uv6eEH6kLcnZbV7MJw+Dasu/ROrsynrbywevY3LQ62g07t2ZPz/82VfcEOGcdBmhsVoFGpNYoaESGQIKV2yXLU+0erOzAmYz4bSI+66i+a1woLaQveko/7nm38ILojedM9+Zqfcgh+PjCYyfjRxTc+5BhS+AjHHQgWAD/sqvaMTLQiH7dP4rYHYeZQi9WL9nfvv/orxVJFCEpMAb13BbJefvCKTKxiOg/F+4RPPB46gAAXMrMGtin/P8wxlFcOR0Drfg0COa5hMvSM2hOhV6LUfx3gL5ilAjuFAL3iANh5qJSECg8m46BU6maVQoGQCiaGSfSerEvnbXftXNCK1SfpkSpV7k/hFAVQyv5tN+4yi4CYqLq+43roSNxlaEVSz8MDJr+SNIJQFD8aqT4RiHMQqOPpYrmSvWeZDELs0TQU4XEVKIU/7naocQfdncUfsExXKdJGvIvnISZpNGcr9/DU2V6a3ZmF3pvQ2HPnZgYSsYBXK7mxJSpgTNCwvV1HBSl93SHs59Zn2aWW0qvaS0IpTHklMWC+8YF3FQAikgaEnVnTwGJL/4gg02MMHOKbazr7Cv/z9Vfj8sSU3enuiK4fCRqlFbwKHtQwqry6or6p+NiXFZ40EuMy0NYPkDy/h5Srk0Y1JMRJJp6bcTIu1f90+fVziqQ==","iv":"2gvqZ+DkKASrRK8iCXALPQ==","keyMetadata":{"algorithm":"PBKDF2","params":{"iterations":600000}},"salt":"PwqqENo0YiZXcRrMzg+ujLG2VtyTNkKBCvFMsnzFefk="}';

export const DEFAULT_FIXTURE_ACCOUNT_SHORTENED = '0x5CfE73b602...474086a7e1';

export const TREZOR_VAULT =
  '{"data":"H+KGUVIk87gi/8BeaSNHa2F0lyQ0Jbu/n8MlD1hV9s3EhA8978Qr1nfJyGlO9YY5pZo10R0dWGurtIe7wA/TSqhrY9gqn1O9zSW+4IJBx22iKTmcjN1PIlMtqP8h1Ft3vDVUtXC1ZR6wJWkmPVMMKGDay0OhZ0EL9iK6JEusN4F/XyTbvGHpvEbMq+dgxds3U9g/NcWH8oe0q9ZdqKmcxCwjalVsSfBgwVCpj66Tt+wTMEC38eDeXWrJEs0Kmq6dVUa74ivMhdVJYbqwg0rN4AA/SXBRx+37/nPOcJPV+spyzZvSBwFWDn7l1dwgszdiy+NyCBGUK/jJRYQo5np7+a7n62Gc2Jnbs2cZarqtUKKqQ+oVsSFPJAWfFgoe9QBVhaU+MP8+URSipvJvpgpX+ODV8iEFdJ3rLXs377cvyABKVrVHOusJzwLS1H2evLyqej+HaLMD0TkyB40AiVU1sMc/Od3P1xQ+I8GBxrxfK+hodNLxWbyjbIM9k4vSNZMoTSkiaWSeJ/hxgRL5Y8clAJTRRqgTpwERQUwW891i5t5HIQoIOl2PNsOw7V/wRzCqWR1COjgMRrAoKjVcuOBu2NmnM1MNq/hPNNn8LMmrCH3qydS2N/J/OKRoeny+h4+9IL8rxmzSP7Zqk+tTFZmMkMCrHo3bofmTXg2XjOqjbZuN3Rn+qtvDOjjzf1atI8+4yFn6jffgQF2wFrFpUnVxl+4Gc/EdEZPSKNQgWkYt8rhgMumDppJ1QboWnKIyNjeN2kVNfqUcNsgp4Qkw34Wq5Ifw3NPkmJ1iOmfpsGPjz4vx1+pRS49PT6qRpdM7nRjuB9uU17VztoPiU/ASj5lkTI53NgIGvMQ3qMoee2wRvPSflsy892f5cs8ZqFTm+YB3kRgl2pq8BHRFR+iXcsVPl+I=","iv":"yLI4xnkISVYDNAiMX5XsNw==","keyMetadata":{"algorithm":"PBKDF2","params":{"iterations":600000}},"salt":"KlzhFYDtD7xefesp6xGvs41ZaziHohL7RgfRf1yX1WM="}';

/** Trezor hardware wallet account ID (internalAccounts.accounts key). Used by FixtureBuilderV2.withTrezorAccount(). */
export const TREZOR_ACCOUNT_ID = '221ecb67-0d29-4c04-83b2-dff07c263634';

/** Trezor hardware wallet address (lowercase). Used by FixtureBuilderV2.withTrezorAccount(). */
export const TREZOR_ADDRESS = '0xf68464152d7289d7ea9a2bec2e0035c45188223c';

/** Trezor hardware wallet address (checksum form). Used for AccountTracker keys in fixtures. */
export const TREZOR_ADDRESS_CHECKSUM =
  '0xF68464152d7289D7eA9a2bEC2E0035c45188223c';

/* Address of the 4337 entrypoint smart contract. */
export const ENTRYPOINT = '0x18b06605539dc02ecD3f7AB314e38eB7c1dA5c9b';

/* Address of the generated ERC-4337 account. */
export const ERC_4337_ACCOUNT = '0x8FCd29A7887f82463E0eA7332CB1ce431A4430F7';

/* URL of the local bundler server. */
export const BUNDLER_URL = 'http://localhost:3000/rpc';

/* URL of the 4337 account snap site. */
export const ERC_4337_ACCOUNT_SNAP_URL =
  'https://metamask.github.io/snap-account-abstraction-keyring/0.5.0/';

/* Salt used to generate the 4337 account. */
export const ERC_4337_ACCOUNT_SALT = '0x1';

/* Address of the SimpleAccountFactory smart contract deployed to the local node. */
export const SIMPLE_ACCOUNT_FACTORY =
  '0x4aFf835038b16dccDb1670103C4877A8F93E5219';

/* URL of the Snap Simple Keyring site. */
export const TEST_SNAPS_SIMPLE_KEYRING_WEBSITE_URL =
  'https://metamask.github.io/snap-simple-keyring/1.1.6/';

/* Address of the VerifyingPaymaster smart contract deployed to the local node. */
export const VERIFYING_PAYMASTER = '0xbdbDEc38ed168331b1F7004cc9e5392A2272C1D7';

/* Default local node ETH balance in decimal when first login */
export const DEFAULT_LOCAL_NODE_ETH_BALANCE_DEC = '25';
/* Default local node USD balance in format for when first login */
export const DEFAULT_LOCAL_NODE_USD_BALANCE = '85,000.00';

/* Dapp host addresses and URL*/
export const DAPP_HOST_ADDRESS = '127.0.0.1:8080';
export const DAPP_ONE_ADDRESS = '127.0.0.1:8081';
export const DAPP_URL_LOCALHOST = 'http://localhost:8080';
export const DAPP_URL = `http://${DAPP_HOST_ADDRESS}`;
export const DAPP_ONE_URL = `http://${DAPP_ONE_ADDRESS}`;
export const DAPP_TWO_URL = 'http://127.0.0.1:8082';

// Common base segments for resolving local test dapps from this file's location
const NODE_MODULES_BASE = ['..', '..', 'node_modules'] as const;
const METAMASK_SCOPE = '@metamask';

// Helper to build MetaMask-scoped package paths
const mm = (pkg: string, ...rest: string[]): readonly string[] => [
  ...NODE_MODULES_BASE,
  METAMASK_SCOPE,
  pkg,
  ...rest,
];

/** Mapping of dapp keys to relative path segments from this repo's test root */
export const DAPP_PATHS: Readonly<Record<string, readonly string[]>> =
  Object.freeze({
    'snap-simple-keyring-site': mm('snap-simple-keyring-site', 'public'),
    'snap-account-abstraction-keyring': mm(
      'snap-account-abstraction-keyring-site',
      'public',
    ),
    'test-dapp': mm('test-dapp', 'dist'),
    'test-dapp-multichain': mm('test-dapp-multichain', 'build'),
    'test-dapp-solana': mm('test-dapp-solana', 'dist'),
    'test-dapp-tron': mm('test-dapp-tron', 'dist'),
    'test-snaps': mm('test-snaps', 'dist'),
  });

// Canonical dapp path keys to be used in tests
export const DAPP_PATH = Object.freeze({
  TEST_DAPP: 'test-dapp',
  TEST_DAPP_MULTICHAIN: 'test-dapp-multichain',
  TEST_DAPP_SOLANA: 'test-dapp-solana',
  TEST_DAPP_TRON: 'test-dapp-tron',
  TEST_SNAPS: 'test-snaps',
  SNAP_SIMPLE_KEYRING_SITE: 'snap-simple-keyring-site',
  SNAP_ACCOUNT_ABSTRACTION_KEYRING: 'snap-account-abstraction-keyring',
} as const);

/* Default BTC address created using test SRP (E2E_SRP) with BIP84 derivation */
export const DEFAULT_BTC_ADDRESS = 'bc1qg6whd6pc0cguh6gpp3ewujm53hv32ta9hdp252';

/* Default BTC Account name */
export const DEFAULT_BTC_ACCOUNT_NAME = 'Bitcoin Account 1';

/* Default (mocked) BTC balance used by the Bitcoin RPC provider */
export const DEFAULT_BTC_BALANCE = 1; // BTC

/* Default BTC fee rate */
export const DEFAULT_BTC_FEE_RATE = 2.0060000000000002; // sat/vB

/* Default BTC conversion rate to USD */
export const DEFAULT_BTC_CONVERSION_RATE = 106763; // USD

/* Default SOL conversion rate to USD */
export const DEFAULT_SOL_CONVERSION_RATE = 226; // USD

/* Default BTC transaction ID */
export const DEFAULT_BTC_TRANSACTION_ID =
  'e4111a707317da67d49a71af4cbcf6c0546f900ca32c3842d2254e315d1fca18';

/* Number of sats in 1 BTC */
export const SATS_IN_1_BTC = 100000000; // sats

/* Default (mocked) SOLANA address created using test SRP */
export const DEFAULT_SOLANA_ACCOUNT =
  'E6Aa9DDv7zsePJHosoqiNb3cFuup3fkXTyRH2pZ1nVzP';

/* Default fixture SOLANA address */
export const DEFAULT_FIXTURE_SOLANA_ACCOUNT =
  '4tE76eixEgyJDrdykdWJR1XBkzUk4cLMvqjR2xVJUxer';

/* Solana Mainnet chain ID (genesis hash) */
export const SOLANA_MAINNET_CHAIN_ID = '5eykt4UsFv8P8NJdTREpY1vzqKqZKvdp';

/* Solana Mainnet scope in CAIP-2 format */
export const SOLANA_MAINNET_SCOPE = `solana:${SOLANA_MAINNET_CHAIN_ID}`;

/* Default (mocked) SOLANA balance used by the Solana RPC provider */
export const DEFAULT_SOLANA_BALANCE = 1; // SOL

/* Title of Portfolio page */
export const PORTFOLIO_PAGE_TITLE = 'MetaMask Portfolio';

/* Default TRON address created using test SRP */
export const DEFAULT_TRON_ADDRESS = 'TJ3QZbBREK1Xybe1jf4nR9Attb8i54vGS3';

/* Second TRON address created using test SRP */
export const DEFAULT_TRON_ADDRESS_2 = 'TEcjynxEx7bPfDByW1uwPgsLCBhqynvpQx';

/* Default TRON address created using test SRP */
export const DEFAULT_TRON_ADDRESS_SHORT = 'TJ3Q...vGS3';

/* Account types */
// TODO: Fix in https://github.com/MetaMask/metamask-extension/issues/31860
// eslint-disable-next-line @typescript-eslint/naming-convention
export enum ACCOUNT_TYPE {
  Ethereum,
  Bitcoin,
  Solana,
}

/* Meta metricsId generated by generateMetaMetricsId */
export const MOCK_META_METRICS_ID =
  '0x86bacb9b2bf9a7e8d2b147eadb95ac9aaa26842327cd24afc8bd4b3c1d136420';

/* Mock remote feature flags response */
export const MOCK_REMOTE_FEATURE_FLAGS_RESPONSE = {
  feature1: true,
  feature2: false,
  feature3: {
    name: 'groupA',
    value: 'valueA',
  },
};

/* Mock customized remote feature flags response*/
export const MOCK_CUSTOMIZED_REMOTE_FEATURE_FLAGS = {
  feature3: {
    name: 'groupC',
    value: 'valueC',
  },
};

/* The password for the wallet used in e2e tests*/
export const WALLET_PASSWORD = 'correct horse battery staple';

export const MOCK_AUTH_CONNECTION_ID = 'torus-test-health';
export const MOCK_GROUPED_AUTH_CONNECTION_ID = 'torus-test-health-aggregate';

/* Mock Google account used in Social login flow e2e tests*/
export const MOCK_GOOGLE_ACCOUNT = 'e2e-user-mock@gmail.com';
export const MOCK_GOOGLE_ACCOUNT_WALLET_ADDRESS =
  '0x5CfE73b6021E818B776b421B1c4Db2474086a7e1';
/* Mock Apple account used in Social login flow e2e tests*/
export const MOCK_APPLE_ACCOUNT = 'e2e-user-mock@appleid.com';

/* Test seed phrases used in onboarding flows */
export const TEST_SEED_PHRASE =
  'forum vessel pink push lonely enact gentle tail admit parrot grunt dress';
export const TEST_SEED_PHRASE_TWO =
  'phrase upgrade clock rough situate wedding elder clever doctor stamp excess tent';

/* Test private keys and accounts used by local nodes */
export const PRIVATE_KEY =
  '0x7C9529A67102755B7E6102D6D950AC5D5863C98713805CEC576B945B15B71EAC';
export const PRIVATE_KEY_TWO =
  '0xf444f52ea41e3a39586d7069cb8e8233e9f6b9dea9cbb700cce69ae860661cc8';

/* Frequently used test accounts */
export const ACCOUNT_1 = DEFAULT_FIXTURE_ACCOUNT_LOWERCASE;
export const ACCOUNT_2 = '0x09781764c08de8ca82e156bbf156a3ca217c7950';

/* Window titles */
export const WINDOW_TITLES = Object.freeze({
  ExtensionInFullScreenView: 'MetaMask',
  ExtensionUpdating: 'MetaMask Updating',
  InstalledExtensions: 'Extensions',
  Dialog: 'MetaMask Dialog',
  Phishing: 'MetaMask Phishing Detection',
  ServiceWorkerSettings: 'Inspect with Chrome Developer Tools',
  SnapSimpleKeyringDapp: 'SSK - Simple Snap Keyring',
  TestDApp: 'E2E Test Dapp',
  TestDappSendIndividualRequest: 'E2E Test Dapp - Send Individual Request',
  MultichainTestDApp: 'Multichain Test Dapp',
  SolanaTestDApp: 'Solana Test Dapp',
  TronTestDApp: 'Tron Test Dapp',
  TestSnaps: 'Test Snaps',
  ERC4337Snap: 'Account Abstraction Snap',
});
