/** Address of the first account generated by the default local node mnemonic. */
export const LOCAL_NODE_ACCOUNT = '0xe18035bf8712672935fdb4e5e431b1a0183d2dfc';

/** Private key for the local node default account. */
export const LOCAL_NODE_PRIVATE_KEY =
  '0x4cfd3e90fc78b0f86bf7524722150bb8da9c60cd532564d7ff43f5716514f553';

/** Address of the account derived from the default onboarding fixture. */
export const DEFAULT_FIXTURE_ACCOUNT =
  '0x5CfE73b6021E818B776b421B1c4Db2474086a7e1';

export const DEFAULT_FIXTURE_ACCOUNT_LOWERCASE =
  DEFAULT_FIXTURE_ACCOUNT.toLowerCase();

export const DEFAULT_FIXTURE_ACCOUNT_SHORTENED = '0x5CfE73b602...474086a7e1';

/* Address of the 4337 entrypoint smart contract. */
export const ENTRYPOINT = '0x18b06605539dc02ecD3f7AB314e38eB7c1dA5c9b';

/* Address of the generated ERC-4337 account. */
export const ERC_4337_ACCOUNT = '0x8FCd29A7887f82463E0eA7332CB1ce431A4430F7';

/* URL of the local bundler server. */
export const BUNDLER_URL = 'http://localhost:3000/rpc';

/* URL of the 4337 account snap site. */
export const ERC_4337_ACCOUNT_SNAP_URL =
  'https://metamask.github.io/snap-account-abstraction-keyring/0.5.0/';

/* Salt used to generate the 4337 account. */
export const ERC_4337_ACCOUNT_SALT = '0x1';

/* Address of the SimpleAccountFactory smart contract deployed to the local node. */
export const SIMPLE_ACCOUNT_FACTORY =
  '0x4aFf835038b16dccDb1670103C4877A8F93E5219';

/* URL of the Snap Simple Keyring site. */
export const TEST_SNAPS_SIMPLE_KEYRING_WEBSITE_URL =
  'https://metamask.github.io/snap-simple-keyring/1.1.6/';

/* Address of the VerifyingPaymaster smart contract deployed to the local node. */
export const VERIFYING_PAYMASTER = '0xbdbDEc38ed168331b1F7004cc9e5392A2272C1D7';

/* Default local node ETH balance in decimal when first login */
export const DEFAULT_LOCAL_NODE_ETH_BALANCE_DEC = '25';
/* Default local node USD balance in format for when first login */
export const DEFAULT_LOCAL_NODE_USD_BALANCE = '85,000.00';

/* Dapp host addresses and URL*/
export const DAPP_HOST_ADDRESS = '127.0.0.1:8080';
export const DAPP_ONE_ADDRESS = '127.0.0.1:8081';
export const DAPP_URL_LOCALHOST = 'http://localhost:8080';
export const DAPP_URL = `http://${DAPP_HOST_ADDRESS}`;
export const DAPP_ONE_URL = `http://${DAPP_ONE_ADDRESS}`;
export const DAPP_TWO_URL = 'http://127.0.0.1:8082';

// Common base segments for resolving local test dapps from this file's location
const NODE_MODULES_BASE = ['..', '..', 'node_modules'] as const;
const METAMASK_SCOPE = '@metamask';

// Helper to build MetaMask-scoped package paths
const mm = (pkg: string, ...rest: string[]): readonly string[] => [
  ...NODE_MODULES_BASE,
  METAMASK_SCOPE,
  pkg,
  ...rest,
];

/** Mapping of dapp keys to relative path segments from this repo's test root */
export const DAPP_PATHS: Readonly<Record<string, readonly string[]>> =
  Object.freeze({
    'snap-simple-keyring-site': mm('snap-simple-keyring-site', 'public'),
    'snap-account-abstraction-keyring': mm(
      'snap-account-abstraction-keyring-site',
      'public',
    ),
    'test-dapp': mm('test-dapp', 'dist'),
    'test-dapp-multichain': mm('test-dapp-multichain', 'build'),
    'test-dapp-solana': mm('test-dapp-solana', 'dist'),
    'test-snaps': mm('test-snaps', 'dist'),
  });

// Canonical dapp path keys to be used in tests
export const DAPP_PATH = Object.freeze({
  TEST_DAPP: 'test-dapp',
  TEST_DAPP_MULTICHAIN: 'test-dapp-multichain',
  TEST_DAPP_SOLANA: 'test-dapp-solana',
  TEST_SNAPS: 'test-snaps',
  SNAP_SIMPLE_KEYRING_SITE: 'snap-simple-keyring-site',
  SNAP_ACCOUNT_ABSTRACTION_KEYRING: 'snap-account-abstraction-keyring',
} as const);

/* Default BTC address created using test SRP */
export const DEFAULT_BTC_ADDRESS = 'bc1qg6whd6pc0cguh6gpp3ewujm53hv32ta9hdp252';

/* Default BTC Account name */
export const DEFAULT_BTC_ACCOUNT_NAME = 'Bitcoin Account 1';

/* Default (mocked) BTC balance used by the Bitcoin RPC provider */
export const DEFAULT_BTC_BALANCE = 1; // BTC

/* Default BTC fee rate */
export const DEFAULT_BTC_FEE_RATE = 2.0060000000000002; // sat/vB

/* Default BTC conversion rate to USD */
export const DEFAULT_BTC_CONVERSION_RATE = 106763; // USD

/* Default SOL conversion rate to USD */
export const DEFAULT_SOL_CONVERSION_RATE = 226; // USD

/* Default BTC transaction ID */
export const DEFAULT_BTC_TRANSACTION_ID =
  'e4111a707317da67d49a71af4cbcf6c0546f900ca32c3842d2254e315d1fca18';

/* Number of sats in 1 BTC */
export const SATS_IN_1_BTC = 100000000; // sats

/* Default (mocked) SOLANA address created using test SRP */
export const DEFAULT_SOLANA_ACCOUNT =
  'E6Aa9DDv7zsePJHosoqiNb3cFuup3fkXTyRH2pZ1nVzP';

/* Default (mocked) SOLANA balance used by the Solana RPC provider */
export const DEFAULT_SOLANA_BALANCE = 1; // SOL

/* Title of Portfolio page */
export const PORTFOLIO_PAGE_TITLE = 'MetaMask Portfolio';

/* Account types */
// TODO: Fix in https://github.com/MetaMask/metamask-extension/issues/31860
// eslint-disable-next-line @typescript-eslint/naming-convention
export enum ACCOUNT_TYPE {
  Ethereum,
  Bitcoin,
  Solana,
}

/* Meta metricsId generated by generateMetaMetricsId */
export const MOCK_META_METRICS_ID =
  '0x86bacb9b2bf9a7e8d2b147eadb95ac9aaa26842327cd24afc8bd4b3c1d136420';

/* Mock remote feature flags response */
export const MOCK_REMOTE_FEATURE_FLAGS_RESPONSE = {
  feature1: true,
  feature2: false,
  feature3: {
    name: 'groupC',
    value: 'valueC',
  },
  sendRedesign: {
    enabled: false,
  },
};

/* Mock customized remote feature flags response*/
export const MOCK_CUSTOMIZED_REMOTE_FEATURE_FLAGS = {
  feature3: {
    name: 'groupA',
    value: 'valueA',
  },
};

/* The password for the wallet used in e2e tests*/
export const WALLET_PASSWORD = 'correct horse battery staple';

export const MOCK_AUTH_CONNECTION_ID = 'torus-test-health';
export const MOCK_GROUPED_AUTH_CONNECTION_ID = 'torus-test-health-aggregate';

/* Mock Google account used in Social login flow e2e tests*/
export const MOCK_GOOGLE_ACCOUNT = 'e2e-user-mock@gmail.com';
export const MOCK_GOOGLE_ACCOUNT_WALLET_ADDRESS =
  '0x5CfE73b6021E818B776b421B1c4Db2474086a7e1';
/* Mock Apple account used in Social login flow e2e tests*/
export const MOCK_APPLE_ACCOUNT = 'e2e-user-mock@appleid.com';

/* Test seed phrases used in onboarding flows */
export const TEST_SEED_PHRASE =
  'forum vessel pink push lonely enact gentle tail admit parrot grunt dress';
export const TEST_SEED_PHRASE_TWO =
  'phrase upgrade clock rough situate wedding elder clever doctor stamp excess tent';

/* Test private keys and accounts used by local nodes */
export const PRIVATE_KEY =
  '0x7C9529A67102755B7E6102D6D950AC5D5863C98713805CEC576B945B15B71EAC';
export const PRIVATE_KEY_TWO =
  '0xf444f52ea41e3a39586d7069cb8e8233e9f6b9dea9cbb700cce69ae860661cc8';

/* Frequently used test accounts */
export const ACCOUNT_1 = DEFAULT_FIXTURE_ACCOUNT_LOWERCASE;
export const ACCOUNT_2 = '0x09781764c08de8ca82e156bbf156a3ca217c7950';

/* Window titles */
export const WINDOW_TITLES = Object.freeze({
  ExtensionInFullScreenView: 'MetaMask',
  ExtensionUpdating: 'MetaMask Updating',
  InstalledExtensions: 'Extensions',
  Dialog: 'MetaMask Dialog',
  Phishing: 'MetaMask Phishing Detection',
  ServiceWorkerSettings: 'Inspect with Chrome Developer Tools',
  SnapSimpleKeyringDapp: 'SSK - Simple Snap Keyring',
  TestDApp: 'E2E Test Dapp',
  TestDappSendIndividualRequest: 'E2E Test Dapp - Send Individual Request',
  MultichainTestDApp: 'Multichain Test Dapp',
  SolanaTestDApp: 'Solana Test Dapp',
  TestSnaps: 'Test Snaps',
  ERC4337Snap: 'Account Abstraction Snap',
});
