import { cloneDeep } from 'lodash';

type VersionedData = {
  meta: { version: number };
  data: Record<string, unknown>;
};

export const version = 100;

/**
 * The core TransactionController uses strings for transaction IDs, specifically UUIDs generated by the uuid package.
 * For the sake of standardisation and minimising code maintenance, the use of UUIDs is preferred.
 * This migration updates the transaction IDs to UUIDs.
 *
 * @param originalVersionedData
 */
export async function migrate(
  originalVersionedData: VersionedData,
): Promise<VersionedData> {
  const versionedData = cloneDeep(originalVersionedData);
  versionedData.meta.version = version;
  transformState(versionedData.data);
  return versionedData;
}

function transformState(state: Record<string, any>) {
  const transactionControllerState = state?.TransactionController || {};
  const transactionsObject = transactionControllerState?.transactions || {};

  state.TransactionController = {
    ...transactionControllerState,
    transactions: Object.values(transactionsObject),
  };
}
