name: Add team label

on:
  pull_request:
    types:
      - opened

jobs:
  add-team-label:
    name: Add team label
    if: ${{ !github.event.pull_request.head.repo.fork }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Get planning token
        id: planning-token
        uses: MetaMask/github-tools/.github/actions/get-token@v1
        with:
          token-exchange-url: ${{ vars.TOKEN_EXCHANGE_URL }}
          target-repository: MetaMask/MetaMask-planning
          permissions: |
            contents: read

      - name: Get label token
        id: label-token
        uses: MetaMask/github-tools/.github/actions/get-token@v1
        with:
          token-exchange-url: ${{ vars.TOKEN_EXCHANGE_URL }}
          permissions: |
            contents: read
            pull_requests: write

      - name: Add team label
        uses: MetaMask/github-tools/.github/actions/add-team-label@v1
        with:
          planning-token: ${{ steps.planning-token.outputs.token }}
          team-label-token: ${{ steps.label-token.outputs.token }}
