name: Close release bug report issue when release branch gets merged

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  close-bug-report:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'Version-v')
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@t2
        with:
          is-high-risk-environment: false
          skip-allow-scripts: true
          yarn-custom-url: 'https://diuv6g5fj9pvx.cloudfront.net/metamask-extension/yarn-4.9.1/yarn.js#sha224.4285002185abb91fe2b781f27fd1e078086c37a7b095f6ea4ee25971'

      - name: Close release bug report issue
        env:
          BUG_REPORT_REPO: MetaMask-planning
          BUG_REPORT_TOKEN: ${{ secrets.BUG_REPORT_TOKEN }}
        run: yarn run close-release-bug-report-issue
