name: E2E Speculos Tests

on:
  workflow_call:
    inputs:
      builds-from-run:
        required: true
        type: string
        description: The run ID to get builds from
    secrets:
      INFURA_PROJECT_ID:
        required: false

jobs:
  speculos-tests:
    strategy:
      fail-fast: false
      matrix:
        device:
          - id: nanosp
            elf: ethereum-nanosp.elf
          - id: nanox
            elf: ethereum-nanox.elf
          - id: stax
            elf: ethereum-stax.elf
          - id: flex
            elf: ethereum-flex.elf
    uses: ./.github/workflows/run-e2e.yml
    with:
      test-suite-name: 'Speculos ${{ matrix.device.id }}'
      build-artifact: build-test-browserify
      build-command: 'yarn build:test'
      test-command: >-
        SPECULOS_E2E=1 SPECULOS_DEVICE=${{ matrix.device.id }} SPECULOS_ELF=${{ matrix.device.elf }} ENABLE_CHROME_LOGGING=false yarn test:e2e:chrome:ledger --debug=false
      builds-from-run: ${{ inputs.builds-from-run }}
      install-speculos: 'speculos==0.26.8'
    secrets:
      INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
