name: Identify Codeowners

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !(contains(github.ref, 'refs/heads/main') || contains(github.ref, 'refs/heads/stable')) }}

jobs:
  identify-codeowners:
    # Avoid running on cross-repo PRs since we need to write a PR comment
    # Avoid running on release branches and bot PRs
    if: >-
      ${{
        github.event.pull_request.head.repo.full_name == github.repository
        && !startsWith(github.head_ref, 'release/')
        && github.event.pull_request.user.login != 'metamaskbot'
        && github.event.pull_request.user.login != 'runway-github[bot]'
      }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: pr-comment
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Get token
        id: token
        uses: MetaMask/github-tools/.github/actions/get-token@7e0d74bc7b79ce9601e52f58d5e4d36c19591df9 # v1.19.0
        with:
          token-exchange-url: ${{ vars.TOKEN_EXCHANGE_URL }}
          permissions: |
            actions: read
            contents: write
            pull_requests: write

      - name: Checkout .github/ directory
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          sparse-checkout: |
            .github
            .nvmrc
          sparse-checkout-cone-mode: false

      - name: Setup Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version-file: '.nvmrc'

      - name: Install script dependencies
        run: npm install --no-save @actions/core@^3.0.1 @actions/github@^9.1.1 micromatch@^4.0.8

      - name: Identify codeowners
        env:
          PR_COMMENT_TOKEN: ${{ steps.token.outputs.token }}
        run: node ./.github/scripts/identify-codeowners.mts
