name: Identify Codeowners

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !(contains(github.ref, 'refs/heads/main') || contains(github.ref, 'refs/heads/stable')) }}

jobs:
  identify-codeowners:
    # Avoid running on cross-repo PRs since we need to write a PR comment
    # Avoid running on release branches and bot PRs
    if: >-
      ${{
        github.event.pull_request.head.repo.full_name == github.repository
        && !startsWith(github.head_ref, 'release/')
        && github.event.pull_request.user.login != 'metamaskbot'
        && github.event.pull_request.user.login != 'runway-github[bot]'
      }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: pr-comment
    steps:
      - name: Checkout .github/ directory
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            .github
            .nvmrc
          sparse-checkout-cone-mode: false

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'

      - name: Install script dependencies
        run: npm install --no-save @actions/core@^3.0.1 @actions/github@^9.1.1 micromatch@^4.0.8

      - name: Identify codeowners
        env:
          PR_COMMENT_TOKEN: ${{ secrets.PR_COMMENT_TOKEN }}
        run: node ./.github/scripts/identify-codeowners.mts
