name: LavaMoat

on:
  workflow_call:
    inputs:
      builds-from-run:
        required: true
        type: string
    outputs:
      lavamoat-policy-changed:
        description: Whether LavaMoat policy files have changed
        value: ${{ jobs.build-viz.outputs.lavamoat-policy-changed }}

env:
  INFURA_PROJECT_ID: 00000000000
  INFURA_PROD_PROJECT_ID: 00000000000
  SEGMENT_PROD_WRITE_KEY: 00000000000
  GOOGLE_PROD_CLIENT_ID: 00000000000
  APPLE_PROD_CLIENT_ID: 00000000000
  GOOGLE_BETA_CLIENT_ID: 00000000000
  APPLE_BETA_CLIENT_ID: 00000000000
  GOOGLE_EXPERIMENTAL_CLIENT_ID: 00000000000
  APPLE_EXPERIMENTAL_CLIENT_ID: 00000000000
  GOOGLE_FLASK_CLIENT_ID: 00000000000
  APPLE_FLASK_CLIENT_ID: 00000000000

jobs:
  validate-policy-build:
    name: Validate LavaMoat build policy
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v3
        with:
          is-high-risk-environment: false
          skip-allow-scripts: true

      - name: Validate LavaMoat build policy
        run: yarn lavamoat:build:auto

      - name: Check working tree
        run: |
          if ! git diff --exit-code; then
              echo "::error::Working tree dirty."
              exit 1
          fi

  validate-policy-webapp:
    name: Validate LavaMoat webapp policy
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v3
        with:
          is-high-risk-environment: false
          skip-allow-scripts: true

      - name: Validate LavaMoat webapp policy
        run: yarn lavamoat:webapp:auto

      - name: Check working tree
        run: |
          if ! git diff --exit-code; then
              echo "::error::Working tree dirty."
              exit 1
          fi

  validate-policy-webpack-build:
    name: Validate LavaMoat webpack build policy
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v3
        with:
          is-high-risk-environment: false
          skip-allow-scripts: true

      - name: Validate LavaMoat webpack build policy
        run: yarn webpack:tsc && yarn webpack:lavamoat:policy:build

      - name: Check working tree
        run: |
          if ! git diff --exit-code; then
              echo "::error::Working tree dirty."
              exit 1
          fi

  validate-policy-webpack-mv2:
    name: Validate LavaMoat webpack MV2 policy
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v3
        with:
          is-high-risk-environment: false
          skip-allow-scripts: true

      - name: Validate LavaMoat webpack MV2 policy
        run: yarn webpack:tsc && yarn webpack:lavamoat:policy:mv2

      - name: Check working tree
        run: |
          if ! git diff --exit-code; then
              echo "::error::Working tree dirty."
              exit 1
          fi

  validate-policy-webpack-mv3:
    name: Validate LavaMoat webpack MV3 policy
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v3
        with:
          is-high-risk-environment: false
          skip-allow-scripts: true

      - name: Validate LavaMoat webpack MV3 policy
        run: yarn webpack:tsc && yarn webpack:lavamoat:policy:mv3

      - name: Check working tree
        run: |
          if ! git diff --exit-code; then
              echo "::error::Working tree dirty."
              exit 1
          fi

  build-viz:
    name: Build viz
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
    outputs:
      lavamoat-policy-changed: ${{ steps.lavamoat-policy-changed.outputs.lavamoat-policy-changed }}
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v3
        with:
          is-high-risk-environment: false
          skip-allow-scripts: true

      - name: Download changed-files artifact
        if: ${{ env.BRANCH != 'main' }}
        id: download-changed-files
        continue-on-error: true
        uses: actions/download-artifact@v7
        with:
          name: changed-files
          path: ./changed-files/

      # if the changed-files artifact does not exist, we get the diff
      - run: yarn tsx .github/scripts/git-diff-default-branch.ts
        if: ${{ steps.download-changed-files.outcome == 'failure' }}

      - name: See if lavamoat policy files have changed
        id: lavamoat-policy-changed
        run: |
          # if 'changed-files/changed-files.json' exists, check if it contains any files named policy.json or policy-override.json
          if [ -f "changed-files/changed-files.json" ]; then
            if grep -q -e 'policy.json' -e 'policy-override.json' changed-files/changed-files.json; then
              echo "Lavamoat policy file changes detected."
              echo "lavamoat-policy-changed=true" >> "$GITHUB_OUTPUT"
            else
              echo "No Lavamoat policy file changes detected."
              echo "lavamoat-policy-changed=false" >> "$GITHUB_OUTPUT"
            fi
          else
            echo "Cannot find 'changed-files.json', assuming that Lavamoat policy files have changed."
            echo "lavamoat-policy-changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Download artifact 'build-dist-browserify'
        if: ${{ steps.lavamoat-policy-changed.outputs.lavamoat-policy-changed == 'true' }}
        uses: actions/download-artifact@v7
        with:
          name: build-dist-browserify
          github-token: ${{ secrets.GITHUB_TOKEN }} # This is required when downloading artifacts from a different repository or from a different workflow run.
          run-id: ${{ inputs.builds-from-run }} # Download from whatever run the get-requirements job said.

      - run: ./.github/scripts/create-lavamoat-viz.sh
        if: ${{ steps.lavamoat-policy-changed.outputs.lavamoat-policy-changed == 'true' }}

      - name: Upload 'build-viz' to S3
        if: ${{ steps.lavamoat-policy-changed.outputs.lavamoat-policy-changed == 'true' && vars.AWS_REGION && vars.AWS_IAM_ROLE && vars.AWS_S3_BUCKET }}
        uses: MetaMask/github-tools/.github/actions/upload-s3@v1
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_IAM_ROLE }}
          s3-bucket: ${{ vars.AWS_S3_BUCKET }}/${{ github.event.repository.name }}/${{ env.RUN_ID }}/lavamoat-viz
          path: build-artifacts/build-viz
