name: Main

on:
  push:
    branches:
      - main
      - master
      - Version-v*
      - trigger-ci*
      - prep-deps*
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  merge_group:

jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        uses: metamask/github-tools/.github/actions/checkout-and-setup@caching2
        with:
          ref: '10.33'

      - run: cat package.json
        shell: bash

  test2:
    runs-on: ubuntu-latest
    steps:
      - name: Setup environment
        uses: metamask/github-tools/.github/actions/checkout-and-setup@caching2

      - run: cat package.json
        shell: bash
