name: Main

on:
  push:

jobs:
  webpack-matrix:
    name: yarn webpack (workers=${{ matrix.workers }}, jobs=${{ matrix.workerParallelJobs }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        workers: [1, 2, 4, 6, 8, 10]
        workerParallelJobs: [2, 4, 6, 8, 10, 12, 14, 16]

    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@v3
        with:
          is-high-risk-environment: false
          skip-allow-scripts: true

      - name: yarn webpack
        env:
          THREAD_LOADER_WORKERS: ${{ matrix.workers }}
          THREAD_LOADER_WORKER_PARALLEL_JOBS: ${{ matrix.workerParallelJobs }}
        run: yarn webpack
