name: Needs E2E

on: push

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Get last completed main workflow
        id: get-last-completed-main-workflow
        run: |
          last_completed_main_workflow=$(gh api "/repos/MetaMask/metamask-extension/actions/workflows/main.yml/runs?branch=main&per_page=1&status=completed" | jq -r .workflow_runs[0].id)
          echo 'LAST_COMPLETED_MAIN_WORKFLOW='"$last_completed_main_workflow" >> "$GITHUB_OUTPUT"

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: .
          pattern: test-e2e-chrome*
          merge-multiple: true
          github-token: ${{ github.token }} # This is required when downloading artifacts from a different repository or from a different workflow run.
          run-id: ${{ steps.get-last-completed-main-workflow.outputs.LAST_COMPLETED_MAIN_WORKFLOW }} # Use the workflow id that triggered the workflow

      - run: ls -laR test/test-results/e2e
        name: List test results
