on:
  workflow_call:

env:
  COMMANDS: |
    {
      pageload: 'SELENIUM_BROWSER={0} yarn tsx test/e2e/benchmark.mjs --out test-artifacts/benchmarks/benchmark-{0}-{1}-pageload.json --retries 2',
      userActions: 'SELENIUM_BROWSER={0} yarn tsx test/e2e/user-actions-benchmark.js --out test-artifacts/benchmarks/benchmark-{0}-{1}-userActions.json --retries 2',
    }

jobs:
  benchmarks:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, firefox]
        buildType: [browserify, webpack]
        testType: [pageload, userActions]
        # exclude:
        #   # webpack can build for Firefox, but it would require more custom code here,
        #   # and it's probably not useful to test this right now anyway
        #   - browser: firefox
        #     buildType: webpack

    name: ${{ matrix.browser }}-${{ matrix.buildType }}-${{ matrix.testType }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        uses: metamask/github-tools/.github/actions/setup-environment@1d657e262aea7e3f216754febb624831527d2565

      - name: Compute ARTIFACT_NAME
        run: |
          if [[ "${{ matrix.buildType }}" == "webpack" ]]; then
            ARTIFACT_NAME="prep-build-test-${{ matrix.buildType }}-${{ matrix.browser }}"
          else
            ARTIFACT_NAME="prep-build-test-${{ matrix.buildType }}"
          fi

          echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> "$GITHUB_ENV"

      - name: Download artifact ${{env.ARTIFACT_NAME}}
        uses: actions/download-artifact@v4
        with:
          path: ./dist/
          pattern: ${{env.ARTIFACT_NAME}}
          merge-multiple: true

      # - run: echo "set -g mouse on" >> ~/.tmux.conf

      # - name: Debugging with tmate
      #   uses: ./.github/actions/actions-tmate
      #   with:
      #     limit-access-to-actor: true

      - name: Run the benchmark
        # Choose a benchmark command from env.COMMANDS
        # Then replace the {0} placeholder with the browser, and the {1} placeholder with the buildType
        run: ${{ format(fromJson(env.COMMANDS)[matrix.testType], matrix.browser, matrix.buildType) }}

      # - name: Rename test artifacts
      #   run: mv test-artifacts/${{ matrix.browser }}/benchmark/${{ matrix.testType }}.json test-artifacts/${{ matrix.browser }}/benchmark/benchmark-${{ matrix.buildType }}-${{ matrix.testType }}.json

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-${{ matrix.browser }}-${{ matrix.buildType }}-${{ matrix.testType }}
          path: test-artifacts/benchmarks/
