name: Stable Branch Sync

on:
  push:
    branches:
      - stable

permissions:
  contents: write

jobs:
  get-stable-version:
    name: Get stable release version
    runs-on: ubuntu-latest
    timeout-minutes: 30
    outputs:
      stable-version: ${{ steps.resolve-stable-version.outputs.stable_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Get stable release version
        id: resolve-stable-version
        run: ./get-stable-released-version.sh
        working-directory: '.github/scripts'

  run-stable-sync:
    name: Run Stable branch sync
    needs: get-stable-version
    runs-on: ubuntu-latest
    steps:
      - name: Run stable sync
        uses: MetaMask/github-tools/.github/actions/stable-sync@v1
        with:
          semver-version: ${{ needs['get-stable-version'].outputs['stable-version'] }}
          repo-type: 'extension'
          stable-branch-name: 'stable'
          github-token: ${{ secrets.STABLE_SYNC_TOKEN }}
