name: 'Close stale issues and PRs'

# run once daily at midnight (UTC)
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stale:
    name: Close stale issues and PRs
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Close stale issues and PRs
        uses: MetaMask/github-tools/.github/actions/stale-issue-pr@7e0d74bc7b79ce9601e52f58d5e4d36c19591df9 # v1.19.0
