name: Test reproducible build

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches-ignore:
      - stable

env:
  # For a `pull_request` event, the branch is `github.head_ref``.
  # For a `push` event, the branch is `github.ref_name`.
  BRANCH: ${{ github.head_ref || github.ref_name }}
  # For a `pull_request` event, the head commit hash is `github.event.pull_request.head.sha`.
  # For a `push` event, the head commit hash is `github.sha`.
  HEAD_COMMIT_HASH: ${{ github.event.pull_request.head.sha || github.sha }}
  RUN_ID: ${{ github.run_id }}

permissions:
  contents: write # required for releases
  id-token: write # required for s3 uploads
  statuses: write # required for build-source-hash and ci-status-gate

jobs:
  build-dist-mv2-webpack:
    strategy:
      fail-fast: false
      matrix:
        iteration:
          [
            1,
            # 2,
            # 3,
            # 4,
            # 5,
            # 6,
            # 7,
            # 8,
            # 9,
            # 10,
            # 11,
            # 12,
            # 13,
            # 14,
            # 15,
            # 16,
            # 17,
            # 18,
            # 19,
            # 20,
            # 21,
            # 22,
            # 23,
            # 24,
            # 25,
            # 26,
            # 27,
            # 28,
            # 29,
            # 30,
            # 31,
            # 32,
            # 33,
            # 34,
            # 35,
            # 36,
            # 37,
            # 38,
            # 39,
            # 40,
            # 41,
            # 42,
            # 43,
            # 44,
            # 45,
            # 46,
            # 47,
            # 48,
            # 49,
            # 50,
            # 51,
            # 52,
            # 53,
            # 54,
            # 55,
            # 56,
            # 57,
            # 58,
            # 59,
            # 60,
            # 61,
            # 62,
            # 63,
            # 64,
            # 65,
            # 66,
            # 67,
            # 68,
            # 69,
            # 70,
            # 71,
            # 72,
            # 73,
            # 74,
            # 75,
            # 76,
            # 77,
            # 78,
            # 79,
            # 80,
            # 81,
            # 82,
            # 83,
            # 84,
            # 85,
            # 86,
            # 87,
            # 88,
            # 89,
            # 90,
            # 91,
            # 92,
            # 93,
            # 94,
            # 95,
            # 96,
            # 97,
            # 98,
            # 99,
            # 100,
          ]
    runs-on: ubuntu-latest
    env:
      FIREFOX_BUNDLE_SCRIPT_TOKEN: ${{ secrets.FIREFOX_BUNDLE_SCRIPT_TOKEN }}
    steps:
      - name: Checkout and setup environment
        uses: actions/checkout@v6
      - name: Build main
        shell: bash
        run: bash "${GITHUB_WORKSPACE}/.github/scripts/firefox-bundle-script/prepare_release.sh" 13.47.1 13.47.0
      # - name: Get runtime hash
      #   id: get_hash
      #   run: |
      #     runtime_hash="$(find ./dist/firefox/ -name "runtime.*" | cut -d . -f 3)"
      #     echo "runtime_hash=${runtime_hash}" >> "${GITHUB_OUTPUT}"
      # - name: Upload artifact 'main-${{ matrix.iteration }}-${{ steps.get_hash.outputs.runtime_hash }}'
      #   if: ${{ steps.get_hash.outputs.runtime_hash != 'b574af00e40dcd7e628a' }}
      #   uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      #   with:
      #     name: main-${{ matrix.iteration }}-${{ steps.get_hash.outputs.runtime_hash }}
      #     path: |
      #       builds
      #       dist
      #     retention-days: 1

  build-flask-mv2-webpack:
    strategy:
      fail-fast: false
      matrix:
        iteration:
          [
            1,
            # 2,
            # 3,
            # 4,
            # 5,
            # 6,
            # 7,
            # 8,
            # 9,
            # 10,
            # 11,
            # 12,
            # 13,
            # 14,
            # 15,
            # 16,
            # 17,
            # 18,
            # 19,
            # 20,
            # 21,
            # 22,
            # 23,
            # 24,
            # 25,
            # 26,
            # 27,
            # 28,
            # 29,
            # 30,
            # 31,
            # 32,
            # 33,
            # 34,
            # 35,
            # 36,
            # 37,
            # 38,
            # 39,
            # 40,
            # 41,
            # 42,
            # 43,
            # 44,
            # 45,
            # 46,
            # 47,
            # 48,
            # 49,
            # 50,
            # 51,
            # 52,
            # 53,
            # 54,
            # 55,
            # 56,
            # 57,
            # 58,
            # 59,
            # 60,
            # 61,
            # 62,
            # 63,
            # 64,
            # 65,
            # 66,
            # 67,
            # 68,
            # 69,
            # 70,
            # 71,
            # 72,
            # 73,
            # 74,
            # 75,
            # 76,
            # 77,
            # 78,
            # 79,
            # 80,
            # 81,
            # 82,
            # 83,
            # 84,
            # 85,
            # 86,
            # 87,
            # 88,
            # 89,
            # 90,
            # 91,
            # 92,
            # 93,
            # 94,
            # 95,
            # 96,
            # 97,
            # 98,
            # 99,
            # 100,
          ]
    runs-on: ubuntu-latest
    env:
      FIREFOX_BUNDLE_SCRIPT_TOKEN: ${{ secrets.FIREFOX_BUNDLE_SCRIPT_TOKEN }}
    steps:
      - name: Checkout and setup environment
        uses: actions/checkout@v6
      - name: Build flask
        shell: bash
        run: bash "${GITHUB_WORKSPACE}/.github/scripts/firefox-bundle-script/prepare_release.sh" --flask 13.47.1 13.47.0
      # - name: Get runtime hash
      #   id: get_hash
      #   run: |
      #     runtime_hash="$(find ./dist/firefox/ -name "runtime.*" | cut -d . -f 3)"
      #     echo "runtime_hash=${runtime_hash}" >> "${GITHUB_OUTPUT}"
      # - name: Upload artifact 'flask-${{ matrix.iteration }}-${{ steps.get_hash.outputs.runtime_hash }}'
      #   if: ${{ steps.get_hash.outputs.runtime_hash != '0c40264eb2c3354bf635' }}
      #   uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      #   with:
      #     name: flask-${{ matrix.iteration }}-${{ steps.get_hash.outputs.runtime_hash }}
      #     path: |
      #       builds
      #       dist
      #     retention-days: 1
