name: Test reproducible build

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches-ignore:
      - stable

env:
  # For a `pull_request` event, the branch is `github.head_ref``.
  # For a `push` event, the branch is `github.ref_name`.
  BRANCH: ${{ github.head_ref || github.ref_name }}
  # For a `pull_request` event, the head commit hash is `github.event.pull_request.head.sha`.
  # For a `push` event, the head commit hash is `github.sha`.
  HEAD_COMMIT_HASH: ${{ github.event.pull_request.head.sha || github.sha }}
  RUN_ID: ${{ github.run_id }}

permissions:
  contents: write # required for releases
  id-token: write # required for s3 uploads
  statuses: write # required for build-source-hash and ci-status-gate

jobs:
  build-dist-mv2-webpack:
    strategy:
      fail-fast: false
      matrix:
        iteration:
          [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
          ]
    runs-on: ubuntu-latest
    env:
      FIREFOX_BUNDLE_SCRIPT_TOKEN: ${{ secrets.FIREFOX_BUNDLE_SCRIPT_TOKEN }}
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@0543b5929698c71e3ccc6ed24eac87825669b5de # v3.5.0
        with:
          is-high-risk-environment: true
          skip-allow-scripts: true
      - name: Build main
        shell: bash
        run: bash "${GITHUB_WORKSPACE}/.github/scripts/package-firefox-reviewer-artifacts.sh" main
      - name: Capture failed build
        if: ${{ failure() }}
        uses: actions/upload-artifact@v6
        with:
          name: failed-build-main-${{ matrix.iteration }}
          path: /tmp/test-bundle-script/firefox-bundle-script/output

  build-flask-mv2-webpack:
    strategy:
      fail-fast: false
      matrix:
        iteration:
          [
            1,
            2,
            3,
            4,
            5,
            6,
            7,
            8,
            9,
            10,
          ]
    runs-on: ubuntu-latest
    env:
      FIREFOX_BUNDLE_SCRIPT_TOKEN: ${{ secrets.FIREFOX_BUNDLE_SCRIPT_TOKEN }}
    steps:
      - name: Checkout and setup environment
        uses: MetaMask/action-checkout-and-setup@0543b5929698c71e3ccc6ed24eac87825669b5de # v3.5.0
        with:
          is-high-risk-environment: true
          skip-allow-scripts: true
      - name: Build flask
        shell: bash
        run: bash "${GITHUB_WORKSPACE}/.github/scripts/package-firefox-reviewer-artifacts.sh" flask
      - name: Capture failed build
        if: ${{ failure() }}
        uses: actions/upload-artifact@v6
        with:
          name: failed-build-flask-${{ matrix.iteration }}
          path: /tmp/test-bundle-script/firefox-bundle-script/output
