name: Update coverage

on:
  schedule:
    # Once per day at midnight UTC
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
  run-tests:
    name: Run tests
    uses: ./.github/workflows/run-tests.yml

  update-coverage:
    if: ${{ needs.run-tests.outputs.current-coverage > needs.run-tests.outputs.stored-coverage }}
    name: Update coverage
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs:
      - run-tests
    env:
      CURRENT_COVERAGE: ${{ needs.run-tests.outputs.current-coverage }}
      STORED_COVERAGE: ${{ needs.run-tests.outputs.stored-coverage }}
    steps:
      - name: Get token
        id: token
        uses: MetaMask/github-tools/.github/actions/get-token@v1
        with:
          token-exchange-url: ${{ vars.TOKEN_EXCHANGE_URL }}
          permissions: |
            contents: write
            pull_requests: write

      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          token: ${{ steps.token.outputs.token }}

      - name: Update coverage
        run: |
          echo "{ \"coverage\": $CURRENT_COVERAGE }" > coverage.json

      - name: Checkout/create branch, commit, and force push
        run: |
          git config user.name "metamask-ci[bot]"
          git config user.email "271559518+metamask-ci[bot]@users.noreply.github.com"
          git checkout -b metamask-ci/update-coverage
          git add coverage.json
          git commit -m "chore: Update coverage.json"
          git push -f origin metamask-ci/update-coverage

      - name: Create/update pull request
        env:
          GITHUB_TOKEN: ${{ steps.token.outputs.token }}
        run: |
          gh pr create --title "chore: Update coverage.json" --body "This PR is automatically opened to update the coverage.json file when test coverage increases. Coverage increased from $STORED_COVERAGE% to $CURRENT_COVERAGE%." --base main --head metamaskbot/update-coverage || gh pr edit --body "This PR is automatically opened to update the coverage.json file when test coverage increases. Coverage increased from $STORED_COVERAGE% to $CURRENT_COVERAGE%."
